// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

export interface BillingMeterCustomerMapping {
    /**
     * The key in the meter event payload to use for mapping the event to a customer.
     */
    eventPayloadKey: pulumi.Input<string>;
    /**
     * The method for mapping a meter event to a customer. Must be `byId`.
     */
    type: pulumi.Input<string>;
}

export interface BillingMeterDefaultAggregation {
    /**
     * Specifies how events are aggregated. Allowed values are `count` to count the number of events, `sum` to sum each event's value and `last` to take the last event's value in the window.
     */
    formula: pulumi.Input<string>;
}

export interface BillingMeterValueSettings {
    /**
     * The key in the usage event payload to use as the value for this meter. For example, if the event payload contains usage on a `bytesUsed` field, then set the event*payload*key to \"bytes_used\".
     */
    eventPayloadKey?: pulumi.Input<string | undefined>;
}

export interface CouponAppliesTo {
    /**
     * An array of Product IDs that this Coupon will apply to.
     */
    products?: pulumi.Input<pulumi.Input<string>[] | undefined>;
}

export interface CouponCurrencyOption {
    /**
     * A positive integer representing the amount to subtract from an invoice total.
     */
    amountOff: pulumi.Input<number>;
    key: pulumi.Input<string>;
}

export interface CouponScript {
    /**
     * The configuration values of the script. The keys and values are specific to the script implementation.
     */
    configuration: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    /**
     * The name of the script used to calculate the discount.
     */
    displayName?: pulumi.Input<string | undefined>;
    /**
     * The script implementation ID for this coupon.
     */
    id: pulumi.Input<string>;
}

export interface CustomerAddress {
    /**
     * City, district, suburb, town, or village.
     */
    city?: pulumi.Input<string | undefined>;
    /**
     * A freeform text field for the country. However, in order to activate some tax features, the format should be a two-letter country code ([ISO 3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2)).
     */
    country?: pulumi.Input<string | undefined>;
    /**
     * Address line 1, such as the street, PO Box, or company name.
     */
    line1?: pulumi.Input<string | undefined>;
    /**
     * Address line 2, such as the apartment, suite, unit, or building.
     */
    line2?: pulumi.Input<string | undefined>;
    /**
     * ZIP or postal code.
     */
    postalCode?: pulumi.Input<string | undefined>;
    /**
     * State, county, province, or region.
     */
    state?: pulumi.Input<string | undefined>;
}

export interface CustomerCashBalance {
    /**
     * A hash of all cash balances available to this customer. You cannot delete a customer with any cash balances, even if the balance is 0. Amounts are represented in the [smallest currency unit](https://stripe.com/docs/currencies#zero-decimal).
     */
    available?: pulumi.Input<{[key: string]: pulumi.Input<string>} | undefined>;
    /**
     * The ID of the customer whose cash balance this object represents.
     */
    customer?: pulumi.Input<string | undefined>;
    /**
     * The ID of the account whose cash balance this object represents.
     */
    customerAccount?: pulumi.Input<string | undefined>;
    /**
     * Settings controlling the behavior of the customer's cash balance, such as reconciliation of funds received.
     */
    settings?: pulumi.Input<inputs.CustomerCashBalanceSettings | undefined>;
}

export interface CustomerCashBalanceSettings {
    /**
     * Controls how funds transferred by the customer are applied to payment intents and invoices. Valid options are `automatic`, `manual`, or `merchantDefault`. For more information about these reconciliation modes, see [Reconciliation](https://stripe.com/docs/payments/customer-balance/reconciliation).
     */
    reconciliationMode?: pulumi.Input<string | undefined>;
}

export interface CustomerInvoiceSettings {
    customFields?: pulumi.Input<pulumi.Input<any[]>[] | undefined>;
    /**
     * ID of a payment method that's attached to the customer, to be used as the customer's default payment method for subscriptions and invoices.
     */
    defaultPaymentMethod?: pulumi.Input<string | undefined>;
    /**
     * Default footer to be displayed on invoices for this customer.
     */
    footer?: pulumi.Input<string | undefined>;
    renderingOptions?: pulumi.Input<inputs.CustomerInvoiceSettingsRenderingOptions | undefined>;
}

export interface CustomerInvoiceSettingsRenderingOptions {
    /**
     * How line-item prices and amounts will be displayed with respect to tax on invoice PDFs. One of `excludeTax` or `includeInclusiveTax`. `includeInclusiveTax` will include inclusive tax (and exclude exclusive tax) in invoice PDF amounts. `excludeTax` will exclude all tax (inclusive and exclusive alike) from invoice PDF amounts.
     */
    amountTaxDisplay?: pulumi.Input<string | undefined>;
    /**
     * ID of the invoice rendering template to use for future invoices.
     */
    template?: pulumi.Input<string | undefined>;
}

export interface CustomerShipping {
    /**
     * Customer shipping address.
     */
    address: pulumi.Input<inputs.CustomerShippingAddress>;
    /**
     * The delivery service that shipped a physical product, such as Fedex, UPS, USPS, etc.
     */
    carrier?: pulumi.Input<string | undefined>;
    /**
     * Customer name.
     */
    name: pulumi.Input<string>;
    /**
     * Customer phone (including extension).
     */
    phone?: pulumi.Input<string | undefined>;
    /**
     * The tracking number for a physical product, obtained from the delivery service. If multiple tracking numbers were generated for this purchase, please separate them with commas.
     */
    trackingNumber?: pulumi.Input<string | undefined>;
}

export interface CustomerShippingAddress {
    /**
     * City, district, suburb, town, or village.
     */
    city?: pulumi.Input<string | undefined>;
    /**
     * A freeform text field for the country. However, in order to activate some tax features, the format should be a two-letter country code ([ISO 3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2)).
     */
    country?: pulumi.Input<string | undefined>;
    /**
     * Address line 1, such as the street, PO Box, or company name.
     */
    line1?: pulumi.Input<string | undefined>;
    /**
     * Address line 2, such as the apartment, suite, unit, or building.
     */
    line2?: pulumi.Input<string | undefined>;
    /**
     * ZIP or postal code.
     */
    postalCode?: pulumi.Input<string | undefined>;
    /**
     * State, county, province, or region.
     */
    state?: pulumi.Input<string | undefined>;
}

export interface CustomerTax {
    /**
     * Surfaces if automatic tax computation is possible given the current customer location information.
     */
    automaticTax?: pulumi.Input<string | undefined>;
    ipAddress?: pulumi.Input<string | undefined>;
    /**
     * The tax calculation provider used for location resolution. Defaults to `stripe` when not using a [third-party provider](https://www.terraform.io/tax/third-party-apps).
     */
    provider?: pulumi.Input<string | undefined>;
    /**
     * A flag that indicates when Stripe should validate the customer tax location. Defaults to `deferred`.
     */
    validateLocation?: pulumi.Input<string | undefined>;
}

export interface CustomerTaxIdData {
    /**
     * Type of the tax ID, one of `adNrt`, `aeTrn`, `alTin`, `amTin`, `aoTin`, `arCuit`, `auAbn`, `auArn`, `awTin`, `azTin`, `baTin`, `bbTin`, `bdBin`, `bfIfu`, `bgUic`, `bhVat`, `bjIfu`, `boTin`, `brCnpj`, `brCpf`, `bsTin`, `byTin`, `caBn`, `caGstHst`, `caPstBc`, `caPstMb`, `caPstSk`, `caQst`, `cdNif`, `chUid`, `chVat`, `clTin`, `cmNiu`, `cnTin`, `coNit`, `crTin`, `cvNif`, `deStn`, `doRcn`, `ecRuc`, `egTin`, `esCif`, `etTin`, `euOssVat`, `euVat`, `gbVat`, `geVat`, `gnNif`, `hkBr`, `hrOib`, `huTin`, `idNpwp`, `ilVat`, `inGst`, `isVat`, `jpCn`, `jpRn`, `jpTrn`, `kePin`, `kgTin`, `khTin`, `krBrn`, `kzBin`, `laTin`, `liUid`, `liVat`, `maVat`, `mdVat`, `mePib`, `mkVat`, `mrNif`, `mxRfc`, `myFrp`, `myItn`, `mySst`, `ngTin`, `noVat`, `noVoec`, `npPan`, `nzGst`, `omVat`, `peRuc`, `phTin`, `roTin`, `rsPib`, `ruInn`, `ruKpp`, `saVat`, `sgGst`, `sgUen`, `siTin`, `snNinea`, `srFin`, `svNit`, `thVat`, `tjTin`, `trTin`, `twVat`, `tzVat`, `uaVat`, `ugTin`, `usEin`, `uyRuc`, `uzTin`, `uzVat`, `veRif`, `vnTin`, `zaVat`, `zmTin`, or `zwTin`
     */
    type: pulumi.Input<string>;
    /**
     * Value of the tax ID.
     */
    value: pulumi.Input<string>;
}

export interface PriceCurrencyOption {
    /**
     * When set, provides configuration for the amount to be adjusted by the customer during Checkout Sessions and Payment Links.
     */
    customUnitAmount?: pulumi.Input<inputs.PriceCurrencyOptionCustomUnitAmount | undefined>;
    key: pulumi.Input<string>;
    /**
     * Only required if a [default tax behavior](https://stripe.com/docs/tax/products-prices-tax-categories-tax-behavior#setting-a-default-tax-behavior-(recommended)) was not provided in the Stripe Tax settings. Specifies whether the price is considered inclusive of taxes or exclusive of taxes. One of `inclusive`, `exclusive`, or `unspecified`. Once specified as either `inclusive` or `exclusive`, it cannot be changed.
     */
    taxBehavior?: pulumi.Input<string | undefined>;
    /**
     * Each element represents a pricing tier. This parameter requires `billingScheme` to be set to `tiered`. See also the documentation for `billingScheme`.
     */
    tiers?: pulumi.Input<pulumi.Input<any[]>[] | undefined>;
    /**
     * A positive integer in cents (or local equivalent) (or 0 for a free price) representing how much to charge.
     */
    unitAmount?: pulumi.Input<number | undefined>;
    /**
     * Same as `unitAmount`, but accepts a decimal value in cents (or local equivalent) with at most 12 decimal places. Only one of `unitAmount` and `unitAmountDecimal` can be set.
     */
    unitAmountDecimal?: pulumi.Input<string | undefined>;
}

export interface PriceCurrencyOptionCustomUnitAmount {
    /**
     * Pass in `true` to enable `customUnitAmount`, otherwise omit `customUnitAmount`.
     */
    enabled: pulumi.Input<boolean>;
    /**
     * The maximum unit amount the customer can specify for this item.
     */
    maximum?: pulumi.Input<number | undefined>;
    /**
     * The minimum unit amount the customer can specify for this item. Must be at least the minimum charge amount.
     */
    minimum?: pulumi.Input<number | undefined>;
    /**
     * The starting unit amount which can be updated by the customer.
     */
    preset?: pulumi.Input<number | undefined>;
}

export interface PriceCustomUnitAmount {
    /**
     * The maximum unit amount the customer can specify for this item.
     */
    maximum?: pulumi.Input<number | undefined>;
    /**
     * The minimum unit amount the customer can specify for this item. Must be at least the minimum charge amount.
     */
    minimum?: pulumi.Input<number | undefined>;
    /**
     * The starting unit amount which can be updated by the customer.
     */
    preset?: pulumi.Input<number | undefined>;
}

export interface PriceProductData {
    /**
     * Whether the product is currently available for purchase. Defaults to `true`.
     */
    active?: pulumi.Input<boolean | undefined>;
    /**
     * The identifier for the product. Must be unique. If not provided, an identifier will be randomly generated.
     */
    id?: pulumi.Input<string | undefined>;
    /**
     * Set of [key-value pairs](https://stripe.com/docs/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format. Individual keys can be unset by posting an empty value to them. All keys can be unset by posting an empty value to `metadata`.
     */
    metadata?: pulumi.Input<{[key: string]: pulumi.Input<string>} | undefined>;
    /**
     * The product's name, meant to be displayable to the customer.
     */
    name: pulumi.Input<string>;
    /**
     * An arbitrary string to be displayed on your customer's credit card or bank statement. While most banks display this information consistently, some may display it incorrectly or not at all. This may be up to 22 characters. The statement description may not include `<`, `>`, `\`, `\"`, `'` characters, and will appear on your customer's statement in capital letters. Non-ASCII characters are automatically stripped.
     */
    statementDescriptor?: pulumi.Input<string | undefined>;
    /**
     * A [tax code](https://stripe.com/docs/tax/tax-categories) ID.
     */
    taxCode?: pulumi.Input<string | undefined>;
    /**
     * A label that represents units of this product. When set, this will be included in customers' receipts, invoices, Checkout, and the customer portal.
     */
    unitLabel?: pulumi.Input<string | undefined>;
}

export interface PriceRecurring {
    /**
     * Specifies billing frequency. Either `day`, `week`, `month` or `year`.
     */
    interval: pulumi.Input<string>;
    /**
     * The number of intervals between subscription billings. For example, `interval=month` and `interval_count=3` bills every 3 months. Maximum of three years interval allowed (3 years, 36 months, or 156 weeks).
     */
    intervalCount?: pulumi.Input<number | undefined>;
    /**
     * The meter tracking the usage of a metered price
     */
    meter?: pulumi.Input<string | undefined>;
    /**
     * Default number of trial days when subscribing a customer to this price using [`trial_from_plan=true`](https://stripe.com/docs/api#create_subscription-trial_from_plan).
     */
    trialPeriodDays?: pulumi.Input<number | undefined>;
    /**
     * Configures how the quantity per period should be determined. Can be either `metered` or `licensed`. `licensed` automatically bills the `quantity` set when adding it to a subscription. `metered` aggregates the total usage based on usage records. Defaults to `licensed`.
     */
    usageType?: pulumi.Input<string | undefined>;
}

export interface PriceTier {
    /**
     * The flat billing amount for an entire tier, regardless of the number of units in the tier.
     */
    flatAmount?: pulumi.Input<number | undefined>;
    /**
     * Same as `flatAmount`, but accepts a decimal value representing an integer in the minor units of the currency. Only one of `flatAmount` and `flatAmountDecimal` can be set.
     */
    flatAmountDecimal?: pulumi.Input<string | undefined>;
    /**
     * The per unit billing amount for each individual unit for which this tier applies.
     */
    unitAmount?: pulumi.Input<number | undefined>;
    /**
     * Same as `unitAmount`, but accepts a decimal value in cents (or local equivalent) with at most 12 decimal places. Only one of `unitAmount` and `unitAmountDecimal` can be set.
     */
    unitAmountDecimal?: pulumi.Input<string | undefined>;
    upTo: pulumi.Input<string>;
}

export interface ProductDefaultPriceData {
    /**
     * Three-letter [ISO currency code](https://www.iso.org/iso-4217-currency-codes.html), in lowercase. Must be a [supported currency](https://stripe.com/docs/currencies).
     */
    currency: pulumi.Input<string>;
    /**
     * Prices defined in each available currency option. Each key must be a three-letter [ISO currency code](https://www.iso.org/iso-4217-currency-codes.html) and a [supported currency](https://stripe.com/docs/currencies).
     */
    currencyOptions?: pulumi.Input<pulumi.Input<inputs.ProductDefaultPriceDataCurrencyOption>[] | undefined>;
    /**
     * When set, provides configuration for the amount to be adjusted by the customer during Checkout Sessions and Payment Links.
     */
    customUnitAmount?: pulumi.Input<inputs.ProductDefaultPriceDataCustomUnitAmount | undefined>;
    /**
     * Set of [key-value pairs](https://stripe.com/docs/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format. Individual keys can be unset by posting an empty value to them. All keys can be unset by posting an empty value to `metadata`.
     */
    metadata?: pulumi.Input<{[key: string]: pulumi.Input<string>} | undefined>;
    /**
     * The recurring components of a price such as `interval` and `intervalCount`.
     */
    recurring?: pulumi.Input<inputs.ProductDefaultPriceDataRecurring | undefined>;
    /**
     * Only required if a [default tax behavior](https://stripe.com/docs/tax/products-prices-tax-categories-tax-behavior#setting-a-default-tax-behavior-(recommended)) was not provided in the Stripe Tax settings. Specifies whether the price is considered inclusive of taxes or exclusive of taxes. One of `inclusive`, `exclusive`, or `unspecified`. Once specified as either `inclusive` or `exclusive`, it cannot be changed.
     */
    taxBehavior?: pulumi.Input<string | undefined>;
    /**
     * A positive integer in cents (or local equivalent) (or 0 for a free price) representing how much to charge. One of `unitAmount`, `unitAmountDecimal`, or `customUnitAmount` is required.
     */
    unitAmount?: pulumi.Input<number | undefined>;
    /**
     * Same as `unitAmount`, but accepts a decimal value in cents (or local equivalent) with at most 12 decimal places. Only one of `unitAmount` and `unitAmountDecimal` can be set.
     */
    unitAmountDecimal?: pulumi.Input<string | undefined>;
}

export interface ProductDefaultPriceDataCurrencyOption {
    /**
     * When set, provides configuration for the amount to be adjusted by the customer during Checkout Sessions and Payment Links.
     */
    customUnitAmount?: pulumi.Input<inputs.ProductDefaultPriceDataCurrencyOptionCustomUnitAmount | undefined>;
    key: pulumi.Input<string>;
    /**
     * Only required if a [default tax behavior](https://stripe.com/docs/tax/products-prices-tax-categories-tax-behavior#setting-a-default-tax-behavior-(recommended)) was not provided in the Stripe Tax settings. Specifies whether the price is considered inclusive of taxes or exclusive of taxes. One of `inclusive`, `exclusive`, or `unspecified`. Once specified as either `inclusive` or `exclusive`, it cannot be changed.
     */
    taxBehavior?: pulumi.Input<string | undefined>;
    /**
     * Each element represents a pricing tier. This parameter requires `billingScheme` to be set to `tiered`. See also the documentation for `billingScheme`.
     */
    tiers?: pulumi.Input<pulumi.Input<any[]>[] | undefined>;
    /**
     * A positive integer in cents (or local equivalent) (or 0 for a free price) representing how much to charge.
     */
    unitAmount?: pulumi.Input<number | undefined>;
    /**
     * Same as `unitAmount`, but accepts a decimal value in cents (or local equivalent) with at most 12 decimal places. Only one of `unitAmount` and `unitAmountDecimal` can be set.
     */
    unitAmountDecimal?: pulumi.Input<string | undefined>;
}

export interface ProductDefaultPriceDataCurrencyOptionCustomUnitAmount {
    /**
     * Pass in `true` to enable `customUnitAmount`, otherwise omit `customUnitAmount`.
     */
    enabled: pulumi.Input<boolean>;
    /**
     * The maximum unit amount the customer can specify for this item.
     */
    maximum?: pulumi.Input<number | undefined>;
    /**
     * The minimum unit amount the customer can specify for this item. Must be at least the minimum charge amount.
     */
    minimum?: pulumi.Input<number | undefined>;
    /**
     * The starting unit amount which can be updated by the customer.
     */
    preset?: pulumi.Input<number | undefined>;
}

export interface ProductDefaultPriceDataCustomUnitAmount {
    /**
     * Pass in `true` to enable `customUnitAmount`, otherwise omit `customUnitAmount`.
     */
    enabled: pulumi.Input<boolean>;
    /**
     * The maximum unit amount the customer can specify for this item.
     */
    maximum?: pulumi.Input<number | undefined>;
    /**
     * The minimum unit amount the customer can specify for this item. Must be at least the minimum charge amount.
     */
    minimum?: pulumi.Input<number | undefined>;
    /**
     * The starting unit amount which can be updated by the customer.
     */
    preset?: pulumi.Input<number | undefined>;
}

export interface ProductDefaultPriceDataRecurring {
    /**
     * Specifies billing frequency. Either `day`, `week`, `month` or `year`.
     */
    interval: pulumi.Input<string>;
    /**
     * The number of intervals between subscription billings. For example, `interval=month` and `interval_count=3` bills every 3 months. Maximum of three years interval allowed (3 years, 36 months, or 156 weeks).
     */
    intervalCount?: pulumi.Input<number | undefined>;
}

export interface ProductMarketingFeature {
    /**
     * The marketing feature name. Up to 80 characters long.
     */
    name: pulumi.Input<string>;
}

export interface ProductPackageDimensions {
    /**
     * Height, in inches. Maximum precision is 2 decimal places.
     */
    height: pulumi.Input<number>;
    /**
     * Length, in inches. Maximum precision is 2 decimal places.
     */
    length: pulumi.Input<number>;
    /**
     * Weight, in ounces. Maximum precision is 2 decimal places.
     */
    weight: pulumi.Input<number>;
    /**
     * Width, in inches. Maximum precision is 2 decimal places.
     */
    width: pulumi.Input<number>;
}

export interface PromotionCodePromotion {
    /**
     * If promotion `type` is `coupon`, the coupon for this promotion code.
     */
    coupon?: pulumi.Input<string | undefined>;
    /**
     * Specifies the type of promotion.
     */
    type: pulumi.Input<string>;
}

export interface PromotionCodeRestrictions {
    /**
     * Promotion codes defined in each available currency option. Each key must be a three-letter [ISO currency code](https://www.iso.org/iso-4217-currency-codes.html) and a [supported currency](https://stripe.com/docs/currencies).
     */
    currencyOptions?: pulumi.Input<pulumi.Input<inputs.PromotionCodeRestrictionsCurrencyOption>[] | undefined>;
    /**
     * A Boolean indicating if the Promotion Code should only be redeemed for Customers without any successful payments or invoices
     */
    firstTimeTransaction?: pulumi.Input<boolean | undefined>;
    /**
     * Minimum amount required to redeem this Promotion Code into a Coupon (e.g., a purchase must be $100 or more to work).
     */
    minimumAmount?: pulumi.Input<number | undefined>;
    /**
     * Three-letter [ISO code](https://stripe.com/docs/currencies) for minimum_amount
     */
    minimumAmountCurrency?: pulumi.Input<string | undefined>;
}

export interface PromotionCodeRestrictionsCurrencyOption {
    key: pulumi.Input<string>;
    /**
     * Minimum amount required to redeem this Promotion Code into a Coupon (e.g., a purchase must be $100 or more to work).
     */
    minimumAmount?: pulumi.Input<number | undefined>;
}

export interface ShippingRateDeliveryEstimate {
    /**
     * The upper bound of the estimated range. If empty, represents no upper bound i.e., infinite.
     */
    maximum?: pulumi.Input<inputs.ShippingRateDeliveryEstimateMaximum | undefined>;
    /**
     * The lower bound of the estimated range. If empty, represents no lower bound.
     */
    minimum?: pulumi.Input<inputs.ShippingRateDeliveryEstimateMinimum | undefined>;
}

export interface ShippingRateDeliveryEstimateMaximum {
    /**
     * A unit of time.
     */
    unit: pulumi.Input<string>;
    /**
     * Must be greater than 0.
     */
    value: pulumi.Input<number>;
}

export interface ShippingRateDeliveryEstimateMinimum {
    /**
     * A unit of time.
     */
    unit: pulumi.Input<string>;
    /**
     * Must be greater than 0.
     */
    value: pulumi.Input<number>;
}

export interface ShippingRateFixedAmount {
    /**
     * A non-negative integer in cents representing how much to charge.
     */
    amount: pulumi.Input<number>;
    /**
     * Three-letter [ISO currency code](https://www.iso.org/iso-4217-currency-codes.html), in lowercase. Must be a [supported currency](https://stripe.com/docs/currencies).
     */
    currency: pulumi.Input<string>;
    /**
     * Shipping rates defined in each available currency option. Each key must be a three-letter [ISO currency code](https://www.iso.org/iso-4217-currency-codes.html) and a [supported currency](https://stripe.com/docs/currencies).
     */
    currencyOptions?: pulumi.Input<pulumi.Input<inputs.ShippingRateFixedAmountCurrencyOption>[] | undefined>;
}

export interface ShippingRateFixedAmountCurrencyOption {
    /**
     * A non-negative integer in cents representing how much to charge.
     */
    amount: pulumi.Input<number>;
    key: pulumi.Input<string>;
    /**
     * Specifies whether the rate is considered inclusive of taxes or exclusive of taxes. One of `inclusive`, `exclusive`, or `unspecified`.
     */
    taxBehavior?: pulumi.Input<string | undefined>;
}

export interface V2BillingLicenseFeeTier {
    /**
     * Price for the entire tier, represented as a decimal string in minor currency units with at most 12 decimal places.
     */
    flatAmount?: pulumi.Input<string | undefined>;
    /**
     * Per-unit price for units included in this tier, represented as a decimal string in minor currency units with at most 12 decimal places.
     */
    unitAmount?: pulumi.Input<string | undefined>;
    /**
     * Up to and including this quantity will be contained in the tier. Only one of `upToDecimal` and `upToInf` may be set.
     */
    upToDecimal?: pulumi.Input<string | undefined>;
    /**
     * No upper bound to this tier. Only one of `upToDecimal` and `upToInf` may be set.
     */
    upToInf?: pulumi.Input<string | undefined>;
}

export interface V2BillingMeteredItemMeterSegmentCondition {
    /**
     * A Meter dimension.
     */
    dimension: pulumi.Input<string>;
    /**
     * To count usage towards this metered item, the dimension must have this value.
     */
    value: pulumi.Input<string>;
}

export interface V2BillingPricingPlanComponentLicenseFee {
    /**
     * The ID of the License Fee.
     */
    id: pulumi.Input<string>;
    /**
     * The version of the LicenseFee. Defaults to 'latest', if not specified.
     */
    version?: pulumi.Input<string | undefined>;
}

export interface V2BillingPricingPlanComponentRateCard {
    /**
     * The ID of the Rate Card.
     */
    id: pulumi.Input<string>;
    /**
     * The version of the RateCard. Defaults to 'latest', if not specified.
     */
    version?: pulumi.Input<string | undefined>;
}

export interface V2BillingPricingPlanComponentServiceAction {
    /**
     * The ID of the service action.
     */
    id: pulumi.Input<string>;
}

export interface V2BillingRateCardRateTier {
    /**
     * Price for the entire tier, represented as a decimal string in minor currency units with at most 12 decimal places.
     */
    flatAmount?: pulumi.Input<string | undefined>;
    /**
     * Per-unit price for units included in this tier, represented as a decimal string in minor currency units with at most 12 decimal places.
     */
    unitAmount?: pulumi.Input<string | undefined>;
    /**
     * Up to and including this quantity will be contained in the tier. Only one of `upToDecimal` and `upToInf` may be set.
     */
    upToDecimal?: pulumi.Input<string | undefined>;
    /**
     * No upper bound to this tier. Only one of `upToDecimal` and `upToInf` may be set.
     */
    upToInf?: pulumi.Input<string | undefined>;
}

export interface V2BillingServiceActionCreditGrant {
    /**
     * The amount of the credit grant.
     */
    amount: pulumi.Input<inputs.V2BillingServiceActionCreditGrantAmount>;
    /**
     * Defines the scope where the credit grant is applicable.
     */
    applicabilityConfig: pulumi.Input<inputs.V2BillingServiceActionCreditGrantApplicabilityConfig>;
    /**
     * The category of the credit grant.
     */
    category?: pulumi.Input<string | undefined>;
    /**
     * The expiry configuration for the credit grant.
     */
    expiryConfig: pulumi.Input<inputs.V2BillingServiceActionCreditGrantExpiryConfig>;
    /**
     * A descriptive name shown in dashboard.
     */
    name: pulumi.Input<string>;
    /**
     * The desired priority for applying this credit grant. If not specified, it will be set to the default value of 50. The highest priority is 0 and the lowest is 100.
     */
    priority?: pulumi.Input<number | undefined>;
}

export interface V2BillingServiceActionCreditGrantAmount {
    /**
     * The custom pricing unit amount of the credit grant. Required if `type` is `customPricingUnit`.
     */
    customPricingUnit?: pulumi.Input<inputs.V2BillingServiceActionCreditGrantAmountCustomPricingUnit | undefined>;
    /**
     * The monetary amount of the credit grant. Required if `type` is `monetary`.
     */
    monetary?: pulumi.Input<inputs.V2BillingServiceActionCreditGrantAmountMonetary | undefined>;
    /**
     * The type of the credit grant amount. We currently support `monetary` and `customPricingUnit` billing credits.
     */
    type: pulumi.Input<string>;
}

export interface V2BillingServiceActionCreditGrantAmountCustomPricingUnit {
    /**
     * The id of the custom pricing unit.
     */
    id: pulumi.Input<string>;
    /**
     * The value of the credit grant, decimal value represented as a string.
     */
    value: pulumi.Input<string>;
}

export interface V2BillingServiceActionCreditGrantAmountMonetary {
    /**
     * Three-letter [ISO currency code](https://www.iso.org/iso-4217-currency-codes.html), in lowercase. Must be a [supported currency](https://stripe.com/docs/currencies).
     */
    currency: pulumi.Input<string>;
    /**
     * A non-negative integer representing how much to charge in the [smallest currency unit](https://docs.stripe.com/currencies#minor-units).
     */
    value: pulumi.Input<number>;
}

export interface V2BillingServiceActionCreditGrantApplicabilityConfig {
    /**
     * The applicability scope of the credit grant.
     */
    scope: pulumi.Input<inputs.V2BillingServiceActionCreditGrantApplicabilityConfigScope>;
}

export interface V2BillingServiceActionCreditGrantApplicabilityConfigScope {
    /**
     * The billable items to apply the credit grant to.
     */
    billableItems?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * The price type that credit grants can apply to. We currently only support the `metered` price type. This will apply to metered prices and rate cards. Cannot be used in combination with `billableItems`.
     */
    priceType?: pulumi.Input<string | undefined>;
}

export interface V2BillingServiceActionCreditGrantExpiryConfig {
    /**
     * The type of the expiry configuration. We currently support `endOfServicePeriod`.
     */
    type: pulumi.Input<string>;
}

export interface V2CoreEventDestinationAmazonEventbridge {
    /**
     * The AWS account ID.
     */
    awsAccountId: pulumi.Input<string>;
    /**
     * The ARN of the AWS event source.
     */
    awsEventSourceArn?: pulumi.Input<string | undefined>;
    /**
     * The state of the AWS event source.
     */
    awsEventSourceStatus?: pulumi.Input<string | undefined>;
    /**
     * The region of the AWS event source.
     */
    awsRegion: pulumi.Input<string>;
}

export interface V2CoreEventDestinationWebhookEndpoint {
    /**
     * The signing secret of the webhook endpoint, only includable on creation.
     */
    signingSecret?: pulumi.Input<string | undefined>;
    /**
     * The URL of the webhook endpoint.
     */
    url: pulumi.Input<string>;
}
