// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * A credit grant is an API resource that documents the allocation of some billing credits to a customer.
 *
 * Related guide: [Billing credits](https://docs.stripe.com/billing/subscriptions/usage-based/billing-credits)
 */
export class BillingCreditGrant extends pulumi.CustomResource {
    /**
     * Get an existing BillingCreditGrant resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: BillingCreditGrantState, opts?: pulumi.CustomResourceOptions): BillingCreditGrant {
        return new BillingCreditGrant(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'stripe:index/billingCreditGrant:BillingCreditGrant';

    /**
     * Returns true if the given object is an instance of BillingCreditGrant.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is BillingCreditGrant {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === BillingCreditGrant.__pulumiType;
    }

    declare public readonly amount: pulumi.Output<outputs.BillingCreditGrantAmount>;
    declare public readonly applicabilityConfig: pulumi.Output<outputs.BillingCreditGrantApplicabilityConfig>;
    /**
     * The category of this credit grant. This is for tracking purposes and isn't displayed to the customer.
     */
    declare public readonly category: pulumi.Output<string>;
    /**
     * Time at which the object was created. Measured in seconds since the Unix epoch.
     */
    declare public /*out*/ readonly created: pulumi.Output<number>;
    /**
     * ID of the customer receiving the billing credits.
     */
    declare public readonly customer: pulumi.Output<string>;
    /**
     * ID of the account representing the customer receiving the billing credits
     */
    declare public readonly customerAccount: pulumi.Output<string>;
    /**
     * The time when the billing credits become effective-when they're eligible for use.
     */
    declare public readonly effectiveAt: pulumi.Output<number>;
    /**
     * The time when the billing credits expire. If not present, the billing credits don't expire.
     */
    declare public readonly expiresAt: pulumi.Output<number>;
    /**
     * If the object exists in live mode, the value is `true`. If the object exists in test mode, the value is `false`.
     */
    declare public /*out*/ readonly livemode: pulumi.Output<boolean>;
    /**
     * Set of [key-value pairs](https://docs.stripe.com/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format.
     */
    declare public readonly metadata: pulumi.Output<{[key: string]: string}>;
    /**
     * A descriptive name shown in dashboard.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * String representing the object's type. Objects of the same type share the same value.
     */
    declare public /*out*/ readonly object: pulumi.Output<string>;
    /**
     * The priority for applying this credit grant. The highest priority is 0 and the lowest is 100.
     */
    declare public readonly priority: pulumi.Output<number>;
    /**
     * ID of the test clock this credit grant belongs to.
     */
    declare public /*out*/ readonly testClock: pulumi.Output<string>;
    /**
     * Time at which the object was last updated. Measured in seconds since the Unix epoch.
     */
    declare public /*out*/ readonly updated: pulumi.Output<number>;
    /**
     * The time when this credit grant was voided. If not present, the credit grant hasn't been voided.
     */
    declare public /*out*/ readonly voidedAt: pulumi.Output<number>;

    /**
     * Create a BillingCreditGrant resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: BillingCreditGrantArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: BillingCreditGrantArgs | BillingCreditGrantState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as BillingCreditGrantState | undefined;
            resourceInputs["amount"] = state?.amount;
            resourceInputs["applicabilityConfig"] = state?.applicabilityConfig;
            resourceInputs["category"] = state?.category;
            resourceInputs["created"] = state?.created;
            resourceInputs["customer"] = state?.customer;
            resourceInputs["customerAccount"] = state?.customerAccount;
            resourceInputs["effectiveAt"] = state?.effectiveAt;
            resourceInputs["expiresAt"] = state?.expiresAt;
            resourceInputs["livemode"] = state?.livemode;
            resourceInputs["metadata"] = state?.metadata;
            resourceInputs["name"] = state?.name;
            resourceInputs["object"] = state?.object;
            resourceInputs["priority"] = state?.priority;
            resourceInputs["testClock"] = state?.testClock;
            resourceInputs["updated"] = state?.updated;
            resourceInputs["voidedAt"] = state?.voidedAt;
        } else {
            const args = argsOrState as BillingCreditGrantArgs | undefined;
            if (args?.amount === undefined && !opts.urn) {
                throw new Error("Missing required property 'amount'");
            }
            if (args?.applicabilityConfig === undefined && !opts.urn) {
                throw new Error("Missing required property 'applicabilityConfig'");
            }
            resourceInputs["amount"] = args?.amount;
            resourceInputs["applicabilityConfig"] = args?.applicabilityConfig;
            resourceInputs["category"] = args?.category;
            resourceInputs["customer"] = args?.customer;
            resourceInputs["customerAccount"] = args?.customerAccount;
            resourceInputs["effectiveAt"] = args?.effectiveAt;
            resourceInputs["expiresAt"] = args?.expiresAt;
            resourceInputs["metadata"] = args?.metadata;
            resourceInputs["name"] = args?.name;
            resourceInputs["priority"] = args?.priority;
            resourceInputs["created"] = undefined /*out*/;
            resourceInputs["livemode"] = undefined /*out*/;
            resourceInputs["object"] = undefined /*out*/;
            resourceInputs["testClock"] = undefined /*out*/;
            resourceInputs["updated"] = undefined /*out*/;
            resourceInputs["voidedAt"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(BillingCreditGrant.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering BillingCreditGrant resources.
 */
export interface BillingCreditGrantState {
    amount?: pulumi.Input<inputs.BillingCreditGrantAmount | undefined>;
    applicabilityConfig?: pulumi.Input<inputs.BillingCreditGrantApplicabilityConfig | undefined>;
    /**
     * The category of this credit grant. This is for tracking purposes and isn't displayed to the customer.
     */
    category?: pulumi.Input<string | undefined>;
    /**
     * Time at which the object was created. Measured in seconds since the Unix epoch.
     */
    created?: pulumi.Input<number | undefined>;
    /**
     * ID of the customer receiving the billing credits.
     */
    customer?: pulumi.Input<string | undefined>;
    /**
     * ID of the account representing the customer receiving the billing credits
     */
    customerAccount?: pulumi.Input<string | undefined>;
    /**
     * The time when the billing credits become effective-when they're eligible for use.
     */
    effectiveAt?: pulumi.Input<number | undefined>;
    /**
     * The time when the billing credits expire. If not present, the billing credits don't expire.
     */
    expiresAt?: pulumi.Input<number | undefined>;
    /**
     * If the object exists in live mode, the value is `true`. If the object exists in test mode, the value is `false`.
     */
    livemode?: pulumi.Input<boolean | undefined>;
    /**
     * Set of [key-value pairs](https://docs.stripe.com/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format.
     */
    metadata?: pulumi.Input<{[key: string]: pulumi.Input<string>} | undefined>;
    /**
     * A descriptive name shown in dashboard.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * String representing the object's type. Objects of the same type share the same value.
     */
    object?: pulumi.Input<string | undefined>;
    /**
     * The priority for applying this credit grant. The highest priority is 0 and the lowest is 100.
     */
    priority?: pulumi.Input<number | undefined>;
    /**
     * ID of the test clock this credit grant belongs to.
     */
    testClock?: pulumi.Input<string | undefined>;
    /**
     * Time at which the object was last updated. Measured in seconds since the Unix epoch.
     */
    updated?: pulumi.Input<number | undefined>;
    /**
     * The time when this credit grant was voided. If not present, the credit grant hasn't been voided.
     */
    voidedAt?: pulumi.Input<number | undefined>;
}

/**
 * The set of arguments for constructing a BillingCreditGrant resource.
 */
export interface BillingCreditGrantArgs {
    amount: pulumi.Input<inputs.BillingCreditGrantAmount>;
    applicabilityConfig: pulumi.Input<inputs.BillingCreditGrantApplicabilityConfig>;
    /**
     * The category of this credit grant. This is for tracking purposes and isn't displayed to the customer.
     */
    category?: pulumi.Input<string | undefined>;
    /**
     * ID of the customer receiving the billing credits.
     */
    customer?: pulumi.Input<string | undefined>;
    /**
     * ID of the account representing the customer receiving the billing credits
     */
    customerAccount?: pulumi.Input<string | undefined>;
    /**
     * The time when the billing credits become effective-when they're eligible for use.
     */
    effectiveAt?: pulumi.Input<number | undefined>;
    /**
     * The time when the billing credits expire. If not present, the billing credits don't expire.
     */
    expiresAt?: pulumi.Input<number | undefined>;
    /**
     * Set of [key-value pairs](https://docs.stripe.com/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format.
     */
    metadata?: pulumi.Input<{[key: string]: pulumi.Input<string>} | undefined>;
    /**
     * A descriptive name shown in dashboard.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * The priority for applying this credit grant. The highest priority is 0 and the lowest is 100.
     */
    priority?: pulumi.Input<number | undefined>;
}
