// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * A coupon contains information about a percent-off or amount-off discount you might want to apply to a customer. Coupons may be applied to [subscriptions](https://stripe.com/docs/api#subscriptions), [invoices](https://stripe.com/docs/api#invoices), [checkout sessions](https://stripe.com/docs/api/checkout/sessions), [quotes](https://stripe.com/docs/api#quotes), and more. Coupons do not work with conventional one-off [charges](https://stripe.com/docs/api#create_charge) or [payment intents](https://stripe.com/docs/api/payment_intents).
 */
export class Coupon extends pulumi.CustomResource {
    /**
     * Get an existing Coupon resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: CouponState, opts?: pulumi.CustomResourceOptions): Coupon {
        return new Coupon(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'stripe:index/coupon:Coupon';

    /**
     * Returns true if the given object is an instance of Coupon.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Coupon {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Coupon.__pulumiType;
    }

    /**
     * A positive integer representing the amount to subtract from an invoice total (required if `percentOff` is not passed).
     */
    declare public readonly amountOff: pulumi.Output<number>;
    /**
     * A hash containing directions for what this Coupon will apply discounts to.
     */
    declare public readonly appliesTo: pulumi.Output<outputs.CouponAppliesTo | undefined>;
    /**
     * Three-letter [ISO code for the currency](https://stripe.com/docs/currencies) of the `amountOff` parameter (required if `amountOff` is passed).
     */
    declare public readonly currency: pulumi.Output<string>;
    /**
     * Coupons defined in each available currency option (only supported if `amountOff` is passed). Each key must be a three-letter [ISO currency code](https://www.iso.org/iso-4217-currency-codes.html) and a [supported currency](https://stripe.com/docs/currencies).
     */
    declare public readonly currencyOptions: pulumi.Output<outputs.CouponCurrencyOption[]>;
    /**
     * Specifies how long the discount will be in effect if used on a subscription. Defaults to `once`.
     */
    declare public readonly duration: pulumi.Output<string>;
    /**
     * Required only if `duration` is `repeating`, in which case it must be a positive integer that specifies the number of months the discount will be in effect.
     */
    declare public readonly durationInMonths: pulumi.Output<number>;
    /**
     * A positive integer specifying the number of times the coupon can be redeemed before it's no longer valid. For example, you might have a 50% off coupon that the first 20 readers of your blog can use.
     */
    declare public readonly maxRedemptions: pulumi.Output<number>;
    declare public readonly metadata: pulumi.Output<{[key: string]: string}>;
    /**
     * Name of the coupon displayed to customers on, for instance invoices, or receipts. By default the `id` is shown if `name` is not set.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * A positive float larger than 0, and smaller or equal to 100, that represents the discount the coupon will apply (required if `amountOff` is not passed).
     */
    declare public readonly percentOff: pulumi.Output<number>;
    /**
     * Unix timestamp specifying the last time at which the coupon can be redeemed. After the redeemBy date, the coupon can no longer be applied to new customers.
     */
    declare public readonly redeemBy: pulumi.Output<number>;
    /**
     * Configuration of the [script](https://docs.stripe.com/billing/subscriptions/script-coupons) used to calculate the discount.
     */
    declare public readonly script: pulumi.Output<outputs.CouponScript | undefined>;
    /**
     * Number of times this coupon has been applied to a customer.
     */
    declare public /*out*/ readonly timesRedeemed: pulumi.Output<number>;
    /**
     * One of `amountOff`, `percentOff`, or `script`. Describes the type of coupon logic used to calculate the discount.
     */
    declare public /*out*/ readonly type: pulumi.Output<string>;
    /**
     * Taking account of the above properties, whether this coupon can still be applied to a customer.
     */
    declare public /*out*/ readonly valid: pulumi.Output<boolean>;

    /**
     * Create a Coupon resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: CouponArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: CouponArgs | CouponState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as CouponState | undefined;
            resourceInputs["amountOff"] = state?.amountOff;
            resourceInputs["appliesTo"] = state?.appliesTo;
            resourceInputs["currency"] = state?.currency;
            resourceInputs["currencyOptions"] = state?.currencyOptions;
            resourceInputs["duration"] = state?.duration;
            resourceInputs["durationInMonths"] = state?.durationInMonths;
            resourceInputs["maxRedemptions"] = state?.maxRedemptions;
            resourceInputs["metadata"] = state?.metadata;
            resourceInputs["name"] = state?.name;
            resourceInputs["percentOff"] = state?.percentOff;
            resourceInputs["redeemBy"] = state?.redeemBy;
            resourceInputs["script"] = state?.script;
            resourceInputs["timesRedeemed"] = state?.timesRedeemed;
            resourceInputs["type"] = state?.type;
            resourceInputs["valid"] = state?.valid;
        } else {
            const args = argsOrState as CouponArgs | undefined;
            resourceInputs["amountOff"] = args?.amountOff;
            resourceInputs["appliesTo"] = args?.appliesTo;
            resourceInputs["currency"] = args?.currency;
            resourceInputs["currencyOptions"] = args?.currencyOptions;
            resourceInputs["duration"] = args?.duration;
            resourceInputs["durationInMonths"] = args?.durationInMonths;
            resourceInputs["maxRedemptions"] = args?.maxRedemptions;
            resourceInputs["metadata"] = args?.metadata;
            resourceInputs["name"] = args?.name;
            resourceInputs["percentOff"] = args?.percentOff;
            resourceInputs["redeemBy"] = args?.redeemBy;
            resourceInputs["script"] = args?.script;
            resourceInputs["timesRedeemed"] = undefined /*out*/;
            resourceInputs["type"] = undefined /*out*/;
            resourceInputs["valid"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Coupon.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering Coupon resources.
 */
export interface CouponState {
    /**
     * A positive integer representing the amount to subtract from an invoice total (required if `percentOff` is not passed).
     */
    amountOff?: pulumi.Input<number | undefined>;
    /**
     * A hash containing directions for what this Coupon will apply discounts to.
     */
    appliesTo?: pulumi.Input<inputs.CouponAppliesTo | undefined>;
    /**
     * Three-letter [ISO code for the currency](https://stripe.com/docs/currencies) of the `amountOff` parameter (required if `amountOff` is passed).
     */
    currency?: pulumi.Input<string | undefined>;
    /**
     * Coupons defined in each available currency option (only supported if `amountOff` is passed). Each key must be a three-letter [ISO currency code](https://www.iso.org/iso-4217-currency-codes.html) and a [supported currency](https://stripe.com/docs/currencies).
     */
    currencyOptions?: pulumi.Input<pulumi.Input<inputs.CouponCurrencyOption>[] | undefined>;
    /**
     * Specifies how long the discount will be in effect if used on a subscription. Defaults to `once`.
     */
    duration?: pulumi.Input<string | undefined>;
    /**
     * Required only if `duration` is `repeating`, in which case it must be a positive integer that specifies the number of months the discount will be in effect.
     */
    durationInMonths?: pulumi.Input<number | undefined>;
    /**
     * A positive integer specifying the number of times the coupon can be redeemed before it's no longer valid. For example, you might have a 50% off coupon that the first 20 readers of your blog can use.
     */
    maxRedemptions?: pulumi.Input<number | undefined>;
    metadata?: pulumi.Input<{[key: string]: pulumi.Input<string>} | undefined>;
    /**
     * Name of the coupon displayed to customers on, for instance invoices, or receipts. By default the `id` is shown if `name` is not set.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * A positive float larger than 0, and smaller or equal to 100, that represents the discount the coupon will apply (required if `amountOff` is not passed).
     */
    percentOff?: pulumi.Input<number | undefined>;
    /**
     * Unix timestamp specifying the last time at which the coupon can be redeemed. After the redeemBy date, the coupon can no longer be applied to new customers.
     */
    redeemBy?: pulumi.Input<number | undefined>;
    /**
     * Configuration of the [script](https://docs.stripe.com/billing/subscriptions/script-coupons) used to calculate the discount.
     */
    script?: pulumi.Input<inputs.CouponScript | undefined>;
    /**
     * Number of times this coupon has been applied to a customer.
     */
    timesRedeemed?: pulumi.Input<number | undefined>;
    /**
     * One of `amountOff`, `percentOff`, or `script`. Describes the type of coupon logic used to calculate the discount.
     */
    type?: pulumi.Input<string | undefined>;
    /**
     * Taking account of the above properties, whether this coupon can still be applied to a customer.
     */
    valid?: pulumi.Input<boolean | undefined>;
}

/**
 * The set of arguments for constructing a Coupon resource.
 */
export interface CouponArgs {
    /**
     * A positive integer representing the amount to subtract from an invoice total (required if `percentOff` is not passed).
     */
    amountOff?: pulumi.Input<number | undefined>;
    /**
     * A hash containing directions for what this Coupon will apply discounts to.
     */
    appliesTo?: pulumi.Input<inputs.CouponAppliesTo | undefined>;
    /**
     * Three-letter [ISO code for the currency](https://stripe.com/docs/currencies) of the `amountOff` parameter (required if `amountOff` is passed).
     */
    currency?: pulumi.Input<string | undefined>;
    /**
     * Coupons defined in each available currency option (only supported if `amountOff` is passed). Each key must be a three-letter [ISO currency code](https://www.iso.org/iso-4217-currency-codes.html) and a [supported currency](https://stripe.com/docs/currencies).
     */
    currencyOptions?: pulumi.Input<pulumi.Input<inputs.CouponCurrencyOption>[] | undefined>;
    /**
     * Specifies how long the discount will be in effect if used on a subscription. Defaults to `once`.
     */
    duration?: pulumi.Input<string | undefined>;
    /**
     * Required only if `duration` is `repeating`, in which case it must be a positive integer that specifies the number of months the discount will be in effect.
     */
    durationInMonths?: pulumi.Input<number | undefined>;
    /**
     * A positive integer specifying the number of times the coupon can be redeemed before it's no longer valid. For example, you might have a 50% off coupon that the first 20 readers of your blog can use.
     */
    maxRedemptions?: pulumi.Input<number | undefined>;
    metadata?: pulumi.Input<{[key: string]: pulumi.Input<string>} | undefined>;
    /**
     * Name of the coupon displayed to customers on, for instance invoices, or receipts. By default the `id` is shown if `name` is not set.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * A positive float larger than 0, and smaller or equal to 100, that represents the discount the coupon will apply (required if `amountOff` is not passed).
     */
    percentOff?: pulumi.Input<number | undefined>;
    /**
     * Unix timestamp specifying the last time at which the coupon can be redeemed. After the redeemBy date, the coupon can no longer be applied to new customers.
     */
    redeemBy?: pulumi.Input<number | undefined>;
    /**
     * Configuration of the [script](https://docs.stripe.com/billing/subscriptions/script-coupons) used to calculate the discount.
     */
    script?: pulumi.Input<inputs.CouponScript | undefined>;
}
