// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * Issue a credit note to adjust an invoice's amount after the invoice is finalized.
 *
 * Related guide: [Credit notes](https://docs.stripe.com/billing/invoices/credit-notes)
 */
export class CreditNote extends pulumi.CustomResource {
    /**
     * Get an existing CreditNote resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: CreditNoteState, opts?: pulumi.CustomResourceOptions): CreditNote {
        return new CreditNote(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'stripe:index/creditNote:CreditNote';

    /**
     * Returns true if the given object is an instance of CreditNote.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is CreditNote {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === CreditNote.__pulumiType;
    }

    /**
     * The integer amount in cents (or local equivalent) representing the total amount of the credit note, including tax.
     */
    declare public readonly amount: pulumi.Output<number>;
    /**
     * This is the sum of all the shipping amounts.
     */
    declare public /*out*/ readonly amountShipping: pulumi.Output<number>;
    /**
     * Time at which the object was created. Measured in seconds since the Unix epoch.
     */
    declare public /*out*/ readonly created: pulumi.Output<number>;
    /**
     * **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * The integer amount in cents (or local equivalent) representing the amount to credit the customer's balance, which will be automatically applied to their next invoice.
     */
    declare public readonly creditAmount: pulumi.Output<number | undefined>;
    /**
     * Three-letter [ISO currency code](https://www.iso.org/iso-4217-currency-codes.html), in lowercase. Must be a [supported currency](https://stripe.com/docs/currencies).
     */
    declare public /*out*/ readonly currency: pulumi.Output<string>;
    /**
     * ID of the customer.
     */
    declare public /*out*/ readonly customer: pulumi.Output<string>;
    /**
     * Customer balance transaction related to this credit note.
     */
    declare public /*out*/ readonly customerBalanceTransaction: pulumi.Output<string>;
    /**
     * The integer amount in cents (or local equivalent) representing the total amount of discount that was credited.
     */
    declare public /*out*/ readonly discountAmount: pulumi.Output<number>;
    /**
     * The aggregate amounts calculated per discount for all line items.
     */
    declare public /*out*/ readonly discountAmounts: pulumi.Output<outputs.CreditNoteDiscountAmount[]>;
    /**
     * The date when this credit note is in effect. Same as `created` unless overwritten. When defined, this value replaces the system-generated 'Date of issue' printed on the credit note PDF.
     */
    declare public readonly effectiveAt: pulumi.Output<number>;
    /**
     * **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * Type of email to send to the customer, one of `creditNote` or `none` and the default is `creditNote`.
     */
    declare public readonly emailType: pulumi.Output<string | undefined>;
    /**
     * ID of the invoice.
     */
    declare public readonly invoice: pulumi.Output<string>;
    /**
     * If the object exists in live mode, the value is `true`. If the object exists in test mode, the value is `false`.
     */
    declare public /*out*/ readonly livemode: pulumi.Output<boolean>;
    /**
     * Customer-facing text that appears on the credit note PDF.
     */
    declare public readonly memo: pulumi.Output<string>;
    /**
     * Set of [key-value pairs](https://docs.stripe.com/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format.
     */
    declare public readonly metadata: pulumi.Output<{[key: string]: string}>;
    /**
     * A unique number that identifies this particular credit note and appears on the PDF of the credit note and its associated invoice.
     */
    declare public /*out*/ readonly number: pulumi.Output<string>;
    /**
     * String representing the object's type. Objects of the same type share the same value.
     */
    declare public /*out*/ readonly object: pulumi.Output<string>;
    /**
     * Amount that was credited outside of Stripe.
     */
    declare public readonly outOfBandAmount: pulumi.Output<number>;
    /**
     * The amount of the credit note that was refunded to the customer, credited to the customer's balance, credited outside of Stripe, or any combination thereof.
     */
    declare public /*out*/ readonly postPaymentAmount: pulumi.Output<number>;
    /**
     * The amount of the credit note by which the invoice's `amountRemaining` and `amountDue` were reduced.
     */
    declare public /*out*/ readonly prePaymentAmount: pulumi.Output<number>;
    /**
     * The pretax credit amounts (ex: discount, credit grants, etc) for all line items.
     */
    declare public /*out*/ readonly pretaxCreditAmounts: pulumi.Output<outputs.CreditNotePretaxCreditAmount[]>;
    /**
     * Reason for issuing this credit note, one of `duplicate`, `fraudulent`, `orderChange`, or `productUnsatisfactory`
     */
    declare public readonly reason: pulumi.Output<string>;
    /**
     * **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * The integer amount in cents (or local equivalent) representing the amount to refund. If set, a refund will be created for the charge associated with the invoice.
     */
    declare public readonly refundAmount: pulumi.Output<number | undefined>;
    /**
     * Refunds related to this credit note.
     */
    declare public readonly refunds: pulumi.Output<outputs.CreditNoteRefund[]>;
    /**
     * The details of the cost of shipping, including the ShippingRate applied to the invoice.
     */
    declare public readonly shippingCost: pulumi.Output<outputs.CreditNoteShippingCost>;
    /**
     * Status of this credit note, one of `issued` or `void`. Learn more about [voiding credit notes](https://docs.stripe.com/billing/invoices/credit-notes#voiding).
     */
    declare public /*out*/ readonly status: pulumi.Output<string>;
    /**
     * The integer amount in cents (or local equivalent) representing the amount of the credit note, excluding exclusive tax and invoice level discounts.
     */
    declare public /*out*/ readonly subtotal: pulumi.Output<number>;
    /**
     * The integer amount in cents (or local equivalent) representing the amount of the credit note, excluding all tax and invoice level discounts.
     */
    declare public /*out*/ readonly subtotalExcludingTax: pulumi.Output<number>;
    /**
     * The integer amount in cents (or local equivalent) representing the total amount of the credit note, including tax and all discount.
     */
    declare public /*out*/ readonly total: pulumi.Output<number>;
    /**
     * The integer amount in cents (or local equivalent) representing the total amount of the credit note, excluding tax, but including discounts.
     */
    declare public /*out*/ readonly totalExcludingTax: pulumi.Output<number>;
    /**
     * The aggregate tax information for all line items.
     */
    declare public /*out*/ readonly totalTaxes: pulumi.Output<outputs.CreditNoteTotalTax[]>;
    /**
     * Type of this credit note, one of `prePayment` or `postPayment`. A `prePayment` credit note means it was issued when the invoice was open. A `postPayment` credit note means it was issued when the invoice was paid.
     */
    declare public /*out*/ readonly type: pulumi.Output<string>;
    /**
     * The time that the credit note was voided.
     */
    declare public /*out*/ readonly voidedAt: pulumi.Output<number>;

    /**
     * Create a CreditNote resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: CreditNoteArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: CreditNoteArgs | CreditNoteState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as CreditNoteState | undefined;
            resourceInputs["amount"] = state?.amount;
            resourceInputs["amountShipping"] = state?.amountShipping;
            resourceInputs["created"] = state?.created;
            resourceInputs["creditAmount"] = state?.creditAmount;
            resourceInputs["currency"] = state?.currency;
            resourceInputs["customer"] = state?.customer;
            resourceInputs["customerBalanceTransaction"] = state?.customerBalanceTransaction;
            resourceInputs["discountAmount"] = state?.discountAmount;
            resourceInputs["discountAmounts"] = state?.discountAmounts;
            resourceInputs["effectiveAt"] = state?.effectiveAt;
            resourceInputs["emailType"] = state?.emailType;
            resourceInputs["invoice"] = state?.invoice;
            resourceInputs["livemode"] = state?.livemode;
            resourceInputs["memo"] = state?.memo;
            resourceInputs["metadata"] = state?.metadata;
            resourceInputs["number"] = state?.number;
            resourceInputs["object"] = state?.object;
            resourceInputs["outOfBandAmount"] = state?.outOfBandAmount;
            resourceInputs["postPaymentAmount"] = state?.postPaymentAmount;
            resourceInputs["prePaymentAmount"] = state?.prePaymentAmount;
            resourceInputs["pretaxCreditAmounts"] = state?.pretaxCreditAmounts;
            resourceInputs["reason"] = state?.reason;
            resourceInputs["refundAmount"] = state?.refundAmount;
            resourceInputs["refunds"] = state?.refunds;
            resourceInputs["shippingCost"] = state?.shippingCost;
            resourceInputs["status"] = state?.status;
            resourceInputs["subtotal"] = state?.subtotal;
            resourceInputs["subtotalExcludingTax"] = state?.subtotalExcludingTax;
            resourceInputs["total"] = state?.total;
            resourceInputs["totalExcludingTax"] = state?.totalExcludingTax;
            resourceInputs["totalTaxes"] = state?.totalTaxes;
            resourceInputs["type"] = state?.type;
            resourceInputs["voidedAt"] = state?.voidedAt;
        } else {
            const args = argsOrState as CreditNoteArgs | undefined;
            if (args?.invoice === undefined && !opts.urn) {
                throw new Error("Missing required property 'invoice'");
            }
            resourceInputs["amount"] = args?.amount;
            resourceInputs["creditAmount"] = args?.creditAmount ? pulumi.secret(args.creditAmount) : undefined;
            resourceInputs["effectiveAt"] = args?.effectiveAt;
            resourceInputs["emailType"] = args?.emailType ? pulumi.secret(args.emailType) : undefined;
            resourceInputs["invoice"] = args?.invoice;
            resourceInputs["memo"] = args?.memo;
            resourceInputs["metadata"] = args?.metadata;
            resourceInputs["outOfBandAmount"] = args?.outOfBandAmount;
            resourceInputs["reason"] = args?.reason;
            resourceInputs["refundAmount"] = args?.refundAmount ? pulumi.secret(args.refundAmount) : undefined;
            resourceInputs["refunds"] = args?.refunds;
            resourceInputs["shippingCost"] = args?.shippingCost;
            resourceInputs["amountShipping"] = undefined /*out*/;
            resourceInputs["created"] = undefined /*out*/;
            resourceInputs["currency"] = undefined /*out*/;
            resourceInputs["customer"] = undefined /*out*/;
            resourceInputs["customerBalanceTransaction"] = undefined /*out*/;
            resourceInputs["discountAmount"] = undefined /*out*/;
            resourceInputs["discountAmounts"] = undefined /*out*/;
            resourceInputs["livemode"] = undefined /*out*/;
            resourceInputs["number"] = undefined /*out*/;
            resourceInputs["object"] = undefined /*out*/;
            resourceInputs["postPaymentAmount"] = undefined /*out*/;
            resourceInputs["prePaymentAmount"] = undefined /*out*/;
            resourceInputs["pretaxCreditAmounts"] = undefined /*out*/;
            resourceInputs["status"] = undefined /*out*/;
            resourceInputs["subtotal"] = undefined /*out*/;
            resourceInputs["subtotalExcludingTax"] = undefined /*out*/;
            resourceInputs["total"] = undefined /*out*/;
            resourceInputs["totalExcludingTax"] = undefined /*out*/;
            resourceInputs["totalTaxes"] = undefined /*out*/;
            resourceInputs["type"] = undefined /*out*/;
            resourceInputs["voidedAt"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["creditAmount", "emailType", "refundAmount"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(CreditNote.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering CreditNote resources.
 */
export interface CreditNoteState {
    /**
     * The integer amount in cents (or local equivalent) representing the total amount of the credit note, including tax.
     */
    amount?: pulumi.Input<number | undefined>;
    /**
     * This is the sum of all the shipping amounts.
     */
    amountShipping?: pulumi.Input<number | undefined>;
    /**
     * Time at which the object was created. Measured in seconds since the Unix epoch.
     */
    created?: pulumi.Input<number | undefined>;
    /**
     * **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * The integer amount in cents (or local equivalent) representing the amount to credit the customer's balance, which will be automatically applied to their next invoice.
     */
    creditAmount?: pulumi.Input<number | undefined>;
    /**
     * Three-letter [ISO currency code](https://www.iso.org/iso-4217-currency-codes.html), in lowercase. Must be a [supported currency](https://stripe.com/docs/currencies).
     */
    currency?: pulumi.Input<string | undefined>;
    /**
     * ID of the customer.
     */
    customer?: pulumi.Input<string | undefined>;
    /**
     * Customer balance transaction related to this credit note.
     */
    customerBalanceTransaction?: pulumi.Input<string | undefined>;
    /**
     * The integer amount in cents (or local equivalent) representing the total amount of discount that was credited.
     */
    discountAmount?: pulumi.Input<number | undefined>;
    /**
     * The aggregate amounts calculated per discount for all line items.
     */
    discountAmounts?: pulumi.Input<pulumi.Input<inputs.CreditNoteDiscountAmount>[] | undefined>;
    /**
     * The date when this credit note is in effect. Same as `created` unless overwritten. When defined, this value replaces the system-generated 'Date of issue' printed on the credit note PDF.
     */
    effectiveAt?: pulumi.Input<number | undefined>;
    /**
     * **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * Type of email to send to the customer, one of `creditNote` or `none` and the default is `creditNote`.
     */
    emailType?: pulumi.Input<string | undefined>;
    /**
     * ID of the invoice.
     */
    invoice?: pulumi.Input<string | undefined>;
    /**
     * If the object exists in live mode, the value is `true`. If the object exists in test mode, the value is `false`.
     */
    livemode?: pulumi.Input<boolean | undefined>;
    /**
     * Customer-facing text that appears on the credit note PDF.
     */
    memo?: pulumi.Input<string | undefined>;
    /**
     * Set of [key-value pairs](https://docs.stripe.com/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format.
     */
    metadata?: pulumi.Input<{[key: string]: pulumi.Input<string>} | undefined>;
    /**
     * A unique number that identifies this particular credit note and appears on the PDF of the credit note and its associated invoice.
     */
    number?: pulumi.Input<string | undefined>;
    /**
     * String representing the object's type. Objects of the same type share the same value.
     */
    object?: pulumi.Input<string | undefined>;
    /**
     * Amount that was credited outside of Stripe.
     */
    outOfBandAmount?: pulumi.Input<number | undefined>;
    /**
     * The amount of the credit note that was refunded to the customer, credited to the customer's balance, credited outside of Stripe, or any combination thereof.
     */
    postPaymentAmount?: pulumi.Input<number | undefined>;
    /**
     * The amount of the credit note by which the invoice's `amountRemaining` and `amountDue` were reduced.
     */
    prePaymentAmount?: pulumi.Input<number | undefined>;
    /**
     * The pretax credit amounts (ex: discount, credit grants, etc) for all line items.
     */
    pretaxCreditAmounts?: pulumi.Input<pulumi.Input<inputs.CreditNotePretaxCreditAmount>[] | undefined>;
    /**
     * Reason for issuing this credit note, one of `duplicate`, `fraudulent`, `orderChange`, or `productUnsatisfactory`
     */
    reason?: pulumi.Input<string | undefined>;
    /**
     * **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * The integer amount in cents (or local equivalent) representing the amount to refund. If set, a refund will be created for the charge associated with the invoice.
     */
    refundAmount?: pulumi.Input<number | undefined>;
    /**
     * Refunds related to this credit note.
     */
    refunds?: pulumi.Input<pulumi.Input<inputs.CreditNoteRefund>[] | undefined>;
    /**
     * The details of the cost of shipping, including the ShippingRate applied to the invoice.
     */
    shippingCost?: pulumi.Input<inputs.CreditNoteShippingCost | undefined>;
    /**
     * Status of this credit note, one of `issued` or `void`. Learn more about [voiding credit notes](https://docs.stripe.com/billing/invoices/credit-notes#voiding).
     */
    status?: pulumi.Input<string | undefined>;
    /**
     * The integer amount in cents (or local equivalent) representing the amount of the credit note, excluding exclusive tax and invoice level discounts.
     */
    subtotal?: pulumi.Input<number | undefined>;
    /**
     * The integer amount in cents (or local equivalent) representing the amount of the credit note, excluding all tax and invoice level discounts.
     */
    subtotalExcludingTax?: pulumi.Input<number | undefined>;
    /**
     * The integer amount in cents (or local equivalent) representing the total amount of the credit note, including tax and all discount.
     */
    total?: pulumi.Input<number | undefined>;
    /**
     * The integer amount in cents (or local equivalent) representing the total amount of the credit note, excluding tax, but including discounts.
     */
    totalExcludingTax?: pulumi.Input<number | undefined>;
    /**
     * The aggregate tax information for all line items.
     */
    totalTaxes?: pulumi.Input<pulumi.Input<inputs.CreditNoteTotalTax>[] | undefined>;
    /**
     * Type of this credit note, one of `prePayment` or `postPayment`. A `prePayment` credit note means it was issued when the invoice was open. A `postPayment` credit note means it was issued when the invoice was paid.
     */
    type?: pulumi.Input<string | undefined>;
    /**
     * The time that the credit note was voided.
     */
    voidedAt?: pulumi.Input<number | undefined>;
}

/**
 * The set of arguments for constructing a CreditNote resource.
 */
export interface CreditNoteArgs {
    /**
     * The integer amount in cents (or local equivalent) representing the total amount of the credit note, including tax.
     */
    amount?: pulumi.Input<number | undefined>;
    /**
     * **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * The integer amount in cents (or local equivalent) representing the amount to credit the customer's balance, which will be automatically applied to their next invoice.
     */
    creditAmount?: pulumi.Input<number | undefined>;
    /**
     * The date when this credit note is in effect. Same as `created` unless overwritten. When defined, this value replaces the system-generated 'Date of issue' printed on the credit note PDF.
     */
    effectiveAt?: pulumi.Input<number | undefined>;
    /**
     * **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * Type of email to send to the customer, one of `creditNote` or `none` and the default is `creditNote`.
     */
    emailType?: pulumi.Input<string | undefined>;
    /**
     * ID of the invoice.
     */
    invoice: pulumi.Input<string>;
    /**
     * Customer-facing text that appears on the credit note PDF.
     */
    memo?: pulumi.Input<string | undefined>;
    /**
     * Set of [key-value pairs](https://docs.stripe.com/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format.
     */
    metadata?: pulumi.Input<{[key: string]: pulumi.Input<string>} | undefined>;
    /**
     * Amount that was credited outside of Stripe.
     */
    outOfBandAmount?: pulumi.Input<number | undefined>;
    /**
     * Reason for issuing this credit note, one of `duplicate`, `fraudulent`, `orderChange`, or `productUnsatisfactory`
     */
    reason?: pulumi.Input<string | undefined>;
    /**
     * **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * The integer amount in cents (or local equivalent) representing the amount to refund. If set, a refund will be created for the charge associated with the invoice.
     */
    refundAmount?: pulumi.Input<number | undefined>;
    /**
     * Refunds related to this credit note.
     */
    refunds?: pulumi.Input<pulumi.Input<inputs.CreditNoteRefund>[] | undefined>;
    /**
     * The details of the cost of shipping, including the ShippingRate applied to the invoice.
     */
    shippingCost?: pulumi.Input<inputs.CreditNoteShippingCost | undefined>;
}
