// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * This object represents a customer of your business. Use it to [create recurring charges](https://stripe.com/docs/invoicing/customer), [save payment](https://stripe.com/docs/payments/save-during-payment) and contact information, and track payments that belong to the same customer.
 */
export class Customer extends pulumi.CustomResource {
    /**
     * Get an existing Customer resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: CustomerState, opts?: pulumi.CustomResourceOptions): Customer {
        return new Customer(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'stripe:index/customer:Customer';

    /**
     * Returns true if the given object is an instance of Customer.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Customer {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Customer.__pulumiType;
    }

    declare public readonly address: pulumi.Output<outputs.CustomerAddress | undefined>;
    /**
     * An integer amount in cents (or local equivalent) that represents the customer's current balance, which affect the customer's future invoices. A negative amount represents a credit that decreases the amount due on an invoice; a positive amount increases the amount due on an invoice.
     */
    declare public readonly balance: pulumi.Output<number>;
    declare public readonly businessName: pulumi.Output<string>;
    /**
     * Balance information and default balance settings for this customer.
     */
    declare public readonly cashBalance: pulumi.Output<outputs.CustomerCashBalance | undefined>;
    /**
     * Three-letter [ISO code for the currency](https://stripe.com/docs/currencies) the customer can be charged in for recurring billing purposes.
     */
    declare public /*out*/ readonly currency: pulumi.Output<string>;
    declare public /*out*/ readonly customerAccount: pulumi.Output<string>;
    /**
     * Tracks the most recent state change on any invoice belonging to the customer. Paying an invoice or marking it uncollectible via the API will set this field to false. An automatic payment failure or passing the `invoice.due_date` will set this field to `true`. If an invoice becomes uncollectible by [dunning](https://stripe.com/docs/billing/automatic-collection), `delinquent` doesn't reset to `false`. If you care whether the customer has paid their most recent subscription invoice, use `subscription.status` instead. Paying or marking uncollectible any customer invoice regardless of whether it is the latest invoice for a subscription will always set this field to `false`.
     */
    declare public /*out*/ readonly delinquent: pulumi.Output<boolean>;
    /**
     * An arbitrary string that you can attach to a customer object. It is displayed alongside the customer in the dashboard.
     */
    declare public readonly description: pulumi.Output<string>;
    /**
     * Customer's email address. It's displayed alongside the customer in your dashboard and can be useful for searching and tracking. This may be up to *512 characters*.
     */
    declare public readonly email: pulumi.Output<string>;
    declare public readonly individualName: pulumi.Output<string>;
    /**
     * The prefix for the customer used to generate unique invoice numbers. Must be 3–12 uppercase letters or numbers.
     */
    declare public readonly invoicePrefix: pulumi.Output<string>;
    /**
     * Default invoice settings for this customer.
     */
    declare public readonly invoiceSettings: pulumi.Output<outputs.CustomerInvoiceSettings | undefined>;
    declare public readonly metadata: pulumi.Output<{[key: string]: string}>;
    /**
     * The customer's full name or business name.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * The sequence to be used on the customer's next invoice. Defaults to 1.
     */
    declare public readonly nextInvoiceSequence: pulumi.Output<number>;
    declare public readonly paymentMethod: pulumi.Output<string | undefined>;
    /**
     * The customer's phone number.
     */
    declare public readonly phone: pulumi.Output<string>;
    /**
     * Customer's preferred languages, ordered by preference.
     */
    declare public readonly preferredLocales: pulumi.Output<string[] | undefined>;
    declare public readonly shipping: pulumi.Output<outputs.CustomerShipping | undefined>;
    /**
     * Tax details about the customer.
     */
    declare public readonly tax: pulumi.Output<outputs.CustomerTax | undefined>;
    /**
     * The customer's tax exemption. One of `none`, `exempt`, or `reverse`.
     */
    declare public readonly taxExempt: pulumi.Output<string>;
    /**
     * The customer's tax IDs.
     */
    declare public readonly taxIdDatas: pulumi.Output<outputs.CustomerTaxIdData[] | undefined>;
    /**
     * ID of the test clock to attach to the customer.
     */
    declare public readonly testClock: pulumi.Output<string>;

    /**
     * Create a Customer resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: CustomerArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: CustomerArgs | CustomerState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as CustomerState | undefined;
            resourceInputs["address"] = state?.address;
            resourceInputs["balance"] = state?.balance;
            resourceInputs["businessName"] = state?.businessName;
            resourceInputs["cashBalance"] = state?.cashBalance;
            resourceInputs["currency"] = state?.currency;
            resourceInputs["customerAccount"] = state?.customerAccount;
            resourceInputs["delinquent"] = state?.delinquent;
            resourceInputs["description"] = state?.description;
            resourceInputs["email"] = state?.email;
            resourceInputs["individualName"] = state?.individualName;
            resourceInputs["invoicePrefix"] = state?.invoicePrefix;
            resourceInputs["invoiceSettings"] = state?.invoiceSettings;
            resourceInputs["metadata"] = state?.metadata;
            resourceInputs["name"] = state?.name;
            resourceInputs["nextInvoiceSequence"] = state?.nextInvoiceSequence;
            resourceInputs["paymentMethod"] = state?.paymentMethod;
            resourceInputs["phone"] = state?.phone;
            resourceInputs["preferredLocales"] = state?.preferredLocales;
            resourceInputs["shipping"] = state?.shipping;
            resourceInputs["tax"] = state?.tax;
            resourceInputs["taxExempt"] = state?.taxExempt;
            resourceInputs["taxIdDatas"] = state?.taxIdDatas;
            resourceInputs["testClock"] = state?.testClock;
        } else {
            const args = argsOrState as CustomerArgs | undefined;
            resourceInputs["address"] = args?.address;
            resourceInputs["balance"] = args?.balance;
            resourceInputs["businessName"] = args?.businessName;
            resourceInputs["cashBalance"] = args?.cashBalance;
            resourceInputs["description"] = args?.description;
            resourceInputs["email"] = args?.email;
            resourceInputs["individualName"] = args?.individualName;
            resourceInputs["invoicePrefix"] = args?.invoicePrefix;
            resourceInputs["invoiceSettings"] = args?.invoiceSettings;
            resourceInputs["metadata"] = args?.metadata;
            resourceInputs["name"] = args?.name;
            resourceInputs["nextInvoiceSequence"] = args?.nextInvoiceSequence;
            resourceInputs["paymentMethod"] = args?.paymentMethod;
            resourceInputs["phone"] = args?.phone;
            resourceInputs["preferredLocales"] = args?.preferredLocales;
            resourceInputs["shipping"] = args?.shipping;
            resourceInputs["tax"] = args?.tax;
            resourceInputs["taxExempt"] = args?.taxExempt;
            resourceInputs["taxIdDatas"] = args?.taxIdDatas;
            resourceInputs["testClock"] = args?.testClock;
            resourceInputs["currency"] = undefined /*out*/;
            resourceInputs["customerAccount"] = undefined /*out*/;
            resourceInputs["delinquent"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Customer.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering Customer resources.
 */
export interface CustomerState {
    address?: pulumi.Input<inputs.CustomerAddress | undefined>;
    /**
     * An integer amount in cents (or local equivalent) that represents the customer's current balance, which affect the customer's future invoices. A negative amount represents a credit that decreases the amount due on an invoice; a positive amount increases the amount due on an invoice.
     */
    balance?: pulumi.Input<number | undefined>;
    businessName?: pulumi.Input<string | undefined>;
    /**
     * Balance information and default balance settings for this customer.
     */
    cashBalance?: pulumi.Input<inputs.CustomerCashBalance | undefined>;
    /**
     * Three-letter [ISO code for the currency](https://stripe.com/docs/currencies) the customer can be charged in for recurring billing purposes.
     */
    currency?: pulumi.Input<string | undefined>;
    customerAccount?: pulumi.Input<string | undefined>;
    /**
     * Tracks the most recent state change on any invoice belonging to the customer. Paying an invoice or marking it uncollectible via the API will set this field to false. An automatic payment failure or passing the `invoice.due_date` will set this field to `true`. If an invoice becomes uncollectible by [dunning](https://stripe.com/docs/billing/automatic-collection), `delinquent` doesn't reset to `false`. If you care whether the customer has paid their most recent subscription invoice, use `subscription.status` instead. Paying or marking uncollectible any customer invoice regardless of whether it is the latest invoice for a subscription will always set this field to `false`.
     */
    delinquent?: pulumi.Input<boolean | undefined>;
    /**
     * An arbitrary string that you can attach to a customer object. It is displayed alongside the customer in the dashboard.
     */
    description?: pulumi.Input<string | undefined>;
    /**
     * Customer's email address. It's displayed alongside the customer in your dashboard and can be useful for searching and tracking. This may be up to *512 characters*.
     */
    email?: pulumi.Input<string | undefined>;
    individualName?: pulumi.Input<string | undefined>;
    /**
     * The prefix for the customer used to generate unique invoice numbers. Must be 3–12 uppercase letters or numbers.
     */
    invoicePrefix?: pulumi.Input<string | undefined>;
    /**
     * Default invoice settings for this customer.
     */
    invoiceSettings?: pulumi.Input<inputs.CustomerInvoiceSettings | undefined>;
    metadata?: pulumi.Input<{[key: string]: pulumi.Input<string>} | undefined>;
    /**
     * The customer's full name or business name.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * The sequence to be used on the customer's next invoice. Defaults to 1.
     */
    nextInvoiceSequence?: pulumi.Input<number | undefined>;
    paymentMethod?: pulumi.Input<string | undefined>;
    /**
     * The customer's phone number.
     */
    phone?: pulumi.Input<string | undefined>;
    /**
     * Customer's preferred languages, ordered by preference.
     */
    preferredLocales?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    shipping?: pulumi.Input<inputs.CustomerShipping | undefined>;
    /**
     * Tax details about the customer.
     */
    tax?: pulumi.Input<inputs.CustomerTax | undefined>;
    /**
     * The customer's tax exemption. One of `none`, `exempt`, or `reverse`.
     */
    taxExempt?: pulumi.Input<string | undefined>;
    /**
     * The customer's tax IDs.
     */
    taxIdDatas?: pulumi.Input<pulumi.Input<inputs.CustomerTaxIdData>[] | undefined>;
    /**
     * ID of the test clock to attach to the customer.
     */
    testClock?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a Customer resource.
 */
export interface CustomerArgs {
    address?: pulumi.Input<inputs.CustomerAddress | undefined>;
    /**
     * An integer amount in cents (or local equivalent) that represents the customer's current balance, which affect the customer's future invoices. A negative amount represents a credit that decreases the amount due on an invoice; a positive amount increases the amount due on an invoice.
     */
    balance?: pulumi.Input<number | undefined>;
    businessName?: pulumi.Input<string | undefined>;
    /**
     * Balance information and default balance settings for this customer.
     */
    cashBalance?: pulumi.Input<inputs.CustomerCashBalance | undefined>;
    /**
     * An arbitrary string that you can attach to a customer object. It is displayed alongside the customer in the dashboard.
     */
    description?: pulumi.Input<string | undefined>;
    /**
     * Customer's email address. It's displayed alongside the customer in your dashboard and can be useful for searching and tracking. This may be up to *512 characters*.
     */
    email?: pulumi.Input<string | undefined>;
    individualName?: pulumi.Input<string | undefined>;
    /**
     * The prefix for the customer used to generate unique invoice numbers. Must be 3–12 uppercase letters or numbers.
     */
    invoicePrefix?: pulumi.Input<string | undefined>;
    /**
     * Default invoice settings for this customer.
     */
    invoiceSettings?: pulumi.Input<inputs.CustomerInvoiceSettings | undefined>;
    metadata?: pulumi.Input<{[key: string]: pulumi.Input<string>} | undefined>;
    /**
     * The customer's full name or business name.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * The sequence to be used on the customer's next invoice. Defaults to 1.
     */
    nextInvoiceSequence?: pulumi.Input<number | undefined>;
    paymentMethod?: pulumi.Input<string | undefined>;
    /**
     * The customer's phone number.
     */
    phone?: pulumi.Input<string | undefined>;
    /**
     * Customer's preferred languages, ordered by preference.
     */
    preferredLocales?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    shipping?: pulumi.Input<inputs.CustomerShipping | undefined>;
    /**
     * Tax details about the customer.
     */
    tax?: pulumi.Input<inputs.CustomerTax | undefined>;
    /**
     * The customer's tax exemption. One of `none`, `exempt`, or `reverse`.
     */
    taxExempt?: pulumi.Input<string | undefined>;
    /**
     * The customer's tax IDs.
     */
    taxIdDatas?: pulumi.Input<pulumi.Input<inputs.CustomerTaxIdData>[] | undefined>;
    /**
     * ID of the test clock to attach to the customer.
     */
    testClock?: pulumi.Input<string | undefined>;
}
