// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * This object represents files hosted on Stripe's servers. You can upload
 * files with the [create file](https://api.stripe.com#create_file) request
 * (for example, when uploading dispute evidence). Stripe also
 * creates files independently (for example, the results of a Sigma scheduled
 * query).
 *
 * Related guide: [File upload guide](https://docs.stripe.com/file-upload)
 */
export class File extends pulumi.CustomResource {
    /**
     * Get an existing File resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: FileState, opts?: pulumi.CustomResourceOptions): File {
        return new File(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'stripe:index/file:File';

    /**
     * Returns true if the given object is an instance of File.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is File {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === File.__pulumiType;
    }

    /**
     * Time at which the object was created. Measured in seconds since the Unix epoch.
     */
    declare public /*out*/ readonly created: pulumi.Output<number>;
    /**
     * The file expires and isn't available at this time in epoch seconds.
     */
    declare public /*out*/ readonly expiresAt: pulumi.Output<number>;
    /**
     * **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * A file to upload. Make sure that the specifications follow RFC 2388, which defines file transfers for the `multipart/form-data` protocol.
     */
    declare public readonly file: pulumi.Output<string>;
    /**
     * **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * Optional parameters that automatically create a [file link](https://api.stripe.com#file_links) for the newly created file.
     */
    declare public readonly fileLinkData: pulumi.Output<outputs.FileFileLinkData | undefined>;
    /**
     * The suitable name for saving the file to a filesystem.
     */
    declare public /*out*/ readonly filename: pulumi.Output<string>;
    /**
     * String representing the object's type. Objects of the same type share the same value.
     */
    declare public /*out*/ readonly object: pulumi.Output<string>;
    /**
     * The [purpose](https://docs.stripe.com/file-upload#uploading-a-file) of the uploaded file.
     */
    declare public readonly purpose: pulumi.Output<string>;
    /**
     * The size of the file object in bytes.
     */
    declare public /*out*/ readonly size: pulumi.Output<number>;
    /**
     * A suitable title for the document.
     */
    declare public /*out*/ readonly title: pulumi.Output<string>;
    /**
     * The returned file type (for example, `csv`, `pdf`, `jpg`, or `png`).
     */
    declare public /*out*/ readonly type: pulumi.Output<string>;
    /**
     * Use your live secret API key to download the file from this URL.
     */
    declare public /*out*/ readonly url: pulumi.Output<string>;

    /**
     * Create a File resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: FileArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: FileArgs | FileState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as FileState | undefined;
            resourceInputs["created"] = state?.created;
            resourceInputs["expiresAt"] = state?.expiresAt;
            resourceInputs["file"] = state?.file;
            resourceInputs["fileLinkData"] = state?.fileLinkData;
            resourceInputs["filename"] = state?.filename;
            resourceInputs["object"] = state?.object;
            resourceInputs["purpose"] = state?.purpose;
            resourceInputs["size"] = state?.size;
            resourceInputs["title"] = state?.title;
            resourceInputs["type"] = state?.type;
            resourceInputs["url"] = state?.url;
        } else {
            const args = argsOrState as FileArgs | undefined;
            if (args?.file === undefined && !opts.urn) {
                throw new Error("Missing required property 'file'");
            }
            if (args?.purpose === undefined && !opts.urn) {
                throw new Error("Missing required property 'purpose'");
            }
            resourceInputs["file"] = args?.file ? pulumi.secret(args.file) : undefined;
            resourceInputs["fileLinkData"] = args?.fileLinkData ? pulumi.secret(args.fileLinkData) : undefined;
            resourceInputs["purpose"] = args?.purpose;
            resourceInputs["created"] = undefined /*out*/;
            resourceInputs["expiresAt"] = undefined /*out*/;
            resourceInputs["filename"] = undefined /*out*/;
            resourceInputs["object"] = undefined /*out*/;
            resourceInputs["size"] = undefined /*out*/;
            resourceInputs["title"] = undefined /*out*/;
            resourceInputs["type"] = undefined /*out*/;
            resourceInputs["url"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["file", "fileLinkData"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(File.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering File resources.
 */
export interface FileState {
    /**
     * Time at which the object was created. Measured in seconds since the Unix epoch.
     */
    created?: pulumi.Input<number | undefined>;
    /**
     * The file expires and isn't available at this time in epoch seconds.
     */
    expiresAt?: pulumi.Input<number | undefined>;
    /**
     * **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * A file to upload. Make sure that the specifications follow RFC 2388, which defines file transfers for the `multipart/form-data` protocol.
     */
    file?: pulumi.Input<string | undefined>;
    /**
     * **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * Optional parameters that automatically create a [file link](https://api.stripe.com#file_links) for the newly created file.
     */
    fileLinkData?: pulumi.Input<inputs.FileFileLinkData | undefined>;
    /**
     * The suitable name for saving the file to a filesystem.
     */
    filename?: pulumi.Input<string | undefined>;
    /**
     * String representing the object's type. Objects of the same type share the same value.
     */
    object?: pulumi.Input<string | undefined>;
    /**
     * The [purpose](https://docs.stripe.com/file-upload#uploading-a-file) of the uploaded file.
     */
    purpose?: pulumi.Input<string | undefined>;
    /**
     * The size of the file object in bytes.
     */
    size?: pulumi.Input<number | undefined>;
    /**
     * A suitable title for the document.
     */
    title?: pulumi.Input<string | undefined>;
    /**
     * The returned file type (for example, `csv`, `pdf`, `jpg`, or `png`).
     */
    type?: pulumi.Input<string | undefined>;
    /**
     * Use your live secret API key to download the file from this URL.
     */
    url?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a File resource.
 */
export interface FileArgs {
    /**
     * **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * A file to upload. Make sure that the specifications follow RFC 2388, which defines file transfers for the `multipart/form-data` protocol.
     */
    file: pulumi.Input<string>;
    /**
     * **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * Optional parameters that automatically create a [file link](https://api.stripe.com#file_links) for the newly created file.
     */
    fileLinkData?: pulumi.Input<inputs.FileFileLinkData | undefined>;
    /**
     * The [purpose](https://docs.stripe.com/file-upload#uploading-a-file) of the uploaded file.
     */
    purpose: pulumi.Input<string>;
}
