// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * To share the contents of a `File` object with non-Stripe users, you can
 * create a `FileLink`. `FileLink`s contain a URL that you can use to
 * retrieve the contents of the file without authentication.
 */
export class FileLink extends pulumi.CustomResource {
    /**
     * Get an existing FileLink resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: FileLinkState, opts?: pulumi.CustomResourceOptions): FileLink {
        return new FileLink(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'stripe:index/fileLink:FileLink';

    /**
     * Returns true if the given object is an instance of FileLink.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is FileLink {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === FileLink.__pulumiType;
    }

    /**
     * Time at which the object was created. Measured in seconds since the Unix epoch.
     */
    declare public /*out*/ readonly created: pulumi.Output<number>;
    /**
     * Returns if the link is already expired.
     */
    declare public /*out*/ readonly expired: pulumi.Output<boolean>;
    /**
     * Time that the link expires.
     */
    declare public readonly expiresAt: pulumi.Output<number>;
    /**
     * The file object this link points to.
     */
    declare public readonly file: pulumi.Output<string>;
    /**
     * If the object exists in live mode, the value is `true`. If the object exists in test mode, the value is `false`.
     */
    declare public /*out*/ readonly livemode: pulumi.Output<boolean>;
    /**
     * Set of [key-value pairs](https://docs.stripe.com/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format.
     */
    declare public readonly metadata: pulumi.Output<{[key: string]: string}>;
    /**
     * String representing the object's type. Objects of the same type share the same value.
     */
    declare public /*out*/ readonly object: pulumi.Output<string>;
    /**
     * The publicly accessible URL to download the file.
     */
    declare public /*out*/ readonly url: pulumi.Output<string>;

    /**
     * Create a FileLink resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: FileLinkArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: FileLinkArgs | FileLinkState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as FileLinkState | undefined;
            resourceInputs["created"] = state?.created;
            resourceInputs["expired"] = state?.expired;
            resourceInputs["expiresAt"] = state?.expiresAt;
            resourceInputs["file"] = state?.file;
            resourceInputs["livemode"] = state?.livemode;
            resourceInputs["metadata"] = state?.metadata;
            resourceInputs["object"] = state?.object;
            resourceInputs["url"] = state?.url;
        } else {
            const args = argsOrState as FileLinkArgs | undefined;
            if (args?.file === undefined && !opts.urn) {
                throw new Error("Missing required property 'file'");
            }
            resourceInputs["expiresAt"] = args?.expiresAt;
            resourceInputs["file"] = args?.file;
            resourceInputs["metadata"] = args?.metadata;
            resourceInputs["created"] = undefined /*out*/;
            resourceInputs["expired"] = undefined /*out*/;
            resourceInputs["livemode"] = undefined /*out*/;
            resourceInputs["object"] = undefined /*out*/;
            resourceInputs["url"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(FileLink.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering FileLink resources.
 */
export interface FileLinkState {
    /**
     * Time at which the object was created. Measured in seconds since the Unix epoch.
     */
    created?: pulumi.Input<number | undefined>;
    /**
     * Returns if the link is already expired.
     */
    expired?: pulumi.Input<boolean | undefined>;
    /**
     * Time that the link expires.
     */
    expiresAt?: pulumi.Input<number | undefined>;
    /**
     * The file object this link points to.
     */
    file?: pulumi.Input<string | undefined>;
    /**
     * If the object exists in live mode, the value is `true`. If the object exists in test mode, the value is `false`.
     */
    livemode?: pulumi.Input<boolean | undefined>;
    /**
     * Set of [key-value pairs](https://docs.stripe.com/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format.
     */
    metadata?: pulumi.Input<{[key: string]: pulumi.Input<string>} | undefined>;
    /**
     * String representing the object's type. Objects of the same type share the same value.
     */
    object?: pulumi.Input<string | undefined>;
    /**
     * The publicly accessible URL to download the file.
     */
    url?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a FileLink resource.
 */
export interface FileLinkArgs {
    /**
     * Time that the link expires.
     */
    expiresAt?: pulumi.Input<number | undefined>;
    /**
     * The file object this link points to.
     */
    file: pulumi.Input<string>;
    /**
     * Set of [key-value pairs](https://docs.stripe.com/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format.
     */
    metadata?: pulumi.Input<{[key: string]: pulumi.Input<string>} | undefined>;
}
