// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Use this data source to retrieve information about an existing Stripe Billing Meter.
 */
export function getBillingMeter(args?: GetBillingMeterArgs, opts?: pulumi.InvokeOptions): Promise<GetBillingMeterResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("stripe:index/getBillingMeter:getBillingMeter", {
        "eventName": args.eventName,
        "id": args.id,
    }, opts);
}

/**
 * A collection of arguments for invoking getBillingMeter.
 */
export interface GetBillingMeterArgs {
    /**
     * Event name for the meter
     */
    eventName?: string;
    /**
     * Unique identifier for the object
     */
    id?: string;
}

/**
 * A collection of values returned by getBillingMeter.
 */
export interface GetBillingMeterResult {
    /**
     * Display name of the meter
     */
    readonly displayName: string;
    /**
     * Event name for the meter
     */
    readonly eventName: string;
    /**
     * Unique identifier for the object
     */
    readonly id: string;
    /**
     * Status of the meter
     */
    readonly status: string;
}
/**
 * Use this data source to retrieve information about an existing Stripe Billing Meter.
 */
export function getBillingMeterOutput(args?: GetBillingMeterOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetBillingMeterResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("stripe:index/getBillingMeter:getBillingMeter", {
        "eventName": args.eventName,
        "id": args.id,
    }, opts);
}

/**
 * A collection of arguments for invoking getBillingMeter.
 */
export interface GetBillingMeterOutputArgs {
    /**
     * Event name for the meter
     */
    eventName?: pulumi.Input<string | undefined>;
    /**
     * Unique identifier for the object
     */
    id?: pulumi.Input<string | undefined>;
}
