// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

// Export members:
export { BillingMeterArgs, BillingMeterState } from "./billingMeter";
export type BillingMeter = import("./billingMeter").BillingMeter;
export const BillingMeter: typeof import("./billingMeter").BillingMeter = null as any;
utilities.lazyLoad(exports, ["BillingMeter"], () => require("./billingMeter"));

export { CouponArgs, CouponState } from "./coupon";
export type Coupon = import("./coupon").Coupon;
export const Coupon: typeof import("./coupon").Coupon = null as any;
utilities.lazyLoad(exports, ["Coupon"], () => require("./coupon"));

export { CustomerArgs, CustomerState } from "./customer";
export type Customer = import("./customer").Customer;
export const Customer: typeof import("./customer").Customer = null as any;
utilities.lazyLoad(exports, ["Customer"], () => require("./customer"));

export { EntitlementsFeatureArgs, EntitlementsFeatureState } from "./entitlementsFeature";
export type EntitlementsFeature = import("./entitlementsFeature").EntitlementsFeature;
export const EntitlementsFeature: typeof import("./entitlementsFeature").EntitlementsFeature = null as any;
utilities.lazyLoad(exports, ["EntitlementsFeature"], () => require("./entitlementsFeature"));

export { GetBillingMeterArgs, GetBillingMeterResult, GetBillingMeterOutputArgs } from "./getBillingMeter";
export const getBillingMeter: typeof import("./getBillingMeter").getBillingMeter = null as any;
export const getBillingMeterOutput: typeof import("./getBillingMeter").getBillingMeterOutput = null as any;
utilities.lazyLoad(exports, ["getBillingMeter","getBillingMeterOutput"], () => require("./getBillingMeter"));

export { PriceArgs, PriceState } from "./price";
export type Price = import("./price").Price;
export const Price: typeof import("./price").Price = null as any;
utilities.lazyLoad(exports, ["Price"], () => require("./price"));

export { ProductArgs, ProductState } from "./product";
export type Product = import("./product").Product;
export const Product: typeof import("./product").Product = null as any;
utilities.lazyLoad(exports, ["Product"], () => require("./product"));

export { PromotionCodeArgs, PromotionCodeState } from "./promotionCode";
export type PromotionCode = import("./promotionCode").PromotionCode;
export const PromotionCode: typeof import("./promotionCode").PromotionCode = null as any;
utilities.lazyLoad(exports, ["PromotionCode"], () => require("./promotionCode"));

export * from "./provider";
import { Provider } from "./provider";

export { ShippingRateArgs, ShippingRateState } from "./shippingRate";
export type ShippingRate = import("./shippingRate").ShippingRate;
export const ShippingRate: typeof import("./shippingRate").ShippingRate = null as any;
utilities.lazyLoad(exports, ["ShippingRate"], () => require("./shippingRate"));

export { TaxRateArgs, TaxRateState } from "./taxRate";
export type TaxRate = import("./taxRate").TaxRate;
export const TaxRate: typeof import("./taxRate").TaxRate = null as any;
utilities.lazyLoad(exports, ["TaxRate"], () => require("./taxRate"));

export { V2BillingLicenseFeeArgs, V2BillingLicenseFeeState } from "./v2billingLicenseFee";
export type V2BillingLicenseFee = import("./v2billingLicenseFee").V2BillingLicenseFee;
export const V2BillingLicenseFee: typeof import("./v2billingLicenseFee").V2BillingLicenseFee = null as any;
utilities.lazyLoad(exports, ["V2BillingLicenseFee"], () => require("./v2billingLicenseFee"));

export { V2BillingLicensedItemArgs, V2BillingLicensedItemState } from "./v2billingLicensedItem";
export type V2BillingLicensedItem = import("./v2billingLicensedItem").V2BillingLicensedItem;
export const V2BillingLicensedItem: typeof import("./v2billingLicensedItem").V2BillingLicensedItem = null as any;
utilities.lazyLoad(exports, ["V2BillingLicensedItem"], () => require("./v2billingLicensedItem"));

export { V2BillingMeteredItemArgs, V2BillingMeteredItemState } from "./v2billingMeteredItem";
export type V2BillingMeteredItem = import("./v2billingMeteredItem").V2BillingMeteredItem;
export const V2BillingMeteredItem: typeof import("./v2billingMeteredItem").V2BillingMeteredItem = null as any;
utilities.lazyLoad(exports, ["V2BillingMeteredItem"], () => require("./v2billingMeteredItem"));

export { V2BillingPricingPlanArgs, V2BillingPricingPlanState } from "./v2billingPricingPlan";
export type V2BillingPricingPlan = import("./v2billingPricingPlan").V2BillingPricingPlan;
export const V2BillingPricingPlan: typeof import("./v2billingPricingPlan").V2BillingPricingPlan = null as any;
utilities.lazyLoad(exports, ["V2BillingPricingPlan"], () => require("./v2billingPricingPlan"));

export { V2BillingPricingPlanComponentArgs, V2BillingPricingPlanComponentState } from "./v2billingPricingPlanComponent";
export type V2BillingPricingPlanComponent = import("./v2billingPricingPlanComponent").V2BillingPricingPlanComponent;
export const V2BillingPricingPlanComponent: typeof import("./v2billingPricingPlanComponent").V2BillingPricingPlanComponent = null as any;
utilities.lazyLoad(exports, ["V2BillingPricingPlanComponent"], () => require("./v2billingPricingPlanComponent"));

export { V2BillingRateCardArgs, V2BillingRateCardState } from "./v2billingRateCard";
export type V2BillingRateCard = import("./v2billingRateCard").V2BillingRateCard;
export const V2BillingRateCard: typeof import("./v2billingRateCard").V2BillingRateCard = null as any;
utilities.lazyLoad(exports, ["V2BillingRateCard"], () => require("./v2billingRateCard"));

export { V2BillingRateCardRateArgs, V2BillingRateCardRateState } from "./v2billingRateCardRate";
export type V2BillingRateCardRate = import("./v2billingRateCardRate").V2BillingRateCardRate;
export const V2BillingRateCardRate: typeof import("./v2billingRateCardRate").V2BillingRateCardRate = null as any;
utilities.lazyLoad(exports, ["V2BillingRateCardRate"], () => require("./v2billingRateCardRate"));

export { V2BillingServiceActionArgs, V2BillingServiceActionState } from "./v2billingServiceAction";
export type V2BillingServiceAction = import("./v2billingServiceAction").V2BillingServiceAction;
export const V2BillingServiceAction: typeof import("./v2billingServiceAction").V2BillingServiceAction = null as any;
utilities.lazyLoad(exports, ["V2BillingServiceAction"], () => require("./v2billingServiceAction"));

export { V2CoreEventDestinationArgs, V2CoreEventDestinationState } from "./v2coreEventDestination";
export type V2CoreEventDestination = import("./v2coreEventDestination").V2CoreEventDestination;
export const V2CoreEventDestination: typeof import("./v2coreEventDestination").V2CoreEventDestination = null as any;
utilities.lazyLoad(exports, ["V2CoreEventDestination"], () => require("./v2coreEventDestination"));

export { WebhookEndpointArgs, WebhookEndpointState } from "./webhookEndpoint";
export type WebhookEndpoint = import("./webhookEndpoint").WebhookEndpoint;
export const WebhookEndpoint: typeof import("./webhookEndpoint").WebhookEndpoint = null as any;
utilities.lazyLoad(exports, ["WebhookEndpoint"], () => require("./webhookEndpoint"));


// Export sub-modules:
import * as config from "./config";
import * as types from "./types";

export {
    config,
    types,
};

const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "stripe:index/billingMeter:BillingMeter":
                return new BillingMeter(name, <any>undefined, { urn })
            case "stripe:index/coupon:Coupon":
                return new Coupon(name, <any>undefined, { urn })
            case "stripe:index/customer:Customer":
                return new Customer(name, <any>undefined, { urn })
            case "stripe:index/entitlementsFeature:EntitlementsFeature":
                return new EntitlementsFeature(name, <any>undefined, { urn })
            case "stripe:index/price:Price":
                return new Price(name, <any>undefined, { urn })
            case "stripe:index/product:Product":
                return new Product(name, <any>undefined, { urn })
            case "stripe:index/promotionCode:PromotionCode":
                return new PromotionCode(name, <any>undefined, { urn })
            case "stripe:index/shippingRate:ShippingRate":
                return new ShippingRate(name, <any>undefined, { urn })
            case "stripe:index/taxRate:TaxRate":
                return new TaxRate(name, <any>undefined, { urn })
            case "stripe:index/v2BillingLicenseFee:V2BillingLicenseFee":
                return new V2BillingLicenseFee(name, <any>undefined, { urn })
            case "stripe:index/v2BillingLicensedItem:V2BillingLicensedItem":
                return new V2BillingLicensedItem(name, <any>undefined, { urn })
            case "stripe:index/v2BillingMeteredItem:V2BillingMeteredItem":
                return new V2BillingMeteredItem(name, <any>undefined, { urn })
            case "stripe:index/v2BillingPricingPlan:V2BillingPricingPlan":
                return new V2BillingPricingPlan(name, <any>undefined, { urn })
            case "stripe:index/v2BillingPricingPlanComponent:V2BillingPricingPlanComponent":
                return new V2BillingPricingPlanComponent(name, <any>undefined, { urn })
            case "stripe:index/v2BillingRateCard:V2BillingRateCard":
                return new V2BillingRateCard(name, <any>undefined, { urn })
            case "stripe:index/v2BillingRateCardRate:V2BillingRateCardRate":
                return new V2BillingRateCardRate(name, <any>undefined, { urn })
            case "stripe:index/v2BillingServiceAction:V2BillingServiceAction":
                return new V2BillingServiceAction(name, <any>undefined, { urn })
            case "stripe:index/v2CoreEventDestination:V2CoreEventDestination":
                return new V2CoreEventDestination(name, <any>undefined, { urn })
            case "stripe:index/webhookEndpoint:WebhookEndpoint":
                return new WebhookEndpoint(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("stripe", "index/billingMeter", _module)
pulumi.runtime.registerResourceModule("stripe", "index/coupon", _module)
pulumi.runtime.registerResourceModule("stripe", "index/customer", _module)
pulumi.runtime.registerResourceModule("stripe", "index/entitlementsFeature", _module)
pulumi.runtime.registerResourceModule("stripe", "index/price", _module)
pulumi.runtime.registerResourceModule("stripe", "index/product", _module)
pulumi.runtime.registerResourceModule("stripe", "index/promotionCode", _module)
pulumi.runtime.registerResourceModule("stripe", "index/shippingRate", _module)
pulumi.runtime.registerResourceModule("stripe", "index/taxRate", _module)
pulumi.runtime.registerResourceModule("stripe", "index/v2BillingLicenseFee", _module)
pulumi.runtime.registerResourceModule("stripe", "index/v2BillingLicensedItem", _module)
pulumi.runtime.registerResourceModule("stripe", "index/v2BillingMeteredItem", _module)
pulumi.runtime.registerResourceModule("stripe", "index/v2BillingPricingPlan", _module)
pulumi.runtime.registerResourceModule("stripe", "index/v2BillingPricingPlanComponent", _module)
pulumi.runtime.registerResourceModule("stripe", "index/v2BillingRateCard", _module)
pulumi.runtime.registerResourceModule("stripe", "index/v2BillingRateCardRate", _module)
pulumi.runtime.registerResourceModule("stripe", "index/v2BillingServiceAction", _module)
pulumi.runtime.registerResourceModule("stripe", "index/v2CoreEventDestination", _module)
pulumi.runtime.registerResourceModule("stripe", "index/webhookEndpoint", _module)
pulumi.runtime.registerResourcePackage("stripe", {
    version: utilities.getVersion(),
    constructProvider: (name: string, type: string, urn: string): pulumi.ProviderResource => {
        if (type !== "pulumi:providers:stripe") {
            throw new Error(`unknown provider type ${type}`);
        }
        return new Provider(name, <any>undefined, { urn });
    },
});
