// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * Invoice Items represent the component lines of an [invoice](https://docs.stripe.com/api/invoices). When you create an invoice item with an `invoice` field, it is attached to the specified invoice and included as [an invoice line item](https://docs.stripe.com/api/invoices/line_item) within [invoice.lines](https://docs.stripe.com/api/invoices/object#invoice_object-lines).
 *
 * Invoice Items can be created before you are ready to actually send the invoice. This can be particularly useful when combined
 * with a [subscription](https://docs.stripe.com/api/subscriptions). Sometimes you want to add a charge or credit to a customer, but actually charge
 * or credit the customer's card only at the end of a regular billing cycle. This is useful for combining several charges
 * (to minimize per-transaction fees), or for having Stripe tabulate your usage-based billing totals.
 *
 * Related guides: [Integrate with the Invoicing API](https://docs.stripe.com/invoicing/integration), [Subscription Invoices](https://docs.stripe.com/billing/invoices/subscription#adding-upcoming-invoice-items).
 */
export class InvoiceItem extends pulumi.CustomResource {
    /**
     * Get an existing InvoiceItem resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: InvoiceItemState, opts?: pulumi.CustomResourceOptions): InvoiceItem {
        return new InvoiceItem(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'stripe:index/invoiceItem:InvoiceItem';

    /**
     * Returns true if the given object is an instance of InvoiceItem.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is InvoiceItem {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === InvoiceItem.__pulumiType;
    }

    /**
     * **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * Amount (in the `currency` specified) of the invoice item. This should always be equal to `unitAmount * quantity`.
     */
    declare public readonly amount: pulumi.Output<number | undefined>;
    /**
     * Three-letter [ISO currency code](https://www.iso.org/iso-4217-currency-codes.html), in lowercase. Must be a [supported currency](https://stripe.com/docs/currencies).
     */
    declare public readonly currency: pulumi.Output<string>;
    /**
     * The ID of the customer to bill for this invoice item.
     */
    declare public readonly customer: pulumi.Output<string>;
    /**
     * Time at which the object was created. Measured in seconds since the Unix epoch.
     */
    declare public /*out*/ readonly date: pulumi.Output<number>;
    /**
     * An arbitrary string attached to the object. Often useful for displaying to users.
     */
    declare public readonly description: pulumi.Output<string>;
    /**
     * If true, discounts will apply to this invoice item. Always false for prorations.
     */
    declare public readonly discountable: pulumi.Output<boolean>;
    /**
     * The discounts which apply to the invoice item. Item discounts are applied before invoice discounts. Use `expand[]=discounts` to expand each discount.
     */
    declare public readonly discounts: pulumi.Output<outputs.InvoiceItemDiscount[]>;
    /**
     * The ID of the invoice this invoice item belongs to.
     */
    declare public readonly invoice: pulumi.Output<string>;
    /**
     * If the object exists in live mode, the value is `true`. If the object exists in test mode, the value is `false`.
     */
    declare public /*out*/ readonly livemode: pulumi.Output<boolean>;
    /**
     * Set of [key-value pairs](https://docs.stripe.com/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format.
     */
    declare public readonly metadata: pulumi.Output<{[key: string]: string}>;
    /**
     * String representing the object's type. Objects of the same type share the same value.
     */
    declare public /*out*/ readonly object: pulumi.Output<string>;
    /**
     * The parent that generated this invoice item.
     */
    declare public /*out*/ readonly parent: pulumi.Output<outputs.InvoiceItemParent>;
    declare public readonly period: pulumi.Output<outputs.InvoiceItemPeriod>;
    /**
     * **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * Data used to generate a new [Price](https://docs.stripe.com/api/prices) object inline.
     */
    declare public readonly priceData: pulumi.Output<outputs.InvoiceItemPriceData | undefined>;
    /**
     * **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * The pricing information of the invoice item.
     */
    declare public readonly pricing: pulumi.Output<outputs.InvoiceItemPricing | undefined>;
    /**
     * Whether the invoice item was created automatically as a proration adjustment when the customer switched plans.
     */
    declare public /*out*/ readonly proration: pulumi.Output<boolean>;
    declare public /*out*/ readonly prorationDetails: pulumi.Output<outputs.InvoiceItemProrationDetails>;
    /**
     * Quantity of units for the invoice item in integer format, with any decimal precision truncated. For the item's full-precision decimal quantity, use `quantityDecimal`. This field will be deprecated in favor of `quantityDecimal` in a future version. If the invoice item is a proration, the quantity of the subscription that the proration was computed for.
     */
    declare public readonly quantity: pulumi.Output<number>;
    /**
     * **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * Non-negative decimal with at most 12 decimal places. The quantity of units for the invoice item.
     */
    declare public readonly quantityDecimal: pulumi.Output<number | undefined>;
    /**
     * **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * The ID of a subscription to add this invoice item to. When left blank, the invoice item is added to the next upcoming scheduled invoice. When set, scheduled invoices for subscriptions other than the specified subscription will ignore the invoice item. Use this when you want to express that an invoice item has been accrued within the context of a particular subscription.
     */
    declare public readonly subscription: pulumi.Output<string | undefined>;
    /**
     * **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * Only required if a [default tax behavior](<https://docs.stripe.com/tax/products-prices-tax-categories-tax-behavior#setting-a-default-tax-behavior-(recommended)>) was not provided in the Stripe Tax settings. Specifies whether the price is considered inclusive of taxes or exclusive of taxes. One of `inclusive`, `exclusive`, or `unspecified`. Once specified as either `inclusive` or `exclusive`, it cannot be changed.
     */
    declare public readonly taxBehavior: pulumi.Output<string | undefined>;
    /**
     * **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * A [tax code](https://docs.stripe.com/tax/tax-categories) ID.
     */
    declare public readonly taxCode: pulumi.Output<string | undefined>;
    /**
     * The tax rates which apply to the invoice item. When set, the `defaultTaxRates` on the invoice do not apply to this invoice item.
     */
    declare public readonly taxRates: pulumi.Output<string[]>;
    /**
     * ID of the test clock this invoice item belongs to.
     */
    declare public /*out*/ readonly testClock: pulumi.Output<string>;
    /**
     * **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * The decimal unit amount in cents (or local equivalent) of the charge to be applied to the upcoming invoice. This `unitAmountDecimal` will be multiplied by the quantity to get the full amount. Passing in a negative `unitAmountDecimal` will reduce the `amountDue` on the invoice. Accepts at most 12 decimal places.
     */
    declare public readonly unitAmountDecimal: pulumi.Output<number | undefined>;

    /**
     * Create a InvoiceItem resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: InvoiceItemArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: InvoiceItemArgs | InvoiceItemState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as InvoiceItemState | undefined;
            resourceInputs["amount"] = state?.amount;
            resourceInputs["currency"] = state?.currency;
            resourceInputs["customer"] = state?.customer;
            resourceInputs["date"] = state?.date;
            resourceInputs["description"] = state?.description;
            resourceInputs["discountable"] = state?.discountable;
            resourceInputs["discounts"] = state?.discounts;
            resourceInputs["invoice"] = state?.invoice;
            resourceInputs["livemode"] = state?.livemode;
            resourceInputs["metadata"] = state?.metadata;
            resourceInputs["object"] = state?.object;
            resourceInputs["parent"] = state?.parent;
            resourceInputs["period"] = state?.period;
            resourceInputs["priceData"] = state?.priceData;
            resourceInputs["pricing"] = state?.pricing;
            resourceInputs["proration"] = state?.proration;
            resourceInputs["prorationDetails"] = state?.prorationDetails;
            resourceInputs["quantity"] = state?.quantity;
            resourceInputs["quantityDecimal"] = state?.quantityDecimal;
            resourceInputs["subscription"] = state?.subscription;
            resourceInputs["taxBehavior"] = state?.taxBehavior;
            resourceInputs["taxCode"] = state?.taxCode;
            resourceInputs["taxRates"] = state?.taxRates;
            resourceInputs["testClock"] = state?.testClock;
            resourceInputs["unitAmountDecimal"] = state?.unitAmountDecimal;
        } else {
            const args = argsOrState as InvoiceItemArgs | undefined;
            resourceInputs["amount"] = args?.amount ? pulumi.secret(args.amount) : undefined;
            resourceInputs["currency"] = args?.currency;
            resourceInputs["customer"] = args?.customer;
            resourceInputs["description"] = args?.description;
            resourceInputs["discountable"] = args?.discountable;
            resourceInputs["discounts"] = args?.discounts;
            resourceInputs["invoice"] = args?.invoice;
            resourceInputs["metadata"] = args?.metadata;
            resourceInputs["period"] = args?.period;
            resourceInputs["priceData"] = args?.priceData ? pulumi.secret(args.priceData) : undefined;
            resourceInputs["pricing"] = args?.pricing ? pulumi.secret(args.pricing) : undefined;
            resourceInputs["quantity"] = args?.quantity;
            resourceInputs["quantityDecimal"] = args?.quantityDecimal ? pulumi.secret(args.quantityDecimal) : undefined;
            resourceInputs["subscription"] = args?.subscription ? pulumi.secret(args.subscription) : undefined;
            resourceInputs["taxBehavior"] = args?.taxBehavior ? pulumi.secret(args.taxBehavior) : undefined;
            resourceInputs["taxCode"] = args?.taxCode ? pulumi.secret(args.taxCode) : undefined;
            resourceInputs["taxRates"] = args?.taxRates;
            resourceInputs["unitAmountDecimal"] = args?.unitAmountDecimal ? pulumi.secret(args.unitAmountDecimal) : undefined;
            resourceInputs["date"] = undefined /*out*/;
            resourceInputs["livemode"] = undefined /*out*/;
            resourceInputs["object"] = undefined /*out*/;
            resourceInputs["parent"] = undefined /*out*/;
            resourceInputs["proration"] = undefined /*out*/;
            resourceInputs["prorationDetails"] = undefined /*out*/;
            resourceInputs["testClock"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["amount", "priceData", "pricing", "quantityDecimal", "subscription", "taxBehavior", "taxCode", "unitAmountDecimal"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(InvoiceItem.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering InvoiceItem resources.
 */
export interface InvoiceItemState {
    /**
     * **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * Amount (in the `currency` specified) of the invoice item. This should always be equal to `unitAmount * quantity`.
     */
    amount?: pulumi.Input<number | undefined>;
    /**
     * Three-letter [ISO currency code](https://www.iso.org/iso-4217-currency-codes.html), in lowercase. Must be a [supported currency](https://stripe.com/docs/currencies).
     */
    currency?: pulumi.Input<string | undefined>;
    /**
     * The ID of the customer to bill for this invoice item.
     */
    customer?: pulumi.Input<string | undefined>;
    /**
     * Time at which the object was created. Measured in seconds since the Unix epoch.
     */
    date?: pulumi.Input<number | undefined>;
    /**
     * An arbitrary string attached to the object. Often useful for displaying to users.
     */
    description?: pulumi.Input<string | undefined>;
    /**
     * If true, discounts will apply to this invoice item. Always false for prorations.
     */
    discountable?: pulumi.Input<boolean | undefined>;
    /**
     * The discounts which apply to the invoice item. Item discounts are applied before invoice discounts. Use `expand[]=discounts` to expand each discount.
     */
    discounts?: pulumi.Input<pulumi.Input<inputs.InvoiceItemDiscount>[] | undefined>;
    /**
     * The ID of the invoice this invoice item belongs to.
     */
    invoice?: pulumi.Input<string | undefined>;
    /**
     * If the object exists in live mode, the value is `true`. If the object exists in test mode, the value is `false`.
     */
    livemode?: pulumi.Input<boolean | undefined>;
    /**
     * Set of [key-value pairs](https://docs.stripe.com/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format.
     */
    metadata?: pulumi.Input<{[key: string]: pulumi.Input<string>} | undefined>;
    /**
     * String representing the object's type. Objects of the same type share the same value.
     */
    object?: pulumi.Input<string | undefined>;
    /**
     * The parent that generated this invoice item.
     */
    parent?: pulumi.Input<inputs.InvoiceItemParent | undefined>;
    period?: pulumi.Input<inputs.InvoiceItemPeriod | undefined>;
    /**
     * **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * Data used to generate a new [Price](https://docs.stripe.com/api/prices) object inline.
     */
    priceData?: pulumi.Input<inputs.InvoiceItemPriceData | undefined>;
    /**
     * **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * The pricing information of the invoice item.
     */
    pricing?: pulumi.Input<inputs.InvoiceItemPricing | undefined>;
    /**
     * Whether the invoice item was created automatically as a proration adjustment when the customer switched plans.
     */
    proration?: pulumi.Input<boolean | undefined>;
    prorationDetails?: pulumi.Input<inputs.InvoiceItemProrationDetails | undefined>;
    /**
     * Quantity of units for the invoice item in integer format, with any decimal precision truncated. For the item's full-precision decimal quantity, use `quantityDecimal`. This field will be deprecated in favor of `quantityDecimal` in a future version. If the invoice item is a proration, the quantity of the subscription that the proration was computed for.
     */
    quantity?: pulumi.Input<number | undefined>;
    /**
     * **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * Non-negative decimal with at most 12 decimal places. The quantity of units for the invoice item.
     */
    quantityDecimal?: pulumi.Input<number | undefined>;
    /**
     * **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * The ID of a subscription to add this invoice item to. When left blank, the invoice item is added to the next upcoming scheduled invoice. When set, scheduled invoices for subscriptions other than the specified subscription will ignore the invoice item. Use this when you want to express that an invoice item has been accrued within the context of a particular subscription.
     */
    subscription?: pulumi.Input<string | undefined>;
    /**
     * **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * Only required if a [default tax behavior](<https://docs.stripe.com/tax/products-prices-tax-categories-tax-behavior#setting-a-default-tax-behavior-(recommended)>) was not provided in the Stripe Tax settings. Specifies whether the price is considered inclusive of taxes or exclusive of taxes. One of `inclusive`, `exclusive`, or `unspecified`. Once specified as either `inclusive` or `exclusive`, it cannot be changed.
     */
    taxBehavior?: pulumi.Input<string | undefined>;
    /**
     * **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * A [tax code](https://docs.stripe.com/tax/tax-categories) ID.
     */
    taxCode?: pulumi.Input<string | undefined>;
    /**
     * The tax rates which apply to the invoice item. When set, the `defaultTaxRates` on the invoice do not apply to this invoice item.
     */
    taxRates?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * ID of the test clock this invoice item belongs to.
     */
    testClock?: pulumi.Input<string | undefined>;
    /**
     * **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * The decimal unit amount in cents (or local equivalent) of the charge to be applied to the upcoming invoice. This `unitAmountDecimal` will be multiplied by the quantity to get the full amount. Passing in a negative `unitAmountDecimal` will reduce the `amountDue` on the invoice. Accepts at most 12 decimal places.
     */
    unitAmountDecimal?: pulumi.Input<number | undefined>;
}

/**
 * The set of arguments for constructing a InvoiceItem resource.
 */
export interface InvoiceItemArgs {
    /**
     * **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * Amount (in the `currency` specified) of the invoice item. This should always be equal to `unitAmount * quantity`.
     */
    amount?: pulumi.Input<number | undefined>;
    /**
     * Three-letter [ISO currency code](https://www.iso.org/iso-4217-currency-codes.html), in lowercase. Must be a [supported currency](https://stripe.com/docs/currencies).
     */
    currency?: pulumi.Input<string | undefined>;
    /**
     * The ID of the customer to bill for this invoice item.
     */
    customer?: pulumi.Input<string | undefined>;
    /**
     * An arbitrary string attached to the object. Often useful for displaying to users.
     */
    description?: pulumi.Input<string | undefined>;
    /**
     * If true, discounts will apply to this invoice item. Always false for prorations.
     */
    discountable?: pulumi.Input<boolean | undefined>;
    /**
     * The discounts which apply to the invoice item. Item discounts are applied before invoice discounts. Use `expand[]=discounts` to expand each discount.
     */
    discounts?: pulumi.Input<pulumi.Input<inputs.InvoiceItemDiscount>[] | undefined>;
    /**
     * The ID of the invoice this invoice item belongs to.
     */
    invoice?: pulumi.Input<string | undefined>;
    /**
     * Set of [key-value pairs](https://docs.stripe.com/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format.
     */
    metadata?: pulumi.Input<{[key: string]: pulumi.Input<string>} | undefined>;
    period?: pulumi.Input<inputs.InvoiceItemPeriod | undefined>;
    /**
     * **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * Data used to generate a new [Price](https://docs.stripe.com/api/prices) object inline.
     */
    priceData?: pulumi.Input<inputs.InvoiceItemPriceData | undefined>;
    /**
     * **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * The pricing information of the invoice item.
     */
    pricing?: pulumi.Input<inputs.InvoiceItemPricing | undefined>;
    /**
     * Quantity of units for the invoice item in integer format, with any decimal precision truncated. For the item's full-precision decimal quantity, use `quantityDecimal`. This field will be deprecated in favor of `quantityDecimal` in a future version. If the invoice item is a proration, the quantity of the subscription that the proration was computed for.
     */
    quantity?: pulumi.Input<number | undefined>;
    /**
     * **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * Non-negative decimal with at most 12 decimal places. The quantity of units for the invoice item.
     */
    quantityDecimal?: pulumi.Input<number | undefined>;
    /**
     * **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * The ID of a subscription to add this invoice item to. When left blank, the invoice item is added to the next upcoming scheduled invoice. When set, scheduled invoices for subscriptions other than the specified subscription will ignore the invoice item. Use this when you want to express that an invoice item has been accrued within the context of a particular subscription.
     */
    subscription?: pulumi.Input<string | undefined>;
    /**
     * **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * Only required if a [default tax behavior](<https://docs.stripe.com/tax/products-prices-tax-categories-tax-behavior#setting-a-default-tax-behavior-(recommended)>) was not provided in the Stripe Tax settings. Specifies whether the price is considered inclusive of taxes or exclusive of taxes. One of `inclusive`, `exclusive`, or `unspecified`. Once specified as either `inclusive` or `exclusive`, it cannot be changed.
     */
    taxBehavior?: pulumi.Input<string | undefined>;
    /**
     * **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * A [tax code](https://docs.stripe.com/tax/tax-categories) ID.
     */
    taxCode?: pulumi.Input<string | undefined>;
    /**
     * The tax rates which apply to the invoice item. When set, the `defaultTaxRates` on the invoice do not apply to this invoice item.
     */
    taxRates?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * The decimal unit amount in cents (or local equivalent) of the charge to be applied to the upcoming invoice. This `unitAmountDecimal` will be multiplied by the quantity to get the full amount. Passing in a negative `unitAmountDecimal` will reduce the `amountDue` on the invoice. Accepts at most 12 decimal places.
     */
    unitAmountDecimal?: pulumi.Input<number | undefined>;
}
