// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * Invoices are statements of amounts owed by a customer, and are either
 * generated one-off, or generated periodically from a subscription.
 *
 * They contain [invoice items](https://api.stripe.com#invoiceitems), and proration adjustments
 * that may be caused by subscription upgrades/downgrades (if necessary).
 *
 * If your invoice is configured to be billed through automatic charges,
 * Stripe automatically finalizes your invoice and attempts payment. Note
 * that finalizing the invoice,
 * [when automatic](https://docs.stripe.com/invoicing/integration/automatic-advancement-collection), does
 * not happen immediately as the invoice is created. Stripe waits
 * until one hour after the last webhook was successfully sent (or the last
 * webhook timed out after failing). If you (and the platforms you may have
 * connected to) have no webhooks configured, Stripe waits one hour after
 * creation to finalize the invoice.
 *
 * If your invoice is configured to be billed by sending an email, then based on your
 * [email settings](https://dashboard.stripe.com/account/billing/automatic),
 * Stripe will email the invoice to your customer and await payment. These
 * emails can contain a link to a hosted page to pay the invoice.
 *
 * Stripe applies any customer credit on the account before determining the
 * amount due for the invoice (i.e., the amount that will be actually
 * charged). If the amount due for the invoice is less than Stripe's [minimum allowed charge
 * per currency](https://www.terraform.io/docs/currencies#minimum-and-maximum-charge-amounts), the
 * invoice is automatically marked paid, and we add the amount due to the
 * customer's credit balance which is applied to the next invoice.
 *
 * More details on the customer's credit balance are
 * [here](https://docs.stripe.com/billing/customer/balance).
 *
 * Related guide: [Send invoices to customers](https://docs.stripe.com/billing/invoices/sending)
 */
export class Invoice extends pulumi.CustomResource {
    /**
     * Get an existing Invoice resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: InvoiceState, opts?: pulumi.CustomResourceOptions): Invoice {
        return new Invoice(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'stripe:index/invoice:Invoice';

    /**
     * Returns true if the given object is an instance of Invoice.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Invoice {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Invoice.__pulumiType;
    }

    /**
     * The country of the business associated with this invoice, most often the business creating the invoice.
     */
    declare public /*out*/ readonly accountCountry: pulumi.Output<string>;
    /**
     * The public name of the business associated with this invoice, most often the business creating the invoice.
     */
    declare public /*out*/ readonly accountName: pulumi.Output<string>;
    /**
     * The account tax IDs associated with the invoice. Only editable when the invoice is a draft.
     */
    declare public readonly accountTaxIds: pulumi.Output<string[]>;
    /**
     * Final amount due at this time for this invoice. If the invoice's total is smaller than the minimum charge amount, for example, or if there is account credit that can be applied to the invoice, the `amountDue` may be 0. If there is a positive `startingBalance` for the invoice (the customer owes money), the `amountDue` will also take that into account. The charge that gets generated for the invoice will be for the amount specified in `amountDue`.
     */
    declare public /*out*/ readonly amountDue: pulumi.Output<number>;
    /**
     * Amount that was overpaid on the invoice. The amount overpaid is credited to the customer's credit balance.
     */
    declare public /*out*/ readonly amountOverpaid: pulumi.Output<number>;
    /**
     * The amount, in cents (or local equivalent), that was paid.
     */
    declare public /*out*/ readonly amountPaid: pulumi.Output<number>;
    /**
     * Amount, in cents (or local equivalent), that was paid on the invoice outside of Stripe.
     */
    declare public /*out*/ readonly amountPaidOffStripe: pulumi.Output<number>;
    /**
     * The difference between amountDue and amount_paid, in cents (or local equivalent).
     */
    declare public /*out*/ readonly amountRemaining: pulumi.Output<number>;
    /**
     * This is the sum of all the shipping amounts.
     */
    declare public /*out*/ readonly amountShipping: pulumi.Output<number>;
    /**
     * ID of the Connect Application that created the invoice.
     */
    declare public /*out*/ readonly application: pulumi.Output<string>;
    /**
     * **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * A fee in cents (or local equivalent) that will be applied to the invoice and transferred to the application owner's Stripe account. The request must be made with an OAuth key or the Stripe-Account header in order to take an application fee. For more information, see the application fees [documentation](https://docs.stripe.com/billing/invoices/connect#collecting-fees).
     */
    declare public readonly applicationFeeAmount: pulumi.Output<number | undefined>;
    /**
     * Number of payment attempts made for this invoice, from the perspective of the payment retry schedule. Any payment attempt counts as the first attempt, and subsequently only automatic retries increment the attempt count. In other words, manual payment attempts after the first attempt do not affect the retry schedule. If a failure is returned with a non-retryable return code, the invoice can no longer be retried unless a new payment method is obtained. Retries will continue to be scheduled, and attemptCount will continue to increment, but retries will only be executed if a new payment method is obtained.
     */
    declare public /*out*/ readonly attemptCount: pulumi.Output<number>;
    /**
     * Whether an attempt has been made to pay the invoice. An invoice is not attempted until 1 hour after the `invoice.created` webhook, for example, so you might not want to display that invoice as unpaid to your users.
     */
    declare public /*out*/ readonly attempted: pulumi.Output<boolean>;
    /**
     * Controls whether Stripe performs [automatic collection](https://docs.stripe.com/invoicing/integration/automatic-advancement-collection) of the invoice. If `false`, the invoice's state doesn't automatically advance without an explicit action.
     */
    declare public readonly autoAdvance: pulumi.Output<boolean>;
    declare public readonly automaticTax: pulumi.Output<outputs.InvoiceAutomaticTax>;
    /**
     * The time when this invoice is currently scheduled to be automatically finalized. The field will be `null` if the invoice is not scheduled to finalize in the future. If the invoice is not in the draft state, this field will always be `null` - see `finalizedAt` for the time when an already-finalized invoice was finalized.
     */
    declare public readonly automaticallyFinalizesAt: pulumi.Output<number>;
    /**
     * Indicates the reason why the invoice was created.
     *
     * * `manual`: Unrelated to a subscription, for example, created via the invoice editor.
     * * `subscription`: No longer in use. Applies to subscriptions from before May 2018 where no distinction was made between updates, cycles, and thresholds.
     * * `subscriptionCreate`: A new subscription was created.
     * * `subscriptionCycle`: A subscription advanced into a new period.
     * * `subscriptionThreshold`: A subscription reached a billing threshold.
     * * `subscriptionUpdate`: A subscription was updated.
     * * `upcoming`: Reserved for upcoming invoices created through the Create Preview Invoice API or when an `invoice.upcoming` event is generated for an upcoming invoice on a subscription.
     */
    declare public /*out*/ readonly billingReason: pulumi.Output<string>;
    /**
     * Either `chargeAutomatically`, or `sendInvoice`. When charging automatically, Stripe will attempt to pay this invoice using the default source attached to the customer. When sending an invoice, Stripe will email this invoice to the customer with payment instructions.
     */
    declare public readonly collectionMethod: pulumi.Output<string>;
    /**
     * The confirmation secret associated with this invoice. Currently, this contains the clientSecret of the PaymentIntent that Stripe creates during invoice finalization.
     */
    declare public /*out*/ readonly confirmationSecret: pulumi.Output<outputs.InvoiceConfirmationSecret>;
    /**
     * Time at which the object was created. Measured in seconds since the Unix epoch.
     */
    declare public /*out*/ readonly created: pulumi.Output<number>;
    /**
     * Three-letter [ISO currency code](https://www.iso.org/iso-4217-currency-codes.html), in lowercase. Must be a [supported currency](https://stripe.com/docs/currencies).
     */
    declare public readonly currency: pulumi.Output<string>;
    /**
     * Custom fields displayed on the invoice.
     */
    declare public readonly customFields: pulumi.Output<outputs.InvoiceCustomField[]>;
    /**
     * The ID of the customer to bill.
     */
    declare public readonly customer: pulumi.Output<string>;
    /**
     * The ID of the account representing the customer to bill.
     */
    declare public readonly customerAccount: pulumi.Output<string>;
    /**
     * The customer's address. Until the invoice is finalized, this field will equal `customer.address`. Once the invoice is finalized, this field will no longer be updated.
     */
    declare public /*out*/ readonly customerAddress: pulumi.Output<outputs.InvoiceCustomerAddress>;
    /**
     * The customer's email. Until the invoice is finalized, this field will equal `customer.email`. Once the invoice is finalized, this field will no longer be updated.
     */
    declare public /*out*/ readonly customerEmail: pulumi.Output<string>;
    /**
     * The customer's name. Until the invoice is finalized, this field will equal `customer.name`. Once the invoice is finalized, this field will no longer be updated.
     */
    declare public /*out*/ readonly customerName: pulumi.Output<string>;
    /**
     * The customer's phone number. Until the invoice is finalized, this field will equal `customer.phone`. Once the invoice is finalized, this field will no longer be updated.
     */
    declare public /*out*/ readonly customerPhone: pulumi.Output<string>;
    /**
     * The customer's shipping information. Until the invoice is finalized, this field will equal `customer.shipping`. Once the invoice is finalized, this field will no longer be updated.
     */
    declare public /*out*/ readonly customerShipping: pulumi.Output<outputs.InvoiceCustomerShipping>;
    /**
     * The customer's tax IDs. Until the invoice is finalized, this field will contain the same tax IDs as `customer.tax_ids`. Once the invoice is finalized, this field will no longer be updated.
     */
    declare public /*out*/ readonly customerTaxIds: pulumi.Output<outputs.InvoiceCustomerTaxId[]>;
    /**
     * **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * The number of days from when the invoice is created until it is due. Valid only for invoices where `collection_method=send_invoice`.
     */
    declare public readonly daysUntilDue: pulumi.Output<number | undefined>;
    /**
     * ID of the default payment method for the invoice. It must belong to the customer associated with the invoice. If not set, defaults to the subscription's default payment method, if any, or to the default payment method in the customer's invoice settings.
     */
    declare public readonly defaultPaymentMethod: pulumi.Output<string>;
    /**
     * ID of the default payment source for the invoice. It must belong to the customer associated with the invoice and be in a chargeable state. If not set, defaults to the subscription's default source, if any, or to the customer's default source.
     */
    declare public readonly defaultSource: pulumi.Output<string>;
    /**
     * The tax rates applied to this invoice, if any.
     */
    declare public readonly defaultTaxRates: pulumi.Output<string[]>;
    /**
     * An arbitrary string attached to the object. Often useful for displaying to users. Referenced as 'memo' in the Dashboard.
     */
    declare public readonly description: pulumi.Output<string>;
    /**
     * The discounts applied to the invoice. Line item discounts are applied before invoice discounts. Use `expand[]=discounts` to expand each discount.
     */
    declare public readonly discounts: pulumi.Output<outputs.InvoiceDiscount[]>;
    /**
     * The date on which payment for this invoice is due. This value will be `null` for invoices where `collection_method=charge_automatically`.
     */
    declare public readonly dueDate: pulumi.Output<number>;
    /**
     * The date when this invoice is in effect. Same as `finalizedAt` unless overwritten. When defined, this value replaces the system-generated 'Date of issue' printed on the invoice PDF and receipt.
     */
    declare public readonly effectiveAt: pulumi.Output<number>;
    /**
     * Ending customer balance after the invoice is finalized. Invoices are finalized approximately an hour after successful webhook delivery or when payment collection is attempted for the invoice. If the invoice has not been finalized yet, this will be null.
     */
    declare public /*out*/ readonly endingBalance: pulumi.Output<number>;
    /**
     * Footer displayed on the invoice.
     */
    declare public readonly footer: pulumi.Output<string>;
    /**
     * Details of the invoice that was cloned. See the [revision documentation](https://docs.stripe.com/invoicing/invoice-revisions) for more details.
     */
    declare public readonly fromInvoice: pulumi.Output<outputs.InvoiceFromInvoice>;
    /**
     * The URL for the hosted invoice page, which allows customers to view and pay an invoice. If the invoice has not been finalized yet, this will be null.
     */
    declare public /*out*/ readonly hostedInvoiceUrl: pulumi.Output<string>;
    /**
     * The link to download the PDF for the invoice. If the invoice has not been finalized yet, this will be null.
     */
    declare public /*out*/ readonly invoicePdf: pulumi.Output<string>;
    declare public readonly issuer: pulumi.Output<outputs.InvoiceIssuer>;
    /**
     * The error encountered during the previous attempt to finalize the invoice. This field is cleared when the invoice is successfully finalized.
     */
    declare public /*out*/ readonly lastFinalizationError: pulumi.Output<outputs.InvoiceLastFinalizationError>;
    /**
     * The ID of the most recent non-draft revision of this invoice
     */
    declare public /*out*/ readonly latestRevision: pulumi.Output<string>;
    /**
     * If the object exists in live mode, the value is `true`. If the object exists in test mode, the value is `false`.
     */
    declare public /*out*/ readonly livemode: pulumi.Output<boolean>;
    /**
     * Set of [key-value pairs](https://docs.stripe.com/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format.
     */
    declare public readonly metadata: pulumi.Output<{[key: string]: string}>;
    /**
     * The time at which payment will next be attempted. This value will be `null` for invoices where `collection_method=send_invoice`.
     */
    declare public /*out*/ readonly nextPaymentAttempt: pulumi.Output<number>;
    /**
     * A unique, identifying string that appears on emails sent to the customer for this invoice. This starts with the customer's unique invoicePrefix if it is specified.
     */
    declare public readonly number: pulumi.Output<string>;
    /**
     * String representing the object's type. Objects of the same type share the same value.
     */
    declare public /*out*/ readonly object: pulumi.Output<string>;
    /**
     * The account (if any) for which the funds of the invoice payment are intended. If set, the invoice will be presented with the branding and support information of the specified account. See the [Invoices with Connect](https://docs.stripe.com/billing/invoices/connect) documentation for details.
     */
    declare public readonly onBehalfOf: pulumi.Output<string>;
    /**
     * The parent that generated this invoice
     */
    declare public /*out*/ readonly parent: pulumi.Output<outputs.InvoiceParent>;
    declare public readonly paymentSettings: pulumi.Output<outputs.InvoicePaymentSettings>;
    /**
     * **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * How to handle pending invoice items on invoice creation. Defaults to `exclude` if the parameter is omitted.
     */
    declare public readonly pendingInvoiceItemsBehavior: pulumi.Output<string | undefined>;
    /**
     * The latest timestamp at which invoice items can be associated with this invoice. Use the [line item period](https://www.terraform.io/api/invoices/line_item#invoice_line_item_object-period) to get the service period for each price.
     */
    declare public /*out*/ readonly periodEnd: pulumi.Output<number>;
    /**
     * The earliest timestamp at which invoice items can be associated with this invoice. Use the [line item period](https://www.terraform.io/api/invoices/line_item#invoice_line_item_object-period) to get the service period for each price.
     */
    declare public /*out*/ readonly periodStart: pulumi.Output<number>;
    /**
     * Total amount of all post-payment credit notes issued for this invoice.
     */
    declare public /*out*/ readonly postPaymentCreditNotesAmount: pulumi.Output<number>;
    /**
     * Total amount of all pre-payment credit notes issued for this invoice.
     */
    declare public /*out*/ readonly prePaymentCreditNotesAmount: pulumi.Output<number>;
    /**
     * This is the transaction number that appears on email receipts sent for this invoice.
     */
    declare public /*out*/ readonly receiptNumber: pulumi.Output<string>;
    /**
     * The rendering-related settings that control how the invoice is displayed on customer-facing surfaces such as PDF and Hosted Invoice Page.
     */
    declare public readonly rendering: pulumi.Output<outputs.InvoiceRendering>;
    /**
     * The details of the cost of shipping, including the ShippingRate applied on the invoice.
     */
    declare public readonly shippingCost: pulumi.Output<outputs.InvoiceShippingCost>;
    /**
     * Shipping details for the invoice. The Invoice PDF will use the `shippingDetails` value if it is set, otherwise the PDF will render the shipping address from the customer.
     */
    declare public readonly shippingDetails: pulumi.Output<outputs.InvoiceShippingDetails>;
    /**
     * Starting customer balance before the invoice is finalized. If the invoice has not been finalized yet, this will be the current customer balance. For revision invoices, this also includes any customer balance that was applied to the original invoice.
     */
    declare public /*out*/ readonly startingBalance: pulumi.Output<number>;
    /**
     * Extra information about an invoice for the customer's credit card statement.
     */
    declare public readonly statementDescriptor: pulumi.Output<string>;
    /**
     * The status of the invoice, one of `draft`, `open`, `paid`, `uncollectible`, or `void`. [Learn more](https://docs.stripe.com/billing/invoices/workflow#workflow-overview)
     */
    declare public /*out*/ readonly status: pulumi.Output<string>;
    declare public /*out*/ readonly statusTransitions: pulumi.Output<outputs.InvoiceStatusTransitions>;
    declare public readonly subscription: pulumi.Output<string>;
    /**
     * Total of all subscriptions, invoice items, and prorations on the invoice before any invoice level discount or exclusive tax is applied. Item discounts are already incorporated
     */
    declare public /*out*/ readonly subtotal: pulumi.Output<number>;
    /**
     * The integer amount in cents (or local equivalent) representing the subtotal of the invoice before any invoice level discount or tax is applied. Item discounts are already incorporated
     */
    declare public /*out*/ readonly subtotalExcludingTax: pulumi.Output<number>;
    /**
     * ID of the test clock this invoice belongs to.
     */
    declare public /*out*/ readonly testClock: pulumi.Output<string>;
    declare public /*out*/ readonly thresholdReason: pulumi.Output<outputs.InvoiceThresholdReason>;
    /**
     * Total after discounts and taxes.
     */
    declare public /*out*/ readonly total: pulumi.Output<number>;
    /**
     * The aggregate amounts calculated per discount across all line items.
     */
    declare public /*out*/ readonly totalDiscountAmounts: pulumi.Output<outputs.InvoiceTotalDiscountAmount[]>;
    /**
     * The integer amount in cents (or local equivalent) representing the total amount of the invoice including all discounts but excluding all tax.
     */
    declare public /*out*/ readonly totalExcludingTax: pulumi.Output<number>;
    /**
     * Contains pretax credit amounts (ex: discount, credit grants, etc) that apply to this invoice. This is a combined list of totalPretaxCreditAmounts across all invoice line items.
     */
    declare public /*out*/ readonly totalPretaxCreditAmounts: pulumi.Output<outputs.InvoiceTotalPretaxCreditAmount[]>;
    /**
     * The aggregate tax information of all line items.
     */
    declare public /*out*/ readonly totalTaxes: pulumi.Output<outputs.InvoiceTotalTax[]>;
    /**
     * **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * If specified, the funds from the invoice will be transferred to the destination and the ID of the resulting transfer will be found on the invoice's charge.
     */
    declare public readonly transferData: pulumi.Output<outputs.InvoiceTransferData | undefined>;
    /**
     * Invoices are automatically paid or sent 1 hour after webhooks are delivered, or until all webhook delivery attempts have [been exhausted](https://docs.stripe.com/billing/webhooks#understand). This field tracks the time when webhooks for this invoice were successfully delivered. If the invoice had no webhooks to deliver, this will be set while the invoice is being created.
     */
    declare public /*out*/ readonly webhooksDeliveredAt: pulumi.Output<number>;

    /**
     * Create a Invoice resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: InvoiceArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: InvoiceArgs | InvoiceState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as InvoiceState | undefined;
            resourceInputs["accountCountry"] = state?.accountCountry;
            resourceInputs["accountName"] = state?.accountName;
            resourceInputs["accountTaxIds"] = state?.accountTaxIds;
            resourceInputs["amountDue"] = state?.amountDue;
            resourceInputs["amountOverpaid"] = state?.amountOverpaid;
            resourceInputs["amountPaid"] = state?.amountPaid;
            resourceInputs["amountPaidOffStripe"] = state?.amountPaidOffStripe;
            resourceInputs["amountRemaining"] = state?.amountRemaining;
            resourceInputs["amountShipping"] = state?.amountShipping;
            resourceInputs["application"] = state?.application;
            resourceInputs["applicationFeeAmount"] = state?.applicationFeeAmount;
            resourceInputs["attemptCount"] = state?.attemptCount;
            resourceInputs["attempted"] = state?.attempted;
            resourceInputs["autoAdvance"] = state?.autoAdvance;
            resourceInputs["automaticTax"] = state?.automaticTax;
            resourceInputs["automaticallyFinalizesAt"] = state?.automaticallyFinalizesAt;
            resourceInputs["billingReason"] = state?.billingReason;
            resourceInputs["collectionMethod"] = state?.collectionMethod;
            resourceInputs["confirmationSecret"] = state?.confirmationSecret;
            resourceInputs["created"] = state?.created;
            resourceInputs["currency"] = state?.currency;
            resourceInputs["customFields"] = state?.customFields;
            resourceInputs["customer"] = state?.customer;
            resourceInputs["customerAccount"] = state?.customerAccount;
            resourceInputs["customerAddress"] = state?.customerAddress;
            resourceInputs["customerEmail"] = state?.customerEmail;
            resourceInputs["customerName"] = state?.customerName;
            resourceInputs["customerPhone"] = state?.customerPhone;
            resourceInputs["customerShipping"] = state?.customerShipping;
            resourceInputs["customerTaxIds"] = state?.customerTaxIds;
            resourceInputs["daysUntilDue"] = state?.daysUntilDue;
            resourceInputs["defaultPaymentMethod"] = state?.defaultPaymentMethod;
            resourceInputs["defaultSource"] = state?.defaultSource;
            resourceInputs["defaultTaxRates"] = state?.defaultTaxRates;
            resourceInputs["description"] = state?.description;
            resourceInputs["discounts"] = state?.discounts;
            resourceInputs["dueDate"] = state?.dueDate;
            resourceInputs["effectiveAt"] = state?.effectiveAt;
            resourceInputs["endingBalance"] = state?.endingBalance;
            resourceInputs["footer"] = state?.footer;
            resourceInputs["fromInvoice"] = state?.fromInvoice;
            resourceInputs["hostedInvoiceUrl"] = state?.hostedInvoiceUrl;
            resourceInputs["invoicePdf"] = state?.invoicePdf;
            resourceInputs["issuer"] = state?.issuer;
            resourceInputs["lastFinalizationError"] = state?.lastFinalizationError;
            resourceInputs["latestRevision"] = state?.latestRevision;
            resourceInputs["livemode"] = state?.livemode;
            resourceInputs["metadata"] = state?.metadata;
            resourceInputs["nextPaymentAttempt"] = state?.nextPaymentAttempt;
            resourceInputs["number"] = state?.number;
            resourceInputs["object"] = state?.object;
            resourceInputs["onBehalfOf"] = state?.onBehalfOf;
            resourceInputs["parent"] = state?.parent;
            resourceInputs["paymentSettings"] = state?.paymentSettings;
            resourceInputs["pendingInvoiceItemsBehavior"] = state?.pendingInvoiceItemsBehavior;
            resourceInputs["periodEnd"] = state?.periodEnd;
            resourceInputs["periodStart"] = state?.periodStart;
            resourceInputs["postPaymentCreditNotesAmount"] = state?.postPaymentCreditNotesAmount;
            resourceInputs["prePaymentCreditNotesAmount"] = state?.prePaymentCreditNotesAmount;
            resourceInputs["receiptNumber"] = state?.receiptNumber;
            resourceInputs["rendering"] = state?.rendering;
            resourceInputs["shippingCost"] = state?.shippingCost;
            resourceInputs["shippingDetails"] = state?.shippingDetails;
            resourceInputs["startingBalance"] = state?.startingBalance;
            resourceInputs["statementDescriptor"] = state?.statementDescriptor;
            resourceInputs["status"] = state?.status;
            resourceInputs["statusTransitions"] = state?.statusTransitions;
            resourceInputs["subscription"] = state?.subscription;
            resourceInputs["subtotal"] = state?.subtotal;
            resourceInputs["subtotalExcludingTax"] = state?.subtotalExcludingTax;
            resourceInputs["testClock"] = state?.testClock;
            resourceInputs["thresholdReason"] = state?.thresholdReason;
            resourceInputs["total"] = state?.total;
            resourceInputs["totalDiscountAmounts"] = state?.totalDiscountAmounts;
            resourceInputs["totalExcludingTax"] = state?.totalExcludingTax;
            resourceInputs["totalPretaxCreditAmounts"] = state?.totalPretaxCreditAmounts;
            resourceInputs["totalTaxes"] = state?.totalTaxes;
            resourceInputs["transferData"] = state?.transferData;
            resourceInputs["webhooksDeliveredAt"] = state?.webhooksDeliveredAt;
        } else {
            const args = argsOrState as InvoiceArgs | undefined;
            resourceInputs["accountTaxIds"] = args?.accountTaxIds;
            resourceInputs["applicationFeeAmount"] = args?.applicationFeeAmount ? pulumi.secret(args.applicationFeeAmount) : undefined;
            resourceInputs["autoAdvance"] = args?.autoAdvance;
            resourceInputs["automaticTax"] = args?.automaticTax;
            resourceInputs["automaticallyFinalizesAt"] = args?.automaticallyFinalizesAt;
            resourceInputs["collectionMethod"] = args?.collectionMethod;
            resourceInputs["currency"] = args?.currency;
            resourceInputs["customFields"] = args?.customFields;
            resourceInputs["customer"] = args?.customer;
            resourceInputs["customerAccount"] = args?.customerAccount;
            resourceInputs["daysUntilDue"] = args?.daysUntilDue ? pulumi.secret(args.daysUntilDue) : undefined;
            resourceInputs["defaultPaymentMethod"] = args?.defaultPaymentMethod;
            resourceInputs["defaultSource"] = args?.defaultSource;
            resourceInputs["defaultTaxRates"] = args?.defaultTaxRates;
            resourceInputs["description"] = args?.description;
            resourceInputs["discounts"] = args?.discounts;
            resourceInputs["dueDate"] = args?.dueDate;
            resourceInputs["effectiveAt"] = args?.effectiveAt;
            resourceInputs["footer"] = args?.footer;
            resourceInputs["fromInvoice"] = args?.fromInvoice;
            resourceInputs["issuer"] = args?.issuer;
            resourceInputs["metadata"] = args?.metadata;
            resourceInputs["number"] = args?.number;
            resourceInputs["onBehalfOf"] = args?.onBehalfOf;
            resourceInputs["paymentSettings"] = args?.paymentSettings;
            resourceInputs["pendingInvoiceItemsBehavior"] = args?.pendingInvoiceItemsBehavior ? pulumi.secret(args.pendingInvoiceItemsBehavior) : undefined;
            resourceInputs["rendering"] = args?.rendering;
            resourceInputs["shippingCost"] = args?.shippingCost;
            resourceInputs["shippingDetails"] = args?.shippingDetails;
            resourceInputs["statementDescriptor"] = args?.statementDescriptor;
            resourceInputs["subscription"] = args?.subscription;
            resourceInputs["transferData"] = args?.transferData ? pulumi.secret(args.transferData) : undefined;
            resourceInputs["accountCountry"] = undefined /*out*/;
            resourceInputs["accountName"] = undefined /*out*/;
            resourceInputs["amountDue"] = undefined /*out*/;
            resourceInputs["amountOverpaid"] = undefined /*out*/;
            resourceInputs["amountPaid"] = undefined /*out*/;
            resourceInputs["amountPaidOffStripe"] = undefined /*out*/;
            resourceInputs["amountRemaining"] = undefined /*out*/;
            resourceInputs["amountShipping"] = undefined /*out*/;
            resourceInputs["application"] = undefined /*out*/;
            resourceInputs["attemptCount"] = undefined /*out*/;
            resourceInputs["attempted"] = undefined /*out*/;
            resourceInputs["billingReason"] = undefined /*out*/;
            resourceInputs["confirmationSecret"] = undefined /*out*/;
            resourceInputs["created"] = undefined /*out*/;
            resourceInputs["customerAddress"] = undefined /*out*/;
            resourceInputs["customerEmail"] = undefined /*out*/;
            resourceInputs["customerName"] = undefined /*out*/;
            resourceInputs["customerPhone"] = undefined /*out*/;
            resourceInputs["customerShipping"] = undefined /*out*/;
            resourceInputs["customerTaxIds"] = undefined /*out*/;
            resourceInputs["endingBalance"] = undefined /*out*/;
            resourceInputs["hostedInvoiceUrl"] = undefined /*out*/;
            resourceInputs["invoicePdf"] = undefined /*out*/;
            resourceInputs["lastFinalizationError"] = undefined /*out*/;
            resourceInputs["latestRevision"] = undefined /*out*/;
            resourceInputs["livemode"] = undefined /*out*/;
            resourceInputs["nextPaymentAttempt"] = undefined /*out*/;
            resourceInputs["object"] = undefined /*out*/;
            resourceInputs["parent"] = undefined /*out*/;
            resourceInputs["periodEnd"] = undefined /*out*/;
            resourceInputs["periodStart"] = undefined /*out*/;
            resourceInputs["postPaymentCreditNotesAmount"] = undefined /*out*/;
            resourceInputs["prePaymentCreditNotesAmount"] = undefined /*out*/;
            resourceInputs["receiptNumber"] = undefined /*out*/;
            resourceInputs["startingBalance"] = undefined /*out*/;
            resourceInputs["status"] = undefined /*out*/;
            resourceInputs["statusTransitions"] = undefined /*out*/;
            resourceInputs["subtotal"] = undefined /*out*/;
            resourceInputs["subtotalExcludingTax"] = undefined /*out*/;
            resourceInputs["testClock"] = undefined /*out*/;
            resourceInputs["thresholdReason"] = undefined /*out*/;
            resourceInputs["total"] = undefined /*out*/;
            resourceInputs["totalDiscountAmounts"] = undefined /*out*/;
            resourceInputs["totalExcludingTax"] = undefined /*out*/;
            resourceInputs["totalPretaxCreditAmounts"] = undefined /*out*/;
            resourceInputs["totalTaxes"] = undefined /*out*/;
            resourceInputs["webhooksDeliveredAt"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["applicationFeeAmount", "daysUntilDue", "pendingInvoiceItemsBehavior", "transferData"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(Invoice.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering Invoice resources.
 */
export interface InvoiceState {
    /**
     * The country of the business associated with this invoice, most often the business creating the invoice.
     */
    accountCountry?: pulumi.Input<string | undefined>;
    /**
     * The public name of the business associated with this invoice, most often the business creating the invoice.
     */
    accountName?: pulumi.Input<string | undefined>;
    /**
     * The account tax IDs associated with the invoice. Only editable when the invoice is a draft.
     */
    accountTaxIds?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * Final amount due at this time for this invoice. If the invoice's total is smaller than the minimum charge amount, for example, or if there is account credit that can be applied to the invoice, the `amountDue` may be 0. If there is a positive `startingBalance` for the invoice (the customer owes money), the `amountDue` will also take that into account. The charge that gets generated for the invoice will be for the amount specified in `amountDue`.
     */
    amountDue?: pulumi.Input<number | undefined>;
    /**
     * Amount that was overpaid on the invoice. The amount overpaid is credited to the customer's credit balance.
     */
    amountOverpaid?: pulumi.Input<number | undefined>;
    /**
     * The amount, in cents (or local equivalent), that was paid.
     */
    amountPaid?: pulumi.Input<number | undefined>;
    /**
     * Amount, in cents (or local equivalent), that was paid on the invoice outside of Stripe.
     */
    amountPaidOffStripe?: pulumi.Input<number | undefined>;
    /**
     * The difference between amountDue and amount_paid, in cents (or local equivalent).
     */
    amountRemaining?: pulumi.Input<number | undefined>;
    /**
     * This is the sum of all the shipping amounts.
     */
    amountShipping?: pulumi.Input<number | undefined>;
    /**
     * ID of the Connect Application that created the invoice.
     */
    application?: pulumi.Input<string | undefined>;
    /**
     * **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * A fee in cents (or local equivalent) that will be applied to the invoice and transferred to the application owner's Stripe account. The request must be made with an OAuth key or the Stripe-Account header in order to take an application fee. For more information, see the application fees [documentation](https://docs.stripe.com/billing/invoices/connect#collecting-fees).
     */
    applicationFeeAmount?: pulumi.Input<number | undefined>;
    /**
     * Number of payment attempts made for this invoice, from the perspective of the payment retry schedule. Any payment attempt counts as the first attempt, and subsequently only automatic retries increment the attempt count. In other words, manual payment attempts after the first attempt do not affect the retry schedule. If a failure is returned with a non-retryable return code, the invoice can no longer be retried unless a new payment method is obtained. Retries will continue to be scheduled, and attemptCount will continue to increment, but retries will only be executed if a new payment method is obtained.
     */
    attemptCount?: pulumi.Input<number | undefined>;
    /**
     * Whether an attempt has been made to pay the invoice. An invoice is not attempted until 1 hour after the `invoice.created` webhook, for example, so you might not want to display that invoice as unpaid to your users.
     */
    attempted?: pulumi.Input<boolean | undefined>;
    /**
     * Controls whether Stripe performs [automatic collection](https://docs.stripe.com/invoicing/integration/automatic-advancement-collection) of the invoice. If `false`, the invoice's state doesn't automatically advance without an explicit action.
     */
    autoAdvance?: pulumi.Input<boolean | undefined>;
    automaticTax?: pulumi.Input<inputs.InvoiceAutomaticTax | undefined>;
    /**
     * The time when this invoice is currently scheduled to be automatically finalized. The field will be `null` if the invoice is not scheduled to finalize in the future. If the invoice is not in the draft state, this field will always be `null` - see `finalizedAt` for the time when an already-finalized invoice was finalized.
     */
    automaticallyFinalizesAt?: pulumi.Input<number | undefined>;
    /**
     * Indicates the reason why the invoice was created.
     *
     * * `manual`: Unrelated to a subscription, for example, created via the invoice editor.
     * * `subscription`: No longer in use. Applies to subscriptions from before May 2018 where no distinction was made between updates, cycles, and thresholds.
     * * `subscriptionCreate`: A new subscription was created.
     * * `subscriptionCycle`: A subscription advanced into a new period.
     * * `subscriptionThreshold`: A subscription reached a billing threshold.
     * * `subscriptionUpdate`: A subscription was updated.
     * * `upcoming`: Reserved for upcoming invoices created through the Create Preview Invoice API or when an `invoice.upcoming` event is generated for an upcoming invoice on a subscription.
     */
    billingReason?: pulumi.Input<string | undefined>;
    /**
     * Either `chargeAutomatically`, or `sendInvoice`. When charging automatically, Stripe will attempt to pay this invoice using the default source attached to the customer. When sending an invoice, Stripe will email this invoice to the customer with payment instructions.
     */
    collectionMethod?: pulumi.Input<string | undefined>;
    /**
     * The confirmation secret associated with this invoice. Currently, this contains the clientSecret of the PaymentIntent that Stripe creates during invoice finalization.
     */
    confirmationSecret?: pulumi.Input<inputs.InvoiceConfirmationSecret | undefined>;
    /**
     * Time at which the object was created. Measured in seconds since the Unix epoch.
     */
    created?: pulumi.Input<number | undefined>;
    /**
     * Three-letter [ISO currency code](https://www.iso.org/iso-4217-currency-codes.html), in lowercase. Must be a [supported currency](https://stripe.com/docs/currencies).
     */
    currency?: pulumi.Input<string | undefined>;
    /**
     * Custom fields displayed on the invoice.
     */
    customFields?: pulumi.Input<pulumi.Input<inputs.InvoiceCustomField>[] | undefined>;
    /**
     * The ID of the customer to bill.
     */
    customer?: pulumi.Input<string | undefined>;
    /**
     * The ID of the account representing the customer to bill.
     */
    customerAccount?: pulumi.Input<string | undefined>;
    /**
     * The customer's address. Until the invoice is finalized, this field will equal `customer.address`. Once the invoice is finalized, this field will no longer be updated.
     */
    customerAddress?: pulumi.Input<inputs.InvoiceCustomerAddress | undefined>;
    /**
     * The customer's email. Until the invoice is finalized, this field will equal `customer.email`. Once the invoice is finalized, this field will no longer be updated.
     */
    customerEmail?: pulumi.Input<string | undefined>;
    /**
     * The customer's name. Until the invoice is finalized, this field will equal `customer.name`. Once the invoice is finalized, this field will no longer be updated.
     */
    customerName?: pulumi.Input<string | undefined>;
    /**
     * The customer's phone number. Until the invoice is finalized, this field will equal `customer.phone`. Once the invoice is finalized, this field will no longer be updated.
     */
    customerPhone?: pulumi.Input<string | undefined>;
    /**
     * The customer's shipping information. Until the invoice is finalized, this field will equal `customer.shipping`. Once the invoice is finalized, this field will no longer be updated.
     */
    customerShipping?: pulumi.Input<inputs.InvoiceCustomerShipping | undefined>;
    /**
     * The customer's tax IDs. Until the invoice is finalized, this field will contain the same tax IDs as `customer.tax_ids`. Once the invoice is finalized, this field will no longer be updated.
     */
    customerTaxIds?: pulumi.Input<pulumi.Input<inputs.InvoiceCustomerTaxId>[] | undefined>;
    /**
     * **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * The number of days from when the invoice is created until it is due. Valid only for invoices where `collection_method=send_invoice`.
     */
    daysUntilDue?: pulumi.Input<number | undefined>;
    /**
     * ID of the default payment method for the invoice. It must belong to the customer associated with the invoice. If not set, defaults to the subscription's default payment method, if any, or to the default payment method in the customer's invoice settings.
     */
    defaultPaymentMethod?: pulumi.Input<string | undefined>;
    /**
     * ID of the default payment source for the invoice. It must belong to the customer associated with the invoice and be in a chargeable state. If not set, defaults to the subscription's default source, if any, or to the customer's default source.
     */
    defaultSource?: pulumi.Input<string | undefined>;
    /**
     * The tax rates applied to this invoice, if any.
     */
    defaultTaxRates?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * An arbitrary string attached to the object. Often useful for displaying to users. Referenced as 'memo' in the Dashboard.
     */
    description?: pulumi.Input<string | undefined>;
    /**
     * The discounts applied to the invoice. Line item discounts are applied before invoice discounts. Use `expand[]=discounts` to expand each discount.
     */
    discounts?: pulumi.Input<pulumi.Input<inputs.InvoiceDiscount>[] | undefined>;
    /**
     * The date on which payment for this invoice is due. This value will be `null` for invoices where `collection_method=charge_automatically`.
     */
    dueDate?: pulumi.Input<number | undefined>;
    /**
     * The date when this invoice is in effect. Same as `finalizedAt` unless overwritten. When defined, this value replaces the system-generated 'Date of issue' printed on the invoice PDF and receipt.
     */
    effectiveAt?: pulumi.Input<number | undefined>;
    /**
     * Ending customer balance after the invoice is finalized. Invoices are finalized approximately an hour after successful webhook delivery or when payment collection is attempted for the invoice. If the invoice has not been finalized yet, this will be null.
     */
    endingBalance?: pulumi.Input<number | undefined>;
    /**
     * Footer displayed on the invoice.
     */
    footer?: pulumi.Input<string | undefined>;
    /**
     * Details of the invoice that was cloned. See the [revision documentation](https://docs.stripe.com/invoicing/invoice-revisions) for more details.
     */
    fromInvoice?: pulumi.Input<inputs.InvoiceFromInvoice | undefined>;
    /**
     * The URL for the hosted invoice page, which allows customers to view and pay an invoice. If the invoice has not been finalized yet, this will be null.
     */
    hostedInvoiceUrl?: pulumi.Input<string | undefined>;
    /**
     * The link to download the PDF for the invoice. If the invoice has not been finalized yet, this will be null.
     */
    invoicePdf?: pulumi.Input<string | undefined>;
    issuer?: pulumi.Input<inputs.InvoiceIssuer | undefined>;
    /**
     * The error encountered during the previous attempt to finalize the invoice. This field is cleared when the invoice is successfully finalized.
     */
    lastFinalizationError?: pulumi.Input<inputs.InvoiceLastFinalizationError | undefined>;
    /**
     * The ID of the most recent non-draft revision of this invoice
     */
    latestRevision?: pulumi.Input<string | undefined>;
    /**
     * If the object exists in live mode, the value is `true`. If the object exists in test mode, the value is `false`.
     */
    livemode?: pulumi.Input<boolean | undefined>;
    /**
     * Set of [key-value pairs](https://docs.stripe.com/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format.
     */
    metadata?: pulumi.Input<{[key: string]: pulumi.Input<string>} | undefined>;
    /**
     * The time at which payment will next be attempted. This value will be `null` for invoices where `collection_method=send_invoice`.
     */
    nextPaymentAttempt?: pulumi.Input<number | undefined>;
    /**
     * A unique, identifying string that appears on emails sent to the customer for this invoice. This starts with the customer's unique invoicePrefix if it is specified.
     */
    number?: pulumi.Input<string | undefined>;
    /**
     * String representing the object's type. Objects of the same type share the same value.
     */
    object?: pulumi.Input<string | undefined>;
    /**
     * The account (if any) for which the funds of the invoice payment are intended. If set, the invoice will be presented with the branding and support information of the specified account. See the [Invoices with Connect](https://docs.stripe.com/billing/invoices/connect) documentation for details.
     */
    onBehalfOf?: pulumi.Input<string | undefined>;
    /**
     * The parent that generated this invoice
     */
    parent?: pulumi.Input<inputs.InvoiceParent | undefined>;
    paymentSettings?: pulumi.Input<inputs.InvoicePaymentSettings | undefined>;
    /**
     * **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * How to handle pending invoice items on invoice creation. Defaults to `exclude` if the parameter is omitted.
     */
    pendingInvoiceItemsBehavior?: pulumi.Input<string | undefined>;
    /**
     * The latest timestamp at which invoice items can be associated with this invoice. Use the [line item period](https://www.terraform.io/api/invoices/line_item#invoice_line_item_object-period) to get the service period for each price.
     */
    periodEnd?: pulumi.Input<number | undefined>;
    /**
     * The earliest timestamp at which invoice items can be associated with this invoice. Use the [line item period](https://www.terraform.io/api/invoices/line_item#invoice_line_item_object-period) to get the service period for each price.
     */
    periodStart?: pulumi.Input<number | undefined>;
    /**
     * Total amount of all post-payment credit notes issued for this invoice.
     */
    postPaymentCreditNotesAmount?: pulumi.Input<number | undefined>;
    /**
     * Total amount of all pre-payment credit notes issued for this invoice.
     */
    prePaymentCreditNotesAmount?: pulumi.Input<number | undefined>;
    /**
     * This is the transaction number that appears on email receipts sent for this invoice.
     */
    receiptNumber?: pulumi.Input<string | undefined>;
    /**
     * The rendering-related settings that control how the invoice is displayed on customer-facing surfaces such as PDF and Hosted Invoice Page.
     */
    rendering?: pulumi.Input<inputs.InvoiceRendering | undefined>;
    /**
     * The details of the cost of shipping, including the ShippingRate applied on the invoice.
     */
    shippingCost?: pulumi.Input<inputs.InvoiceShippingCost | undefined>;
    /**
     * Shipping details for the invoice. The Invoice PDF will use the `shippingDetails` value if it is set, otherwise the PDF will render the shipping address from the customer.
     */
    shippingDetails?: pulumi.Input<inputs.InvoiceShippingDetails | undefined>;
    /**
     * Starting customer balance before the invoice is finalized. If the invoice has not been finalized yet, this will be the current customer balance. For revision invoices, this also includes any customer balance that was applied to the original invoice.
     */
    startingBalance?: pulumi.Input<number | undefined>;
    /**
     * Extra information about an invoice for the customer's credit card statement.
     */
    statementDescriptor?: pulumi.Input<string | undefined>;
    /**
     * The status of the invoice, one of `draft`, `open`, `paid`, `uncollectible`, or `void`. [Learn more](https://docs.stripe.com/billing/invoices/workflow#workflow-overview)
     */
    status?: pulumi.Input<string | undefined>;
    statusTransitions?: pulumi.Input<inputs.InvoiceStatusTransitions | undefined>;
    subscription?: pulumi.Input<string | undefined>;
    /**
     * Total of all subscriptions, invoice items, and prorations on the invoice before any invoice level discount or exclusive tax is applied. Item discounts are already incorporated
     */
    subtotal?: pulumi.Input<number | undefined>;
    /**
     * The integer amount in cents (or local equivalent) representing the subtotal of the invoice before any invoice level discount or tax is applied. Item discounts are already incorporated
     */
    subtotalExcludingTax?: pulumi.Input<number | undefined>;
    /**
     * ID of the test clock this invoice belongs to.
     */
    testClock?: pulumi.Input<string | undefined>;
    thresholdReason?: pulumi.Input<inputs.InvoiceThresholdReason | undefined>;
    /**
     * Total after discounts and taxes.
     */
    total?: pulumi.Input<number | undefined>;
    /**
     * The aggregate amounts calculated per discount across all line items.
     */
    totalDiscountAmounts?: pulumi.Input<pulumi.Input<inputs.InvoiceTotalDiscountAmount>[] | undefined>;
    /**
     * The integer amount in cents (or local equivalent) representing the total amount of the invoice including all discounts but excluding all tax.
     */
    totalExcludingTax?: pulumi.Input<number | undefined>;
    /**
     * Contains pretax credit amounts (ex: discount, credit grants, etc) that apply to this invoice. This is a combined list of totalPretaxCreditAmounts across all invoice line items.
     */
    totalPretaxCreditAmounts?: pulumi.Input<pulumi.Input<inputs.InvoiceTotalPretaxCreditAmount>[] | undefined>;
    /**
     * The aggregate tax information of all line items.
     */
    totalTaxes?: pulumi.Input<pulumi.Input<inputs.InvoiceTotalTax>[] | undefined>;
    /**
     * **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * If specified, the funds from the invoice will be transferred to the destination and the ID of the resulting transfer will be found on the invoice's charge.
     */
    transferData?: pulumi.Input<inputs.InvoiceTransferData | undefined>;
    /**
     * Invoices are automatically paid or sent 1 hour after webhooks are delivered, or until all webhook delivery attempts have [been exhausted](https://docs.stripe.com/billing/webhooks#understand). This field tracks the time when webhooks for this invoice were successfully delivered. If the invoice had no webhooks to deliver, this will be set while the invoice is being created.
     */
    webhooksDeliveredAt?: pulumi.Input<number | undefined>;
}

/**
 * The set of arguments for constructing a Invoice resource.
 */
export interface InvoiceArgs {
    /**
     * The account tax IDs associated with the invoice. Only editable when the invoice is a draft.
     */
    accountTaxIds?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * A fee in cents (or local equivalent) that will be applied to the invoice and transferred to the application owner's Stripe account. The request must be made with an OAuth key or the Stripe-Account header in order to take an application fee. For more information, see the application fees [documentation](https://docs.stripe.com/billing/invoices/connect#collecting-fees).
     */
    applicationFeeAmount?: pulumi.Input<number | undefined>;
    /**
     * Controls whether Stripe performs [automatic collection](https://docs.stripe.com/invoicing/integration/automatic-advancement-collection) of the invoice. If `false`, the invoice's state doesn't automatically advance without an explicit action.
     */
    autoAdvance?: pulumi.Input<boolean | undefined>;
    automaticTax?: pulumi.Input<inputs.InvoiceAutomaticTax | undefined>;
    /**
     * The time when this invoice is currently scheduled to be automatically finalized. The field will be `null` if the invoice is not scheduled to finalize in the future. If the invoice is not in the draft state, this field will always be `null` - see `finalizedAt` for the time when an already-finalized invoice was finalized.
     */
    automaticallyFinalizesAt?: pulumi.Input<number | undefined>;
    /**
     * Either `chargeAutomatically`, or `sendInvoice`. When charging automatically, Stripe will attempt to pay this invoice using the default source attached to the customer. When sending an invoice, Stripe will email this invoice to the customer with payment instructions.
     */
    collectionMethod?: pulumi.Input<string | undefined>;
    /**
     * Three-letter [ISO currency code](https://www.iso.org/iso-4217-currency-codes.html), in lowercase. Must be a [supported currency](https://stripe.com/docs/currencies).
     */
    currency?: pulumi.Input<string | undefined>;
    /**
     * Custom fields displayed on the invoice.
     */
    customFields?: pulumi.Input<pulumi.Input<inputs.InvoiceCustomField>[] | undefined>;
    /**
     * The ID of the customer to bill.
     */
    customer?: pulumi.Input<string | undefined>;
    /**
     * The ID of the account representing the customer to bill.
     */
    customerAccount?: pulumi.Input<string | undefined>;
    /**
     * **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * The number of days from when the invoice is created until it is due. Valid only for invoices where `collection_method=send_invoice`.
     */
    daysUntilDue?: pulumi.Input<number | undefined>;
    /**
     * ID of the default payment method for the invoice. It must belong to the customer associated with the invoice. If not set, defaults to the subscription's default payment method, if any, or to the default payment method in the customer's invoice settings.
     */
    defaultPaymentMethod?: pulumi.Input<string | undefined>;
    /**
     * ID of the default payment source for the invoice. It must belong to the customer associated with the invoice and be in a chargeable state. If not set, defaults to the subscription's default source, if any, or to the customer's default source.
     */
    defaultSource?: pulumi.Input<string | undefined>;
    /**
     * The tax rates applied to this invoice, if any.
     */
    defaultTaxRates?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * An arbitrary string attached to the object. Often useful for displaying to users. Referenced as 'memo' in the Dashboard.
     */
    description?: pulumi.Input<string | undefined>;
    /**
     * The discounts applied to the invoice. Line item discounts are applied before invoice discounts. Use `expand[]=discounts` to expand each discount.
     */
    discounts?: pulumi.Input<pulumi.Input<inputs.InvoiceDiscount>[] | undefined>;
    /**
     * The date on which payment for this invoice is due. This value will be `null` for invoices where `collection_method=charge_automatically`.
     */
    dueDate?: pulumi.Input<number | undefined>;
    /**
     * The date when this invoice is in effect. Same as `finalizedAt` unless overwritten. When defined, this value replaces the system-generated 'Date of issue' printed on the invoice PDF and receipt.
     */
    effectiveAt?: pulumi.Input<number | undefined>;
    /**
     * Footer displayed on the invoice.
     */
    footer?: pulumi.Input<string | undefined>;
    /**
     * Details of the invoice that was cloned. See the [revision documentation](https://docs.stripe.com/invoicing/invoice-revisions) for more details.
     */
    fromInvoice?: pulumi.Input<inputs.InvoiceFromInvoice | undefined>;
    issuer?: pulumi.Input<inputs.InvoiceIssuer | undefined>;
    /**
     * Set of [key-value pairs](https://docs.stripe.com/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format.
     */
    metadata?: pulumi.Input<{[key: string]: pulumi.Input<string>} | undefined>;
    /**
     * A unique, identifying string that appears on emails sent to the customer for this invoice. This starts with the customer's unique invoicePrefix if it is specified.
     */
    number?: pulumi.Input<string | undefined>;
    /**
     * The account (if any) for which the funds of the invoice payment are intended. If set, the invoice will be presented with the branding and support information of the specified account. See the [Invoices with Connect](https://docs.stripe.com/billing/invoices/connect) documentation for details.
     */
    onBehalfOf?: pulumi.Input<string | undefined>;
    paymentSettings?: pulumi.Input<inputs.InvoicePaymentSettings | undefined>;
    /**
     * **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * How to handle pending invoice items on invoice creation. Defaults to `exclude` if the parameter is omitted.
     */
    pendingInvoiceItemsBehavior?: pulumi.Input<string | undefined>;
    /**
     * The rendering-related settings that control how the invoice is displayed on customer-facing surfaces such as PDF and Hosted Invoice Page.
     */
    rendering?: pulumi.Input<inputs.InvoiceRendering | undefined>;
    /**
     * The details of the cost of shipping, including the ShippingRate applied on the invoice.
     */
    shippingCost?: pulumi.Input<inputs.InvoiceShippingCost | undefined>;
    /**
     * Shipping details for the invoice. The Invoice PDF will use the `shippingDetails` value if it is set, otherwise the PDF will render the shipping address from the customer.
     */
    shippingDetails?: pulumi.Input<inputs.InvoiceShippingDetails | undefined>;
    /**
     * Extra information about an invoice for the customer's credit card statement.
     */
    statementDescriptor?: pulumi.Input<string | undefined>;
    subscription?: pulumi.Input<string | undefined>;
    /**
     * **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * If specified, the funds from the invoice will be transferred to the destination and the ID of the resulting transfer will be found on the invoice's charge.
     */
    transferData?: pulumi.Input<inputs.InvoiceTransferData | undefined>;
}
