// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * As a [card issuer](https://docs.stripe.com/issuing), you can dispute transactions that the cardholder does not recognize, suspects to be fraudulent, or has other issues with.
 *
 * Related guide: [Issuing disputes](https://docs.stripe.com/issuing/purchases/disputes)
 */
export class IssuingDispute extends pulumi.CustomResource {
    /**
     * Get an existing IssuingDispute resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: IssuingDisputeState, opts?: pulumi.CustomResourceOptions): IssuingDispute {
        return new IssuingDispute(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'stripe:index/issuingDispute:IssuingDispute';

    /**
     * Returns true if the given object is an instance of IssuingDispute.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is IssuingDispute {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === IssuingDispute.__pulumiType;
    }

    /**
     * Disputed amount in the card's currency and in the [smallest currency unit](https://docs.stripe.com/currencies#zero-decimal). Usually the amount of the `transaction`, but can differ (usually because of currency fluctuation).
     */
    declare public readonly amount: pulumi.Output<number>;
    /**
     * Time at which the object was created. Measured in seconds since the Unix epoch.
     */
    declare public /*out*/ readonly created: pulumi.Output<number>;
    /**
     * The currency the `transaction` was made in.
     */
    declare public /*out*/ readonly currency: pulumi.Output<string>;
    declare public readonly evidence: pulumi.Output<outputs.IssuingDisputeEvidence>;
    /**
     * If the object exists in live mode, the value is `true`. If the object exists in test mode, the value is `false`.
     */
    declare public /*out*/ readonly livemode: pulumi.Output<boolean>;
    /**
     * The enum that describes the dispute loss outcome. If the dispute is not lost, this field will be absent. New enum values may be added in the future, so be sure to handle unknown values.
     */
    declare public /*out*/ readonly lossReason: pulumi.Output<string>;
    /**
     * Set of [key-value pairs](https://docs.stripe.com/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format.
     */
    declare public readonly metadata: pulumi.Output<{[key: string]: string}>;
    /**
     * String representing the object's type. Objects of the same type share the same value.
     */
    declare public /*out*/ readonly object: pulumi.Output<string>;
    /**
     * Current status of the dispute.
     */
    declare public /*out*/ readonly status: pulumi.Output<string>;
    /**
     * The transaction being disputed.
     */
    declare public readonly transaction: pulumi.Output<string>;
    /**
     * [Treasury](https://docs.stripe.com/api/treasury) details related to this dispute if it was created on a [FinancialAccount](https://docs.stripe.com/api/treasury/financial_accounts)
     */
    declare public readonly treasury: pulumi.Output<outputs.IssuingDisputeTreasury>;

    /**
     * Create a IssuingDispute resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: IssuingDisputeArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: IssuingDisputeArgs | IssuingDisputeState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as IssuingDisputeState | undefined;
            resourceInputs["amount"] = state?.amount;
            resourceInputs["created"] = state?.created;
            resourceInputs["currency"] = state?.currency;
            resourceInputs["evidence"] = state?.evidence;
            resourceInputs["livemode"] = state?.livemode;
            resourceInputs["lossReason"] = state?.lossReason;
            resourceInputs["metadata"] = state?.metadata;
            resourceInputs["object"] = state?.object;
            resourceInputs["status"] = state?.status;
            resourceInputs["transaction"] = state?.transaction;
            resourceInputs["treasury"] = state?.treasury;
        } else {
            const args = argsOrState as IssuingDisputeArgs | undefined;
            resourceInputs["amount"] = args?.amount;
            resourceInputs["evidence"] = args?.evidence;
            resourceInputs["metadata"] = args?.metadata;
            resourceInputs["transaction"] = args?.transaction;
            resourceInputs["treasury"] = args?.treasury;
            resourceInputs["created"] = undefined /*out*/;
            resourceInputs["currency"] = undefined /*out*/;
            resourceInputs["livemode"] = undefined /*out*/;
            resourceInputs["lossReason"] = undefined /*out*/;
            resourceInputs["object"] = undefined /*out*/;
            resourceInputs["status"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(IssuingDispute.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering IssuingDispute resources.
 */
export interface IssuingDisputeState {
    /**
     * Disputed amount in the card's currency and in the [smallest currency unit](https://docs.stripe.com/currencies#zero-decimal). Usually the amount of the `transaction`, but can differ (usually because of currency fluctuation).
     */
    amount?: pulumi.Input<number | undefined>;
    /**
     * Time at which the object was created. Measured in seconds since the Unix epoch.
     */
    created?: pulumi.Input<number | undefined>;
    /**
     * The currency the `transaction` was made in.
     */
    currency?: pulumi.Input<string | undefined>;
    evidence?: pulumi.Input<inputs.IssuingDisputeEvidence | undefined>;
    /**
     * If the object exists in live mode, the value is `true`. If the object exists in test mode, the value is `false`.
     */
    livemode?: pulumi.Input<boolean | undefined>;
    /**
     * The enum that describes the dispute loss outcome. If the dispute is not lost, this field will be absent. New enum values may be added in the future, so be sure to handle unknown values.
     */
    lossReason?: pulumi.Input<string | undefined>;
    /**
     * Set of [key-value pairs](https://docs.stripe.com/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format.
     */
    metadata?: pulumi.Input<{[key: string]: pulumi.Input<string>} | undefined>;
    /**
     * String representing the object's type. Objects of the same type share the same value.
     */
    object?: pulumi.Input<string | undefined>;
    /**
     * Current status of the dispute.
     */
    status?: pulumi.Input<string | undefined>;
    /**
     * The transaction being disputed.
     */
    transaction?: pulumi.Input<string | undefined>;
    /**
     * [Treasury](https://docs.stripe.com/api/treasury) details related to this dispute if it was created on a [FinancialAccount](https://docs.stripe.com/api/treasury/financial_accounts)
     */
    treasury?: pulumi.Input<inputs.IssuingDisputeTreasury | undefined>;
}

/**
 * The set of arguments for constructing a IssuingDispute resource.
 */
export interface IssuingDisputeArgs {
    /**
     * Disputed amount in the card's currency and in the [smallest currency unit](https://docs.stripe.com/currencies#zero-decimal). Usually the amount of the `transaction`, but can differ (usually because of currency fluctuation).
     */
    amount?: pulumi.Input<number | undefined>;
    evidence?: pulumi.Input<inputs.IssuingDisputeEvidence | undefined>;
    /**
     * Set of [key-value pairs](https://docs.stripe.com/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format.
     */
    metadata?: pulumi.Input<{[key: string]: pulumi.Input<string>} | undefined>;
    /**
     * The transaction being disputed.
     */
    transaction?: pulumi.Input<string | undefined>;
    /**
     * [Treasury](https://docs.stripe.com/api/treasury) details related to this dispute if it was created on a [FinancialAccount](https://docs.stripe.com/api/treasury/financial_accounts)
     */
    treasury?: pulumi.Input<inputs.IssuingDisputeTreasury | undefined>;
}
