// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * An Issuing `Cardholder` object represents an individual or business entity who is [issued](https://docs.stripe.com/issuing) cards.
 *
 * Related guide: [How to create a cardholder](https://docs.stripe.com/issuing/cards/virtual/issue-cards#create-cardholder)
 */
export class IssuingCardholder extends pulumi.CustomResource {
    /**
     * Get an existing IssuingCardholder resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: IssuingCardholderState, opts?: pulumi.CustomResourceOptions): IssuingCardholder {
        return new IssuingCardholder(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'stripe:index/issuingCardholder:IssuingCardholder';

    /**
     * Returns true if the given object is an instance of IssuingCardholder.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is IssuingCardholder {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === IssuingCardholder.__pulumiType;
    }

    declare public readonly billing: pulumi.Output<outputs.IssuingCardholderBilling>;
    /**
     * Additional information about a `company` cardholder.
     */
    declare public readonly company: pulumi.Output<outputs.IssuingCardholderCompany>;
    /**
     * Time at which the object was created. Measured in seconds since the Unix epoch.
     */
    declare public /*out*/ readonly created: pulumi.Output<number>;
    /**
     * The cardholder's email address.
     */
    declare public readonly email: pulumi.Output<string>;
    /**
     * Additional information about an `individual` cardholder.
     */
    declare public readonly individual: pulumi.Output<outputs.IssuingCardholderIndividual>;
    /**
     * If the object exists in live mode, the value is `true`. If the object exists in test mode, the value is `false`.
     */
    declare public /*out*/ readonly livemode: pulumi.Output<boolean>;
    /**
     * Set of [key-value pairs](https://docs.stripe.com/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format.
     */
    declare public readonly metadata: pulumi.Output<{[key: string]: string}>;
    /**
     * The cardholder's name. This will be printed on cards issued to them.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * String representing the object's type. Objects of the same type share the same value.
     */
    declare public /*out*/ readonly object: pulumi.Output<string>;
    /**
     * The cardholder's phone number. This is required for all cardholders who will be creating EU cards. See the [3D Secure documentation](https://docs.stripe.com/issuing/3d-secure#when-is-3d-secure-applied) for more details.
     */
    declare public readonly phoneNumber: pulumi.Output<string>;
    /**
     * The cardholder’s preferred locales (languages), ordered by preference. Locales can be `da`, `de`, `en`, `es`, `fr`, `it`, `pl`, or `sv`.
     * This changes the language of the [3D Secure flow](https://docs.stripe.com/issuing/3d-secure) and one-time password messages sent to the cardholder.
     */
    declare public readonly preferredLocales: pulumi.Output<string[]>;
    declare public /*out*/ readonly requirements: pulumi.Output<outputs.IssuingCardholderRequirements>;
    /**
     * Rules that control spending across this cardholder's cards. Refer to our [documentation](https://docs.stripe.com/issuing/controls/spending-controls) for more details.
     */
    declare public readonly spendingControls: pulumi.Output<outputs.IssuingCardholderSpendingControls>;
    /**
     * Specifies whether to permit authorizations on this cardholder's cards.
     */
    declare public readonly status: pulumi.Output<string>;
    /**
     * One of `individual` or `company`. See [Choose a cardholder type](https://docs.stripe.com/issuing/other/choose-cardholder) for more details.
     */
    declare public readonly type: pulumi.Output<string>;

    /**
     * Create a IssuingCardholder resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: IssuingCardholderArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: IssuingCardholderArgs | IssuingCardholderState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as IssuingCardholderState | undefined;
            resourceInputs["billing"] = state?.billing;
            resourceInputs["company"] = state?.company;
            resourceInputs["created"] = state?.created;
            resourceInputs["email"] = state?.email;
            resourceInputs["individual"] = state?.individual;
            resourceInputs["livemode"] = state?.livemode;
            resourceInputs["metadata"] = state?.metadata;
            resourceInputs["name"] = state?.name;
            resourceInputs["object"] = state?.object;
            resourceInputs["phoneNumber"] = state?.phoneNumber;
            resourceInputs["preferredLocales"] = state?.preferredLocales;
            resourceInputs["requirements"] = state?.requirements;
            resourceInputs["spendingControls"] = state?.spendingControls;
            resourceInputs["status"] = state?.status;
            resourceInputs["type"] = state?.type;
        } else {
            const args = argsOrState as IssuingCardholderArgs | undefined;
            if (args?.billing === undefined && !opts.urn) {
                throw new Error("Missing required property 'billing'");
            }
            resourceInputs["billing"] = args?.billing;
            resourceInputs["company"] = args?.company;
            resourceInputs["email"] = args?.email;
            resourceInputs["individual"] = args?.individual;
            resourceInputs["metadata"] = args?.metadata;
            resourceInputs["name"] = args?.name;
            resourceInputs["phoneNumber"] = args?.phoneNumber;
            resourceInputs["preferredLocales"] = args?.preferredLocales;
            resourceInputs["spendingControls"] = args?.spendingControls;
            resourceInputs["status"] = args?.status;
            resourceInputs["type"] = args?.type;
            resourceInputs["created"] = undefined /*out*/;
            resourceInputs["livemode"] = undefined /*out*/;
            resourceInputs["object"] = undefined /*out*/;
            resourceInputs["requirements"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(IssuingCardholder.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering IssuingCardholder resources.
 */
export interface IssuingCardholderState {
    billing?: pulumi.Input<inputs.IssuingCardholderBilling | undefined>;
    /**
     * Additional information about a `company` cardholder.
     */
    company?: pulumi.Input<inputs.IssuingCardholderCompany | undefined>;
    /**
     * Time at which the object was created. Measured in seconds since the Unix epoch.
     */
    created?: pulumi.Input<number | undefined>;
    /**
     * The cardholder's email address.
     */
    email?: pulumi.Input<string | undefined>;
    /**
     * Additional information about an `individual` cardholder.
     */
    individual?: pulumi.Input<inputs.IssuingCardholderIndividual | undefined>;
    /**
     * If the object exists in live mode, the value is `true`. If the object exists in test mode, the value is `false`.
     */
    livemode?: pulumi.Input<boolean | undefined>;
    /**
     * Set of [key-value pairs](https://docs.stripe.com/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format.
     */
    metadata?: pulumi.Input<{[key: string]: pulumi.Input<string>} | undefined>;
    /**
     * The cardholder's name. This will be printed on cards issued to them.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * String representing the object's type. Objects of the same type share the same value.
     */
    object?: pulumi.Input<string | undefined>;
    /**
     * The cardholder's phone number. This is required for all cardholders who will be creating EU cards. See the [3D Secure documentation](https://docs.stripe.com/issuing/3d-secure#when-is-3d-secure-applied) for more details.
     */
    phoneNumber?: pulumi.Input<string | undefined>;
    /**
     * The cardholder’s preferred locales (languages), ordered by preference. Locales can be `da`, `de`, `en`, `es`, `fr`, `it`, `pl`, or `sv`.
     * This changes the language of the [3D Secure flow](https://docs.stripe.com/issuing/3d-secure) and one-time password messages sent to the cardholder.
     */
    preferredLocales?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    requirements?: pulumi.Input<inputs.IssuingCardholderRequirements | undefined>;
    /**
     * Rules that control spending across this cardholder's cards. Refer to our [documentation](https://docs.stripe.com/issuing/controls/spending-controls) for more details.
     */
    spendingControls?: pulumi.Input<inputs.IssuingCardholderSpendingControls | undefined>;
    /**
     * Specifies whether to permit authorizations on this cardholder's cards.
     */
    status?: pulumi.Input<string | undefined>;
    /**
     * One of `individual` or `company`. See [Choose a cardholder type](https://docs.stripe.com/issuing/other/choose-cardholder) for more details.
     */
    type?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a IssuingCardholder resource.
 */
export interface IssuingCardholderArgs {
    billing: pulumi.Input<inputs.IssuingCardholderBilling>;
    /**
     * Additional information about a `company` cardholder.
     */
    company?: pulumi.Input<inputs.IssuingCardholderCompany | undefined>;
    /**
     * The cardholder's email address.
     */
    email?: pulumi.Input<string | undefined>;
    /**
     * Additional information about an `individual` cardholder.
     */
    individual?: pulumi.Input<inputs.IssuingCardholderIndividual | undefined>;
    /**
     * Set of [key-value pairs](https://docs.stripe.com/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format.
     */
    metadata?: pulumi.Input<{[key: string]: pulumi.Input<string>} | undefined>;
    /**
     * The cardholder's name. This will be printed on cards issued to them.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * The cardholder's phone number. This is required for all cardholders who will be creating EU cards. See the [3D Secure documentation](https://docs.stripe.com/issuing/3d-secure#when-is-3d-secure-applied) for more details.
     */
    phoneNumber?: pulumi.Input<string | undefined>;
    /**
     * The cardholder’s preferred locales (languages), ordered by preference. Locales can be `da`, `de`, `en`, `es`, `fr`, `it`, `pl`, or `sv`.
     * This changes the language of the [3D Secure flow](https://docs.stripe.com/issuing/3d-secure) and one-time password messages sent to the cardholder.
     */
    preferredLocales?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * Rules that control spending across this cardholder's cards. Refer to our [documentation](https://docs.stripe.com/issuing/controls/spending-controls) for more details.
     */
    spendingControls?: pulumi.Input<inputs.IssuingCardholderSpendingControls | undefined>;
    /**
     * Specifies whether to permit authorizations on this cardholder's cards.
     */
    status?: pulumi.Input<string | undefined>;
    /**
     * One of `individual` or `company`. See [Choose a cardholder type](https://docs.stripe.com/issuing/other/choose-cardholder) for more details.
     */
    type?: pulumi.Input<string | undefined>;
}
