// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * Prices define the unit cost, currency, and (optional) billing cycle for both recurring and one-time purchases of products. [Products](https://stripe.com/docs/api#products) help you track inventory or provisioning, and prices help you track payment terms. Different physical goods or levels of service should be represented by products, and pricing options should be represented by prices. This approach lets you change prices without having to change your provisioning scheme. For example, you might have a single \"gold\" product that has prices for $10/month, $100/year, and €9 once. Related guides: [Set up a subscription](https://stripe.com/docs/billing/subscriptions/set-up-subscription), [create an invoice](https://stripe.com/docs/billing/invoices/create), and more about [products and prices](https://stripe.com/docs/products-prices/overview).
 */
export class Price extends pulumi.CustomResource {
    /**
     * Get an existing Price resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: PriceState, opts?: pulumi.CustomResourceOptions): Price {
        return new Price(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'stripe:index/price:Price';

    /**
     * Returns true if the given object is an instance of Price.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Price {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Price.__pulumiType;
    }

    /**
     * Whether the price can be used for new purchases. Defaults to `true`.
     */
    declare public readonly active: pulumi.Output<boolean | undefined>;
    /**
     * Describes how to compute the price per period. Either `perUnit` or `tiered`. `perUnit` indicates that the fixed amount (specified in `unitAmount` or `unitAmountDecimal`) will be charged per unit in `quantity` (for prices with `usage_type=licensed`), or per unit of total usage (for prices with `usage_type=metered`). `tiered` indicates that the unit pricing will be computed using a tiering strategy as defined using the `tiers` and `tiersMode` attributes.
     */
    declare public readonly billingScheme: pulumi.Output<string>;
    /**
     * Three-letter [ISO currency code](https://www.iso.org/iso-4217-currency-codes.html), in lowercase. Must be a [supported currency](https://stripe.com/docs/currencies).
     */
    declare public readonly currency: pulumi.Output<string>;
    /**
     * Prices defined in each available currency option. Each key must be a three-letter [ISO currency code](https://www.iso.org/iso-4217-currency-codes.html) and a [supported currency](https://stripe.com/docs/currencies).
     */
    declare public readonly currencyOptions: pulumi.Output<outputs.PriceCurrencyOption[]>;
    /**
     * When set, provides configuration for the amount to be adjusted by the customer during Checkout Sessions and Payment Links.
     */
    declare public readonly customUnitAmount: pulumi.Output<outputs.PriceCustomUnitAmount | undefined>;
    /**
     * A lookup key used to retrieve prices dynamically from a static string. This may be up to 200 characters.
     */
    declare public readonly lookupKey: pulumi.Output<string>;
    /**
     * Set of [key-value pairs](https://stripe.com/docs/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format. Individual keys can be unset by posting an empty value to them. All keys can be unset by posting an empty value to `metadata`.
     */
    declare public readonly metadata: pulumi.Output<{[key: string]: string}>;
    /**
     * A brief description of the price, hidden from customers.
     */
    declare public readonly nickname: pulumi.Output<string>;
    /**
     * The ID of the [Product](https://docs.stripe.com/api/products) that this [Price](https://docs.stripe.com/api/prices) will belong to.
     */
    declare public readonly product: pulumi.Output<string>;
    /**
     * These fields can be used to create a new product that this price will belong to.
     */
    declare public readonly productData: pulumi.Output<outputs.PriceProductData | undefined>;
    /**
     * The recurring components of a price such as `interval` and `usageType`.
     */
    declare public readonly recurring: pulumi.Output<outputs.PriceRecurring | undefined>;
    /**
     * Only required if a [default tax behavior](https://stripe.com/docs/tax/products-prices-tax-categories-tax-behavior#setting-a-default-tax-behavior-(recommended)) was not provided in the Stripe Tax settings. Specifies whether the price is considered inclusive of taxes or exclusive of taxes. One of `inclusive`, `exclusive`, or `unspecified`. Once specified as either `inclusive` or `exclusive`, it cannot be changed.
     */
    declare public readonly taxBehavior: pulumi.Output<string>;
    /**
     * Each element represents a pricing tier. This parameter requires `billingScheme` to be set to `tiered`. See also the documentation for `billingScheme`.
     */
    declare public readonly tiers: pulumi.Output<outputs.PriceTier[] | undefined>;
    /**
     * Defines if the tiering price should be `graduated` or `volume` based. In `volume`-based tiering, the maximum quantity within a period determines the per unit price, in `graduated` tiering pricing can successively change as the quantity grows.
     */
    declare public readonly tiersMode: pulumi.Output<string>;
    /**
     * One of `oneTime` or `recurring` depending on whether the price is for a one-time purchase or a recurring (subscription) purchase.
     */
    declare public /*out*/ readonly type: pulumi.Output<string>;
    /**
     * A positive integer in cents (or local equivalent) (or 0 for a free price) representing how much to charge. One of `unitAmount`, `unitAmountDecimal`, or `customUnitAmount` is required, unless `billing_scheme=tiered`.
     */
    declare public readonly unitAmount: pulumi.Output<number>;
    /**
     * Same as `unitAmount`, but accepts a decimal value in cents (or local equivalent) with at most 12 decimal places. Only one of `unitAmount` and `unitAmountDecimal` can be set.
     */
    declare public readonly unitAmountDecimal: pulumi.Output<string>;

    /**
     * Create a Price resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: PriceArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: PriceArgs | PriceState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as PriceState | undefined;
            resourceInputs["active"] = state?.active;
            resourceInputs["billingScheme"] = state?.billingScheme;
            resourceInputs["currency"] = state?.currency;
            resourceInputs["currencyOptions"] = state?.currencyOptions;
            resourceInputs["customUnitAmount"] = state?.customUnitAmount;
            resourceInputs["lookupKey"] = state?.lookupKey;
            resourceInputs["metadata"] = state?.metadata;
            resourceInputs["nickname"] = state?.nickname;
            resourceInputs["product"] = state?.product;
            resourceInputs["productData"] = state?.productData;
            resourceInputs["recurring"] = state?.recurring;
            resourceInputs["taxBehavior"] = state?.taxBehavior;
            resourceInputs["tiers"] = state?.tiers;
            resourceInputs["tiersMode"] = state?.tiersMode;
            resourceInputs["type"] = state?.type;
            resourceInputs["unitAmount"] = state?.unitAmount;
            resourceInputs["unitAmountDecimal"] = state?.unitAmountDecimal;
        } else {
            const args = argsOrState as PriceArgs | undefined;
            if (args?.currency === undefined && !opts.urn) {
                throw new Error("Missing required property 'currency'");
            }
            resourceInputs["active"] = args?.active;
            resourceInputs["billingScheme"] = args?.billingScheme;
            resourceInputs["currency"] = args?.currency;
            resourceInputs["currencyOptions"] = args?.currencyOptions;
            resourceInputs["customUnitAmount"] = args?.customUnitAmount;
            resourceInputs["lookupKey"] = args?.lookupKey;
            resourceInputs["metadata"] = args?.metadata;
            resourceInputs["nickname"] = args?.nickname;
            resourceInputs["product"] = args?.product;
            resourceInputs["productData"] = args?.productData;
            resourceInputs["recurring"] = args?.recurring;
            resourceInputs["taxBehavior"] = args?.taxBehavior;
            resourceInputs["tiers"] = args?.tiers;
            resourceInputs["tiersMode"] = args?.tiersMode;
            resourceInputs["unitAmount"] = args?.unitAmount;
            resourceInputs["unitAmountDecimal"] = args?.unitAmountDecimal;
            resourceInputs["type"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Price.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering Price resources.
 */
export interface PriceState {
    /**
     * Whether the price can be used for new purchases. Defaults to `true`.
     */
    active?: pulumi.Input<boolean | undefined>;
    /**
     * Describes how to compute the price per period. Either `perUnit` or `tiered`. `perUnit` indicates that the fixed amount (specified in `unitAmount` or `unitAmountDecimal`) will be charged per unit in `quantity` (for prices with `usage_type=licensed`), or per unit of total usage (for prices with `usage_type=metered`). `tiered` indicates that the unit pricing will be computed using a tiering strategy as defined using the `tiers` and `tiersMode` attributes.
     */
    billingScheme?: pulumi.Input<string | undefined>;
    /**
     * Three-letter [ISO currency code](https://www.iso.org/iso-4217-currency-codes.html), in lowercase. Must be a [supported currency](https://stripe.com/docs/currencies).
     */
    currency?: pulumi.Input<string | undefined>;
    /**
     * Prices defined in each available currency option. Each key must be a three-letter [ISO currency code](https://www.iso.org/iso-4217-currency-codes.html) and a [supported currency](https://stripe.com/docs/currencies).
     */
    currencyOptions?: pulumi.Input<pulumi.Input<inputs.PriceCurrencyOption>[] | undefined>;
    /**
     * When set, provides configuration for the amount to be adjusted by the customer during Checkout Sessions and Payment Links.
     */
    customUnitAmount?: pulumi.Input<inputs.PriceCustomUnitAmount | undefined>;
    /**
     * A lookup key used to retrieve prices dynamically from a static string. This may be up to 200 characters.
     */
    lookupKey?: pulumi.Input<string | undefined>;
    /**
     * Set of [key-value pairs](https://stripe.com/docs/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format. Individual keys can be unset by posting an empty value to them. All keys can be unset by posting an empty value to `metadata`.
     */
    metadata?: pulumi.Input<{[key: string]: pulumi.Input<string>} | undefined>;
    /**
     * A brief description of the price, hidden from customers.
     */
    nickname?: pulumi.Input<string | undefined>;
    /**
     * The ID of the [Product](https://docs.stripe.com/api/products) that this [Price](https://docs.stripe.com/api/prices) will belong to.
     */
    product?: pulumi.Input<string | undefined>;
    /**
     * These fields can be used to create a new product that this price will belong to.
     */
    productData?: pulumi.Input<inputs.PriceProductData | undefined>;
    /**
     * The recurring components of a price such as `interval` and `usageType`.
     */
    recurring?: pulumi.Input<inputs.PriceRecurring | undefined>;
    /**
     * Only required if a [default tax behavior](https://stripe.com/docs/tax/products-prices-tax-categories-tax-behavior#setting-a-default-tax-behavior-(recommended)) was not provided in the Stripe Tax settings. Specifies whether the price is considered inclusive of taxes or exclusive of taxes. One of `inclusive`, `exclusive`, or `unspecified`. Once specified as either `inclusive` or `exclusive`, it cannot be changed.
     */
    taxBehavior?: pulumi.Input<string | undefined>;
    /**
     * Each element represents a pricing tier. This parameter requires `billingScheme` to be set to `tiered`. See also the documentation for `billingScheme`.
     */
    tiers?: pulumi.Input<pulumi.Input<inputs.PriceTier>[] | undefined>;
    /**
     * Defines if the tiering price should be `graduated` or `volume` based. In `volume`-based tiering, the maximum quantity within a period determines the per unit price, in `graduated` tiering pricing can successively change as the quantity grows.
     */
    tiersMode?: pulumi.Input<string | undefined>;
    /**
     * One of `oneTime` or `recurring` depending on whether the price is for a one-time purchase or a recurring (subscription) purchase.
     */
    type?: pulumi.Input<string | undefined>;
    /**
     * A positive integer in cents (or local equivalent) (or 0 for a free price) representing how much to charge. One of `unitAmount`, `unitAmountDecimal`, or `customUnitAmount` is required, unless `billing_scheme=tiered`.
     */
    unitAmount?: pulumi.Input<number | undefined>;
    /**
     * Same as `unitAmount`, but accepts a decimal value in cents (or local equivalent) with at most 12 decimal places. Only one of `unitAmount` and `unitAmountDecimal` can be set.
     */
    unitAmountDecimal?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a Price resource.
 */
export interface PriceArgs {
    /**
     * Whether the price can be used for new purchases. Defaults to `true`.
     */
    active?: pulumi.Input<boolean | undefined>;
    /**
     * Describes how to compute the price per period. Either `perUnit` or `tiered`. `perUnit` indicates that the fixed amount (specified in `unitAmount` or `unitAmountDecimal`) will be charged per unit in `quantity` (for prices with `usage_type=licensed`), or per unit of total usage (for prices with `usage_type=metered`). `tiered` indicates that the unit pricing will be computed using a tiering strategy as defined using the `tiers` and `tiersMode` attributes.
     */
    billingScheme?: pulumi.Input<string | undefined>;
    /**
     * Three-letter [ISO currency code](https://www.iso.org/iso-4217-currency-codes.html), in lowercase. Must be a [supported currency](https://stripe.com/docs/currencies).
     */
    currency: pulumi.Input<string>;
    /**
     * Prices defined in each available currency option. Each key must be a three-letter [ISO currency code](https://www.iso.org/iso-4217-currency-codes.html) and a [supported currency](https://stripe.com/docs/currencies).
     */
    currencyOptions?: pulumi.Input<pulumi.Input<inputs.PriceCurrencyOption>[] | undefined>;
    /**
     * When set, provides configuration for the amount to be adjusted by the customer during Checkout Sessions and Payment Links.
     */
    customUnitAmount?: pulumi.Input<inputs.PriceCustomUnitAmount | undefined>;
    /**
     * A lookup key used to retrieve prices dynamically from a static string. This may be up to 200 characters.
     */
    lookupKey?: pulumi.Input<string | undefined>;
    /**
     * Set of [key-value pairs](https://stripe.com/docs/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format. Individual keys can be unset by posting an empty value to them. All keys can be unset by posting an empty value to `metadata`.
     */
    metadata?: pulumi.Input<{[key: string]: pulumi.Input<string>} | undefined>;
    /**
     * A brief description of the price, hidden from customers.
     */
    nickname?: pulumi.Input<string | undefined>;
    /**
     * The ID of the [Product](https://docs.stripe.com/api/products) that this [Price](https://docs.stripe.com/api/prices) will belong to.
     */
    product?: pulumi.Input<string | undefined>;
    /**
     * These fields can be used to create a new product that this price will belong to.
     */
    productData?: pulumi.Input<inputs.PriceProductData | undefined>;
    /**
     * The recurring components of a price such as `interval` and `usageType`.
     */
    recurring?: pulumi.Input<inputs.PriceRecurring | undefined>;
    /**
     * Only required if a [default tax behavior](https://stripe.com/docs/tax/products-prices-tax-categories-tax-behavior#setting-a-default-tax-behavior-(recommended)) was not provided in the Stripe Tax settings. Specifies whether the price is considered inclusive of taxes or exclusive of taxes. One of `inclusive`, `exclusive`, or `unspecified`. Once specified as either `inclusive` or `exclusive`, it cannot be changed.
     */
    taxBehavior?: pulumi.Input<string | undefined>;
    /**
     * Each element represents a pricing tier. This parameter requires `billingScheme` to be set to `tiered`. See also the documentation for `billingScheme`.
     */
    tiers?: pulumi.Input<pulumi.Input<inputs.PriceTier>[] | undefined>;
    /**
     * Defines if the tiering price should be `graduated` or `volume` based. In `volume`-based tiering, the maximum quantity within a period determines the per unit price, in `graduated` tiering pricing can successively change as the quantity grows.
     */
    tiersMode?: pulumi.Input<string | undefined>;
    /**
     * A positive integer in cents (or local equivalent) (or 0 for a free price) representing how much to charge. One of `unitAmount`, `unitAmountDecimal`, or `customUnitAmount` is required, unless `billing_scheme=tiered`.
     */
    unitAmount?: pulumi.Input<number | undefined>;
    /**
     * Same as `unitAmount`, but accepts a decimal value in cents (or local equivalent) with at most 12 decimal places. Only one of `unitAmount` and `unitAmountDecimal` can be set.
     */
    unitAmountDecimal?: pulumi.Input<string | undefined>;
}
