// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * A SetupIntent guides you through the process of setting up and saving a customer's payment credentials for future payments.
 * For example, you can use a SetupIntent to set up and save your customer's card without immediately collecting a payment.
 * Later, you can use [PaymentIntents](https://api.stripe.com#payment_intents) to drive the payment flow.
 *
 * Create a SetupIntent when you're ready to collect your customer's payment credentials.
 * Don't maintain long-lived, unconfirmed SetupIntents because they might not be valid.
 * The SetupIntent transitions through multiple [statuses](https://docs.stripe.com/payments/intents#intent-statuses) as it guides
 * you through the setup process.
 *
 * Successful SetupIntents result in payment credentials that are optimized for future payments.
 * For example, cardholders in [certain regions](https://stripe.com/guides/strong-customer-authentication) might need to be run through
 * [Strong Customer Authentication](https://docs.stripe.com/strong-customer-authentication) during payment method collection
 * to streamline later [off-session payments](https://docs.stripe.com/payments/setup-intents).
 * If you use the SetupIntent with a [Customer](https://api.stripe.com#setup_intent_object-customer),
 * it automatically attaches the resulting payment method to that Customer after successful setup.
 * We recommend using SetupIntents or [setupFutureUsage](https://api.stripe.com#payment_intent_object-setup_future_usage) on
 * PaymentIntents to save payment methods to prevent saving invalid or unoptimized payment methods.
 *
 * By using SetupIntents, you can reduce friction for your customers, even as regulations change over time.
 *
 * Related guide: [Setup Intents API](https://docs.stripe.com/payments/setup-intents)
 */
export class SetupIntent extends pulumi.CustomResource {
    /**
     * Get an existing SetupIntent resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: SetupIntentState, opts?: pulumi.CustomResourceOptions): SetupIntent {
        return new SetupIntent(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'stripe:index/setupIntent:SetupIntent';

    /**
     * Returns true if the given object is an instance of SetupIntent.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is SetupIntent {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === SetupIntent.__pulumiType;
    }

    /**
     * ID of the Connect application that created the SetupIntent.
     */
    declare public /*out*/ readonly application: pulumi.Output<string>;
    /**
     * If present, the SetupIntent's payment method will be attached to the in-context Stripe Account.
     *
     * It can only be used for this Stripe Account’s own money movement flows like InboundTransfer and OutboundTransfers. It cannot be set to true when setting up a PaymentMethod for a Customer, and defaults to false when attaching a PaymentMethod to a Customer.
     */
    declare public readonly attachToSelf: pulumi.Output<boolean>;
    /**
     * Settings for dynamic payment methods compatible with this Setup Intent
     */
    declare public readonly automaticPaymentMethods: pulumi.Output<outputs.SetupIntentAutomaticPaymentMethods>;
    /**
     * Reason for cancellation of this SetupIntent, one of `abandoned`, `requestedByCustomer`, or `duplicate`.
     */
    declare public /*out*/ readonly cancellationReason: pulumi.Output<string>;
    /**
     * The client secret of this SetupIntent. Used for client-side retrieval using a publishable key.
     *
     * The client secret can be used to complete payment setup from your frontend. It should not be stored, logged, or exposed to anyone other than the customer. Make sure that you have TLS enabled on any page that includes the client secret.
     */
    declare public /*out*/ readonly clientSecret: pulumi.Output<string>;
    /**
     * **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * Set to `true` to attempt to confirm this SetupIntent immediately. This parameter defaults to `false`. If a card is the attached payment method, you can provide a `returnUrl` in case further authentication is necessary.
     */
    declare public readonly confirm: pulumi.Output<boolean | undefined>;
    /**
     * **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * ID of the ConfirmationToken used to confirm this SetupIntent.
     *
     * If the provided ConfirmationToken contains properties that are also being provided in this request, such as `paymentMethod`, then the values in this request will take precedence.
     */
    declare public readonly confirmationToken: pulumi.Output<string | undefined>;
    /**
     * Time at which the object was created. Measured in seconds since the Unix epoch.
     */
    declare public /*out*/ readonly created: pulumi.Output<number>;
    /**
     * ID of the Customer this SetupIntent belongs to, if one exists.
     *
     * If present, the SetupIntent's payment method will be attached to the Customer on successful setup. Payment methods attached to other Customers cannot be used with this SetupIntent.
     */
    declare public readonly customer: pulumi.Output<string>;
    /**
     * ID of the Account this SetupIntent belongs to, if one exists.
     *
     * If present, the SetupIntent's payment method will be attached to the Account on successful setup. Payment methods attached to other Accounts cannot be used with this SetupIntent.
     */
    declare public readonly customerAccount: pulumi.Output<string>;
    /**
     * An arbitrary string attached to the object. Often useful for displaying to users.
     */
    declare public readonly description: pulumi.Output<string>;
    /**
     * Payment method types that are excluded from this SetupIntent.
     */
    declare public readonly excludedPaymentMethodTypes: pulumi.Output<string[]>;
    /**
     * Indicates the directions of money movement for which this payment method is intended to be used.
     *
     * Include `inbound` if you intend to use the payment method as the origin to pull funds from. Include `outbound` if you intend to use the payment method as the destination to send funds to. You can include both if you intend to use the payment method for both purposes.
     */
    declare public readonly flowDirections: pulumi.Output<string[]>;
    /**
     * The error encountered in the previous SetupIntent confirmation.
     */
    declare public /*out*/ readonly lastSetupError: pulumi.Output<outputs.SetupIntentLastSetupError>;
    /**
     * The most recent SetupAttempt for this SetupIntent.
     */
    declare public /*out*/ readonly latestAttempt: pulumi.Output<string>;
    /**
     * If the object exists in live mode, the value is `true`. If the object exists in test mode, the value is `false`.
     */
    declare public /*out*/ readonly livemode: pulumi.Output<boolean>;
    declare public /*out*/ readonly managedPayments: pulumi.Output<outputs.SetupIntentManagedPayments>;
    /**
     * ID of the multi use Mandate generated by the SetupIntent.
     */
    declare public /*out*/ readonly mandate: pulumi.Output<string>;
    /**
     * **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * This hash contains details about the mandate to create. This parameter can only be used with [`confirm=true`](https://docs.stripe.com/api/setup_intents/create#create_setup_intent-confirm).
     */
    declare public readonly mandateData: pulumi.Output<outputs.SetupIntentMandateData | undefined>;
    /**
     * Set of [key-value pairs](https://docs.stripe.com/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format.
     */
    declare public readonly metadata: pulumi.Output<{[key: string]: string}>;
    /**
     * If present, this property tells you what actions you need to take in order for your customer to continue payment setup.
     */
    declare public /*out*/ readonly nextAction: pulumi.Output<outputs.SetupIntentNextAction>;
    /**
     * String representing the object's type. Objects of the same type share the same value.
     */
    declare public /*out*/ readonly object: pulumi.Output<string>;
    /**
     * The account (if any) for which the setup is intended.
     */
    declare public readonly onBehalfOf: pulumi.Output<string>;
    /**
     * ID of the payment method used with this SetupIntent. If the payment method is `cardPresent` and isn't a digital wallet, then the [generatedCard](https://docs.stripe.com/api/setup_attempts/object#setup_attempt_object-payment_method_details-card_present-generated_card) associated with the `latestAttempt` is attached to the Customer instead.
     */
    declare public readonly paymentMethod: pulumi.Output<string>;
    /**
     * **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * The ID of the [payment method configuration](https://docs.stripe.com/api/payment_method_configurations) to use with this SetupIntent.
     */
    declare public readonly paymentMethodConfiguration: pulumi.Output<string | undefined>;
    /**
     * Information about the [payment method configuration](https://docs.stripe.com/api/payment_method_configurations) used for this Setup Intent.
     */
    declare public /*out*/ readonly paymentMethodConfigurationDetails: pulumi.Output<outputs.SetupIntentPaymentMethodConfigurationDetails>;
    /**
     * **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * When included, this hash creates a PaymentMethod that is set as the [`paymentMethod`](https://docs.stripe.com/api/setup_intents/object#setup_intent_object-payment_method)
     * value in the SetupIntent.
     */
    declare public readonly paymentMethodData: pulumi.Output<outputs.SetupIntentPaymentMethodData | undefined>;
    /**
     * Payment method-specific configuration for this SetupIntent.
     */
    declare public readonly paymentMethodOptions: pulumi.Output<outputs.SetupIntentPaymentMethodOptions>;
    /**
     * The list of payment method types (e.g. card) that this SetupIntent is allowed to set up. A list of valid payment method types can be found [here](https://docs.stripe.com/api/payment_methods/object#payment_method_object-type).
     */
    declare public readonly paymentMethodTypes: pulumi.Output<string[]>;
    /**
     * **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * The URL to redirect your customer back to after they authenticate or cancel their payment on the payment method's app or site. To redirect to a mobile application, you can alternatively supply an application URI scheme. This parameter can only be used with [`confirm=true`](https://docs.stripe.com/api/setup_intents/create#create_setup_intent-confirm).
     */
    declare public readonly returnUrl: pulumi.Output<string | undefined>;
    /**
     * **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * If you populate this hash, this SetupIntent generates a `singleUse` mandate after successful completion.
     *
     * Single-use mandates are only valid for the following payment methods: `acssDebit`, `alipay`, `auBecsDebit`, `bacsDebit`, `bancontact`, `boleto`, `ideal`, `link`, `sepaDebit`, and `usBankAccount`.
     */
    declare public readonly singleUse: pulumi.Output<outputs.SetupIntentSingleUse | undefined>;
    /**
     * ID of the singleUse Mandate generated by the SetupIntent.
     */
    declare public /*out*/ readonly singleUseMandate: pulumi.Output<string>;
    /**
     * [Status](https://docs.stripe.com/payments/intents#intent-statuses) of this SetupIntent, one of `requiresPaymentMethod`, `requiresConfirmation`, `requiresAction`, `processing`, `canceled`, or `succeeded`.
     */
    declare public /*out*/ readonly status: pulumi.Output<string>;
    /**
     * Indicates how the payment method is intended to be used in the future.
     *
     * Use `onSession` if you intend to only reuse the payment method when the customer is in your checkout flow. Use `offSession` if your customer may or may not be in your checkout flow. If not provided, this value defaults to `offSession`.
     */
    declare public readonly usage: pulumi.Output<string>;
    /**
     * **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * Set to `true` when confirming server-side and using Stripe.js, iOS, or Android client-side SDKs to handle the next actions.
     */
    declare public readonly useStripeSdk: pulumi.Output<boolean | undefined>;

    /**
     * Create a SetupIntent resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: SetupIntentArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: SetupIntentArgs | SetupIntentState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as SetupIntentState | undefined;
            resourceInputs["application"] = state?.application;
            resourceInputs["attachToSelf"] = state?.attachToSelf;
            resourceInputs["automaticPaymentMethods"] = state?.automaticPaymentMethods;
            resourceInputs["cancellationReason"] = state?.cancellationReason;
            resourceInputs["clientSecret"] = state?.clientSecret;
            resourceInputs["confirm"] = state?.confirm;
            resourceInputs["confirmationToken"] = state?.confirmationToken;
            resourceInputs["created"] = state?.created;
            resourceInputs["customer"] = state?.customer;
            resourceInputs["customerAccount"] = state?.customerAccount;
            resourceInputs["description"] = state?.description;
            resourceInputs["excludedPaymentMethodTypes"] = state?.excludedPaymentMethodTypes;
            resourceInputs["flowDirections"] = state?.flowDirections;
            resourceInputs["lastSetupError"] = state?.lastSetupError;
            resourceInputs["latestAttempt"] = state?.latestAttempt;
            resourceInputs["livemode"] = state?.livemode;
            resourceInputs["managedPayments"] = state?.managedPayments;
            resourceInputs["mandate"] = state?.mandate;
            resourceInputs["mandateData"] = state?.mandateData;
            resourceInputs["metadata"] = state?.metadata;
            resourceInputs["nextAction"] = state?.nextAction;
            resourceInputs["object"] = state?.object;
            resourceInputs["onBehalfOf"] = state?.onBehalfOf;
            resourceInputs["paymentMethod"] = state?.paymentMethod;
            resourceInputs["paymentMethodConfiguration"] = state?.paymentMethodConfiguration;
            resourceInputs["paymentMethodConfigurationDetails"] = state?.paymentMethodConfigurationDetails;
            resourceInputs["paymentMethodData"] = state?.paymentMethodData;
            resourceInputs["paymentMethodOptions"] = state?.paymentMethodOptions;
            resourceInputs["paymentMethodTypes"] = state?.paymentMethodTypes;
            resourceInputs["returnUrl"] = state?.returnUrl;
            resourceInputs["singleUse"] = state?.singleUse;
            resourceInputs["singleUseMandate"] = state?.singleUseMandate;
            resourceInputs["status"] = state?.status;
            resourceInputs["usage"] = state?.usage;
            resourceInputs["useStripeSdk"] = state?.useStripeSdk;
        } else {
            const args = argsOrState as SetupIntentArgs | undefined;
            resourceInputs["attachToSelf"] = args?.attachToSelf;
            resourceInputs["automaticPaymentMethods"] = args?.automaticPaymentMethods;
            resourceInputs["confirm"] = args?.confirm ? pulumi.secret(args.confirm) : undefined;
            resourceInputs["confirmationToken"] = args?.confirmationToken ? pulumi.secret(args.confirmationToken) : undefined;
            resourceInputs["customer"] = args?.customer;
            resourceInputs["customerAccount"] = args?.customerAccount;
            resourceInputs["description"] = args?.description;
            resourceInputs["excludedPaymentMethodTypes"] = args?.excludedPaymentMethodTypes;
            resourceInputs["flowDirections"] = args?.flowDirections;
            resourceInputs["mandateData"] = args?.mandateData ? pulumi.secret(args.mandateData) : undefined;
            resourceInputs["metadata"] = args?.metadata;
            resourceInputs["onBehalfOf"] = args?.onBehalfOf;
            resourceInputs["paymentMethod"] = args?.paymentMethod;
            resourceInputs["paymentMethodConfiguration"] = args?.paymentMethodConfiguration ? pulumi.secret(args.paymentMethodConfiguration) : undefined;
            resourceInputs["paymentMethodData"] = args?.paymentMethodData ? pulumi.secret(args.paymentMethodData) : undefined;
            resourceInputs["paymentMethodOptions"] = args?.paymentMethodOptions;
            resourceInputs["paymentMethodTypes"] = args?.paymentMethodTypes;
            resourceInputs["returnUrl"] = args?.returnUrl ? pulumi.secret(args.returnUrl) : undefined;
            resourceInputs["singleUse"] = args?.singleUse ? pulumi.secret(args.singleUse) : undefined;
            resourceInputs["usage"] = args?.usage;
            resourceInputs["useStripeSdk"] = args?.useStripeSdk ? pulumi.secret(args.useStripeSdk) : undefined;
            resourceInputs["application"] = undefined /*out*/;
            resourceInputs["cancellationReason"] = undefined /*out*/;
            resourceInputs["clientSecret"] = undefined /*out*/;
            resourceInputs["created"] = undefined /*out*/;
            resourceInputs["lastSetupError"] = undefined /*out*/;
            resourceInputs["latestAttempt"] = undefined /*out*/;
            resourceInputs["livemode"] = undefined /*out*/;
            resourceInputs["managedPayments"] = undefined /*out*/;
            resourceInputs["mandate"] = undefined /*out*/;
            resourceInputs["nextAction"] = undefined /*out*/;
            resourceInputs["object"] = undefined /*out*/;
            resourceInputs["paymentMethodConfigurationDetails"] = undefined /*out*/;
            resourceInputs["singleUseMandate"] = undefined /*out*/;
            resourceInputs["status"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["clientSecret", "confirm", "confirmationToken", "mandateData", "paymentMethodConfiguration", "paymentMethodData", "returnUrl", "singleUse", "useStripeSdk"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(SetupIntent.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering SetupIntent resources.
 */
export interface SetupIntentState {
    /**
     * ID of the Connect application that created the SetupIntent.
     */
    application?: pulumi.Input<string | undefined>;
    /**
     * If present, the SetupIntent's payment method will be attached to the in-context Stripe Account.
     *
     * It can only be used for this Stripe Account’s own money movement flows like InboundTransfer and OutboundTransfers. It cannot be set to true when setting up a PaymentMethod for a Customer, and defaults to false when attaching a PaymentMethod to a Customer.
     */
    attachToSelf?: pulumi.Input<boolean | undefined>;
    /**
     * Settings for dynamic payment methods compatible with this Setup Intent
     */
    automaticPaymentMethods?: pulumi.Input<inputs.SetupIntentAutomaticPaymentMethods | undefined>;
    /**
     * Reason for cancellation of this SetupIntent, one of `abandoned`, `requestedByCustomer`, or `duplicate`.
     */
    cancellationReason?: pulumi.Input<string | undefined>;
    /**
     * The client secret of this SetupIntent. Used for client-side retrieval using a publishable key.
     *
     * The client secret can be used to complete payment setup from your frontend. It should not be stored, logged, or exposed to anyone other than the customer. Make sure that you have TLS enabled on any page that includes the client secret.
     */
    clientSecret?: pulumi.Input<string | undefined>;
    /**
     * **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * Set to `true` to attempt to confirm this SetupIntent immediately. This parameter defaults to `false`. If a card is the attached payment method, you can provide a `returnUrl` in case further authentication is necessary.
     */
    confirm?: pulumi.Input<boolean | undefined>;
    /**
     * **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * ID of the ConfirmationToken used to confirm this SetupIntent.
     *
     * If the provided ConfirmationToken contains properties that are also being provided in this request, such as `paymentMethod`, then the values in this request will take precedence.
     */
    confirmationToken?: pulumi.Input<string | undefined>;
    /**
     * Time at which the object was created. Measured in seconds since the Unix epoch.
     */
    created?: pulumi.Input<number | undefined>;
    /**
     * ID of the Customer this SetupIntent belongs to, if one exists.
     *
     * If present, the SetupIntent's payment method will be attached to the Customer on successful setup. Payment methods attached to other Customers cannot be used with this SetupIntent.
     */
    customer?: pulumi.Input<string | undefined>;
    /**
     * ID of the Account this SetupIntent belongs to, if one exists.
     *
     * If present, the SetupIntent's payment method will be attached to the Account on successful setup. Payment methods attached to other Accounts cannot be used with this SetupIntent.
     */
    customerAccount?: pulumi.Input<string | undefined>;
    /**
     * An arbitrary string attached to the object. Often useful for displaying to users.
     */
    description?: pulumi.Input<string | undefined>;
    /**
     * Payment method types that are excluded from this SetupIntent.
     */
    excludedPaymentMethodTypes?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * Indicates the directions of money movement for which this payment method is intended to be used.
     *
     * Include `inbound` if you intend to use the payment method as the origin to pull funds from. Include `outbound` if you intend to use the payment method as the destination to send funds to. You can include both if you intend to use the payment method for both purposes.
     */
    flowDirections?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * The error encountered in the previous SetupIntent confirmation.
     */
    lastSetupError?: pulumi.Input<inputs.SetupIntentLastSetupError | undefined>;
    /**
     * The most recent SetupAttempt for this SetupIntent.
     */
    latestAttempt?: pulumi.Input<string | undefined>;
    /**
     * If the object exists in live mode, the value is `true`. If the object exists in test mode, the value is `false`.
     */
    livemode?: pulumi.Input<boolean | undefined>;
    managedPayments?: pulumi.Input<inputs.SetupIntentManagedPayments | undefined>;
    /**
     * ID of the multi use Mandate generated by the SetupIntent.
     */
    mandate?: pulumi.Input<string | undefined>;
    /**
     * **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * This hash contains details about the mandate to create. This parameter can only be used with [`confirm=true`](https://docs.stripe.com/api/setup_intents/create#create_setup_intent-confirm).
     */
    mandateData?: pulumi.Input<inputs.SetupIntentMandateData | undefined>;
    /**
     * Set of [key-value pairs](https://docs.stripe.com/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format.
     */
    metadata?: pulumi.Input<{[key: string]: pulumi.Input<string>} | undefined>;
    /**
     * If present, this property tells you what actions you need to take in order for your customer to continue payment setup.
     */
    nextAction?: pulumi.Input<inputs.SetupIntentNextAction | undefined>;
    /**
     * String representing the object's type. Objects of the same type share the same value.
     */
    object?: pulumi.Input<string | undefined>;
    /**
     * The account (if any) for which the setup is intended.
     */
    onBehalfOf?: pulumi.Input<string | undefined>;
    /**
     * ID of the payment method used with this SetupIntent. If the payment method is `cardPresent` and isn't a digital wallet, then the [generatedCard](https://docs.stripe.com/api/setup_attempts/object#setup_attempt_object-payment_method_details-card_present-generated_card) associated with the `latestAttempt` is attached to the Customer instead.
     */
    paymentMethod?: pulumi.Input<string | undefined>;
    /**
     * **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * The ID of the [payment method configuration](https://docs.stripe.com/api/payment_method_configurations) to use with this SetupIntent.
     */
    paymentMethodConfiguration?: pulumi.Input<string | undefined>;
    /**
     * Information about the [payment method configuration](https://docs.stripe.com/api/payment_method_configurations) used for this Setup Intent.
     */
    paymentMethodConfigurationDetails?: pulumi.Input<inputs.SetupIntentPaymentMethodConfigurationDetails | undefined>;
    /**
     * **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * When included, this hash creates a PaymentMethod that is set as the [`paymentMethod`](https://docs.stripe.com/api/setup_intents/object#setup_intent_object-payment_method)
     * value in the SetupIntent.
     */
    paymentMethodData?: pulumi.Input<inputs.SetupIntentPaymentMethodData | undefined>;
    /**
     * Payment method-specific configuration for this SetupIntent.
     */
    paymentMethodOptions?: pulumi.Input<inputs.SetupIntentPaymentMethodOptions | undefined>;
    /**
     * The list of payment method types (e.g. card) that this SetupIntent is allowed to set up. A list of valid payment method types can be found [here](https://docs.stripe.com/api/payment_methods/object#payment_method_object-type).
     */
    paymentMethodTypes?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * The URL to redirect your customer back to after they authenticate or cancel their payment on the payment method's app or site. To redirect to a mobile application, you can alternatively supply an application URI scheme. This parameter can only be used with [`confirm=true`](https://docs.stripe.com/api/setup_intents/create#create_setup_intent-confirm).
     */
    returnUrl?: pulumi.Input<string | undefined>;
    /**
     * **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * If you populate this hash, this SetupIntent generates a `singleUse` mandate after successful completion.
     *
     * Single-use mandates are only valid for the following payment methods: `acssDebit`, `alipay`, `auBecsDebit`, `bacsDebit`, `bancontact`, `boleto`, `ideal`, `link`, `sepaDebit`, and `usBankAccount`.
     */
    singleUse?: pulumi.Input<inputs.SetupIntentSingleUse | undefined>;
    /**
     * ID of the singleUse Mandate generated by the SetupIntent.
     */
    singleUseMandate?: pulumi.Input<string | undefined>;
    /**
     * [Status](https://docs.stripe.com/payments/intents#intent-statuses) of this SetupIntent, one of `requiresPaymentMethod`, `requiresConfirmation`, `requiresAction`, `processing`, `canceled`, or `succeeded`.
     */
    status?: pulumi.Input<string | undefined>;
    /**
     * Indicates how the payment method is intended to be used in the future.
     *
     * Use `onSession` if you intend to only reuse the payment method when the customer is in your checkout flow. Use `offSession` if your customer may or may not be in your checkout flow. If not provided, this value defaults to `offSession`.
     */
    usage?: pulumi.Input<string | undefined>;
    /**
     * **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * Set to `true` when confirming server-side and using Stripe.js, iOS, or Android client-side SDKs to handle the next actions.
     */
    useStripeSdk?: pulumi.Input<boolean | undefined>;
}

/**
 * The set of arguments for constructing a SetupIntent resource.
 */
export interface SetupIntentArgs {
    /**
     * If present, the SetupIntent's payment method will be attached to the in-context Stripe Account.
     *
     * It can only be used for this Stripe Account’s own money movement flows like InboundTransfer and OutboundTransfers. It cannot be set to true when setting up a PaymentMethod for a Customer, and defaults to false when attaching a PaymentMethod to a Customer.
     */
    attachToSelf?: pulumi.Input<boolean | undefined>;
    /**
     * Settings for dynamic payment methods compatible with this Setup Intent
     */
    automaticPaymentMethods?: pulumi.Input<inputs.SetupIntentAutomaticPaymentMethods | undefined>;
    /**
     * **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * Set to `true` to attempt to confirm this SetupIntent immediately. This parameter defaults to `false`. If a card is the attached payment method, you can provide a `returnUrl` in case further authentication is necessary.
     */
    confirm?: pulumi.Input<boolean | undefined>;
    /**
     * **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * ID of the ConfirmationToken used to confirm this SetupIntent.
     *
     * If the provided ConfirmationToken contains properties that are also being provided in this request, such as `paymentMethod`, then the values in this request will take precedence.
     */
    confirmationToken?: pulumi.Input<string | undefined>;
    /**
     * ID of the Customer this SetupIntent belongs to, if one exists.
     *
     * If present, the SetupIntent's payment method will be attached to the Customer on successful setup. Payment methods attached to other Customers cannot be used with this SetupIntent.
     */
    customer?: pulumi.Input<string | undefined>;
    /**
     * ID of the Account this SetupIntent belongs to, if one exists.
     *
     * If present, the SetupIntent's payment method will be attached to the Account on successful setup. Payment methods attached to other Accounts cannot be used with this SetupIntent.
     */
    customerAccount?: pulumi.Input<string | undefined>;
    /**
     * An arbitrary string attached to the object. Often useful for displaying to users.
     */
    description?: pulumi.Input<string | undefined>;
    /**
     * Payment method types that are excluded from this SetupIntent.
     */
    excludedPaymentMethodTypes?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * Indicates the directions of money movement for which this payment method is intended to be used.
     *
     * Include `inbound` if you intend to use the payment method as the origin to pull funds from. Include `outbound` if you intend to use the payment method as the destination to send funds to. You can include both if you intend to use the payment method for both purposes.
     */
    flowDirections?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * This hash contains details about the mandate to create. This parameter can only be used with [`confirm=true`](https://docs.stripe.com/api/setup_intents/create#create_setup_intent-confirm).
     */
    mandateData?: pulumi.Input<inputs.SetupIntentMandateData | undefined>;
    /**
     * Set of [key-value pairs](https://docs.stripe.com/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format.
     */
    metadata?: pulumi.Input<{[key: string]: pulumi.Input<string>} | undefined>;
    /**
     * The account (if any) for which the setup is intended.
     */
    onBehalfOf?: pulumi.Input<string | undefined>;
    /**
     * ID of the payment method used with this SetupIntent. If the payment method is `cardPresent` and isn't a digital wallet, then the [generatedCard](https://docs.stripe.com/api/setup_attempts/object#setup_attempt_object-payment_method_details-card_present-generated_card) associated with the `latestAttempt` is attached to the Customer instead.
     */
    paymentMethod?: pulumi.Input<string | undefined>;
    /**
     * **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * The ID of the [payment method configuration](https://docs.stripe.com/api/payment_method_configurations) to use with this SetupIntent.
     */
    paymentMethodConfiguration?: pulumi.Input<string | undefined>;
    /**
     * **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * When included, this hash creates a PaymentMethod that is set as the [`paymentMethod`](https://docs.stripe.com/api/setup_intents/object#setup_intent_object-payment_method)
     * value in the SetupIntent.
     */
    paymentMethodData?: pulumi.Input<inputs.SetupIntentPaymentMethodData | undefined>;
    /**
     * Payment method-specific configuration for this SetupIntent.
     */
    paymentMethodOptions?: pulumi.Input<inputs.SetupIntentPaymentMethodOptions | undefined>;
    /**
     * The list of payment method types (e.g. card) that this SetupIntent is allowed to set up. A list of valid payment method types can be found [here](https://docs.stripe.com/api/payment_methods/object#payment_method_object-type).
     */
    paymentMethodTypes?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * The URL to redirect your customer back to after they authenticate or cancel their payment on the payment method's app or site. To redirect to a mobile application, you can alternatively supply an application URI scheme. This parameter can only be used with [`confirm=true`](https://docs.stripe.com/api/setup_intents/create#create_setup_intent-confirm).
     */
    returnUrl?: pulumi.Input<string | undefined>;
    /**
     * **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * If you populate this hash, this SetupIntent generates a `singleUse` mandate after successful completion.
     *
     * Single-use mandates are only valid for the following payment methods: `acssDebit`, `alipay`, `auBecsDebit`, `bacsDebit`, `bancontact`, `boleto`, `ideal`, `link`, `sepaDebit`, and `usBankAccount`.
     */
    singleUse?: pulumi.Input<inputs.SetupIntentSingleUse | undefined>;
    /**
     * Indicates how the payment method is intended to be used in the future.
     *
     * Use `onSession` if you intend to only reuse the payment method when the customer is in your checkout flow. Use `offSession` if your customer may or may not be in your checkout flow. If not provided, this value defaults to `offSession`.
     */
    usage?: pulumi.Input<string | undefined>;
    /**
     * **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * Set to `true` when confirming server-side and using Stripe.js, iOS, or Android client-side SDKs to handle the next actions.
     */
    useStripeSdk?: pulumi.Input<boolean | undefined>;
}
