// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * A subscription schedule allows you to create and manage the lifecycle of a subscription by predefining expected changes.
 *
 * Related guide: [Subscription schedules](https://docs.stripe.com/billing/subscriptions/subscription-schedules)
 */
export class SubscriptionSchedule extends pulumi.CustomResource {
    /**
     * Get an existing SubscriptionSchedule resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: SubscriptionScheduleState, opts?: pulumi.CustomResourceOptions): SubscriptionSchedule {
        return new SubscriptionSchedule(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'stripe:index/subscriptionSchedule:SubscriptionSchedule';

    /**
     * Returns true if the given object is an instance of SubscriptionSchedule.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is SubscriptionSchedule {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === SubscriptionSchedule.__pulumiType;
    }

    /**
     * ID of the Connect Application that created the schedule.
     */
    declare public /*out*/ readonly application: pulumi.Output<string>;
    /**
     * The billing mode of the subscription.
     */
    declare public readonly billingMode: pulumi.Output<outputs.SubscriptionScheduleBillingMode>;
    /**
     * Time at which the subscription schedule was canceled. Measured in seconds since the Unix epoch.
     */
    declare public /*out*/ readonly canceledAt: pulumi.Output<number>;
    /**
     * Time at which the subscription schedule was completed. Measured in seconds since the Unix epoch.
     */
    declare public /*out*/ readonly completedAt: pulumi.Output<number>;
    /**
     * Time at which the object was created. Measured in seconds since the Unix epoch.
     */
    declare public /*out*/ readonly created: pulumi.Output<number>;
    /**
     * Object representing the start and end dates for the current phase of the subscription schedule, if it is `active`.
     */
    declare public /*out*/ readonly currentPhase: pulumi.Output<outputs.SubscriptionScheduleCurrentPhase>;
    /**
     * ID of the customer who owns the subscription schedule.
     */
    declare public readonly customer: pulumi.Output<string>;
    /**
     * ID of the account who owns the subscription schedule.
     */
    declare public readonly customerAccount: pulumi.Output<string>;
    declare public readonly defaultSettings: pulumi.Output<outputs.SubscriptionScheduleDefaultSettings>;
    /**
     * Behavior of the subscription schedule and underlying subscription when it ends. Possible values are `release` or `cancel` with the default being `release`. `release` will end the subscription schedule and keep the underlying subscription running. `cancel` will end the subscription schedule and cancel the underlying subscription.
     */
    declare public readonly endBehavior: pulumi.Output<string>;
    /**
     * **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * Migrate an existing subscription to be managed by a subscription schedule. If this parameter is set, a subscription schedule will be created using the subscription's item(s), set to auto-renew using the subscription's interval. When using this parameter, other parameters (such as phase values) cannot be set. To create a subscription schedule with other modifications, we recommend making two separate API calls.
     */
    declare public readonly fromSubscription: pulumi.Output<string | undefined>;
    /**
     * If the object exists in live mode, the value is `true`. If the object exists in test mode, the value is `false`.
     */
    declare public /*out*/ readonly livemode: pulumi.Output<boolean>;
    /**
     * Set of [key-value pairs](https://docs.stripe.com/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format.
     */
    declare public readonly metadata: pulumi.Output<{[key: string]: string}>;
    /**
     * String representing the object's type. Objects of the same type share the same value.
     */
    declare public /*out*/ readonly object: pulumi.Output<string>;
    /**
     * Configuration for the subscription schedule's phases.
     */
    declare public readonly phases: pulumi.Output<outputs.SubscriptionSchedulePhase[]>;
    /**
     * Time at which the subscription schedule was released. Measured in seconds since the Unix epoch.
     */
    declare public /*out*/ readonly releasedAt: pulumi.Output<number>;
    /**
     * ID of the subscription once managed by the subscription schedule (if it is released).
     */
    declare public /*out*/ readonly releasedSubscription: pulumi.Output<string>;
    /**
     * When the subscription schedule starts. We recommend using `now` so that it starts the subscription immediately. You can also use a Unix timestamp to backdate the subscription so that it starts on a past date, or set a future date for the subscription to start on.
     */
    declare public readonly startDate: pulumi.Output<number | undefined>;
    /**
     * The present status of the subscription schedule. Possible values are `notStarted`, `active`, `completed`, `released`, and `canceled`. You can read more about the different states in our [behavior guide](https://docs.stripe.com/billing/subscriptions/subscription-schedules).
     */
    declare public /*out*/ readonly status: pulumi.Output<string>;
    /**
     * ID of the subscription managed by the subscription schedule.
     */
    declare public /*out*/ readonly subscription: pulumi.Output<string>;
    /**
     * ID of the test clock this subscription schedule belongs to.
     */
    declare public /*out*/ readonly testClock: pulumi.Output<string>;

    /**
     * Create a SubscriptionSchedule resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: SubscriptionScheduleArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: SubscriptionScheduleArgs | SubscriptionScheduleState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as SubscriptionScheduleState | undefined;
            resourceInputs["application"] = state?.application;
            resourceInputs["billingMode"] = state?.billingMode;
            resourceInputs["canceledAt"] = state?.canceledAt;
            resourceInputs["completedAt"] = state?.completedAt;
            resourceInputs["created"] = state?.created;
            resourceInputs["currentPhase"] = state?.currentPhase;
            resourceInputs["customer"] = state?.customer;
            resourceInputs["customerAccount"] = state?.customerAccount;
            resourceInputs["defaultSettings"] = state?.defaultSettings;
            resourceInputs["endBehavior"] = state?.endBehavior;
            resourceInputs["fromSubscription"] = state?.fromSubscription;
            resourceInputs["livemode"] = state?.livemode;
            resourceInputs["metadata"] = state?.metadata;
            resourceInputs["object"] = state?.object;
            resourceInputs["phases"] = state?.phases;
            resourceInputs["releasedAt"] = state?.releasedAt;
            resourceInputs["releasedSubscription"] = state?.releasedSubscription;
            resourceInputs["startDate"] = state?.startDate;
            resourceInputs["status"] = state?.status;
            resourceInputs["subscription"] = state?.subscription;
            resourceInputs["testClock"] = state?.testClock;
        } else {
            const args = argsOrState as SubscriptionScheduleArgs | undefined;
            resourceInputs["billingMode"] = args?.billingMode;
            resourceInputs["customer"] = args?.customer;
            resourceInputs["customerAccount"] = args?.customerAccount;
            resourceInputs["defaultSettings"] = args?.defaultSettings;
            resourceInputs["endBehavior"] = args?.endBehavior;
            resourceInputs["fromSubscription"] = args?.fromSubscription ? pulumi.secret(args.fromSubscription) : undefined;
            resourceInputs["metadata"] = args?.metadata;
            resourceInputs["phases"] = args?.phases;
            resourceInputs["startDate"] = args?.startDate;
            resourceInputs["application"] = undefined /*out*/;
            resourceInputs["canceledAt"] = undefined /*out*/;
            resourceInputs["completedAt"] = undefined /*out*/;
            resourceInputs["created"] = undefined /*out*/;
            resourceInputs["currentPhase"] = undefined /*out*/;
            resourceInputs["livemode"] = undefined /*out*/;
            resourceInputs["object"] = undefined /*out*/;
            resourceInputs["releasedAt"] = undefined /*out*/;
            resourceInputs["releasedSubscription"] = undefined /*out*/;
            resourceInputs["status"] = undefined /*out*/;
            resourceInputs["subscription"] = undefined /*out*/;
            resourceInputs["testClock"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["fromSubscription"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(SubscriptionSchedule.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering SubscriptionSchedule resources.
 */
export interface SubscriptionScheduleState {
    /**
     * ID of the Connect Application that created the schedule.
     */
    application?: pulumi.Input<string | undefined>;
    /**
     * The billing mode of the subscription.
     */
    billingMode?: pulumi.Input<inputs.SubscriptionScheduleBillingMode | undefined>;
    /**
     * Time at which the subscription schedule was canceled. Measured in seconds since the Unix epoch.
     */
    canceledAt?: pulumi.Input<number | undefined>;
    /**
     * Time at which the subscription schedule was completed. Measured in seconds since the Unix epoch.
     */
    completedAt?: pulumi.Input<number | undefined>;
    /**
     * Time at which the object was created. Measured in seconds since the Unix epoch.
     */
    created?: pulumi.Input<number | undefined>;
    /**
     * Object representing the start and end dates for the current phase of the subscription schedule, if it is `active`.
     */
    currentPhase?: pulumi.Input<inputs.SubscriptionScheduleCurrentPhase | undefined>;
    /**
     * ID of the customer who owns the subscription schedule.
     */
    customer?: pulumi.Input<string | undefined>;
    /**
     * ID of the account who owns the subscription schedule.
     */
    customerAccount?: pulumi.Input<string | undefined>;
    defaultSettings?: pulumi.Input<inputs.SubscriptionScheduleDefaultSettings | undefined>;
    /**
     * Behavior of the subscription schedule and underlying subscription when it ends. Possible values are `release` or `cancel` with the default being `release`. `release` will end the subscription schedule and keep the underlying subscription running. `cancel` will end the subscription schedule and cancel the underlying subscription.
     */
    endBehavior?: pulumi.Input<string | undefined>;
    /**
     * **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * Migrate an existing subscription to be managed by a subscription schedule. If this parameter is set, a subscription schedule will be created using the subscription's item(s), set to auto-renew using the subscription's interval. When using this parameter, other parameters (such as phase values) cannot be set. To create a subscription schedule with other modifications, we recommend making two separate API calls.
     */
    fromSubscription?: pulumi.Input<string | undefined>;
    /**
     * If the object exists in live mode, the value is `true`. If the object exists in test mode, the value is `false`.
     */
    livemode?: pulumi.Input<boolean | undefined>;
    /**
     * Set of [key-value pairs](https://docs.stripe.com/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format.
     */
    metadata?: pulumi.Input<{[key: string]: pulumi.Input<string>} | undefined>;
    /**
     * String representing the object's type. Objects of the same type share the same value.
     */
    object?: pulumi.Input<string | undefined>;
    /**
     * Configuration for the subscription schedule's phases.
     */
    phases?: pulumi.Input<pulumi.Input<inputs.SubscriptionSchedulePhase>[] | undefined>;
    /**
     * Time at which the subscription schedule was released. Measured in seconds since the Unix epoch.
     */
    releasedAt?: pulumi.Input<number | undefined>;
    /**
     * ID of the subscription once managed by the subscription schedule (if it is released).
     */
    releasedSubscription?: pulumi.Input<string | undefined>;
    /**
     * When the subscription schedule starts. We recommend using `now` so that it starts the subscription immediately. You can also use a Unix timestamp to backdate the subscription so that it starts on a past date, or set a future date for the subscription to start on.
     */
    startDate?: pulumi.Input<number | undefined>;
    /**
     * The present status of the subscription schedule. Possible values are `notStarted`, `active`, `completed`, `released`, and `canceled`. You can read more about the different states in our [behavior guide](https://docs.stripe.com/billing/subscriptions/subscription-schedules).
     */
    status?: pulumi.Input<string | undefined>;
    /**
     * ID of the subscription managed by the subscription schedule.
     */
    subscription?: pulumi.Input<string | undefined>;
    /**
     * ID of the test clock this subscription schedule belongs to.
     */
    testClock?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a SubscriptionSchedule resource.
 */
export interface SubscriptionScheduleArgs {
    /**
     * The billing mode of the subscription.
     */
    billingMode?: pulumi.Input<inputs.SubscriptionScheduleBillingMode | undefined>;
    /**
     * ID of the customer who owns the subscription schedule.
     */
    customer?: pulumi.Input<string | undefined>;
    /**
     * ID of the account who owns the subscription schedule.
     */
    customerAccount?: pulumi.Input<string | undefined>;
    defaultSettings?: pulumi.Input<inputs.SubscriptionScheduleDefaultSettings | undefined>;
    /**
     * Behavior of the subscription schedule and underlying subscription when it ends. Possible values are `release` or `cancel` with the default being `release`. `release` will end the subscription schedule and keep the underlying subscription running. `cancel` will end the subscription schedule and cancel the underlying subscription.
     */
    endBehavior?: pulumi.Input<string | undefined>;
    /**
     * **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * Migrate an existing subscription to be managed by a subscription schedule. If this parameter is set, a subscription schedule will be created using the subscription's item(s), set to auto-renew using the subscription's interval. When using this parameter, other parameters (such as phase values) cannot be set. To create a subscription schedule with other modifications, we recommend making two separate API calls.
     */
    fromSubscription?: pulumi.Input<string | undefined>;
    /**
     * Set of [key-value pairs](https://docs.stripe.com/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format.
     */
    metadata?: pulumi.Input<{[key: string]: pulumi.Input<string>} | undefined>;
    /**
     * Configuration for the subscription schedule's phases.
     */
    phases?: pulumi.Input<pulumi.Input<inputs.SubscriptionSchedulePhase>[] | undefined>;
    /**
     * When the subscription schedule starts. We recommend using `now` so that it starts the subscription immediately. You can also use a Unix timestamp to backdate the subscription so that it starts on a past date, or set a future date for the subscription to start on.
     */
    startDate?: pulumi.Input<number | undefined>;
}
