// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * You can add one or multiple tax IDs to a [customer](https://docs.stripe.com/api/customers) or account.
 * Customer and account tax IDs get displayed on related invoices and credit notes.
 *
 * Related guides: [Customer tax identification numbers](https://docs.stripe.com/billing/taxes/tax-ids), [Account tax IDs](https://docs.stripe.com/invoicing/connect#account-tax-ids)
 */
export class TaxId extends pulumi.CustomResource {
    /**
     * Get an existing TaxId resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: TaxIdState, opts?: pulumi.CustomResourceOptions): TaxId {
        return new TaxId(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'stripe:index/taxId:TaxId';

    /**
     * Returns true if the given object is an instance of TaxId.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is TaxId {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === TaxId.__pulumiType;
    }

    /**
     * Two-letter ISO code representing the country of the tax ID.
     */
    declare public /*out*/ readonly country: pulumi.Output<string>;
    /**
     * Time at which the object was created. Measured in seconds since the Unix epoch.
     */
    declare public /*out*/ readonly created: pulumi.Output<number>;
    /**
     * ID of the customer.
     */
    declare public readonly customer: pulumi.Output<string>;
    /**
     * ID of the Account representing the customer.
     */
    declare public /*out*/ readonly customerAccount: pulumi.Output<string>;
    /**
     * If the object exists in live mode, the value is `true`. If the object exists in test mode, the value is `false`.
     */
    declare public /*out*/ readonly livemode: pulumi.Output<boolean>;
    /**
     * String representing the object's type. Objects of the same type share the same value.
     */
    declare public /*out*/ readonly object: pulumi.Output<string>;
    /**
     * The account or customer the tax ID belongs to.
     */
    declare public /*out*/ readonly owner: pulumi.Output<outputs.TaxIdOwner>;
    /**
     * Type of the tax ID, one of `adNrt`, `aeTrn`, `alTin`, `amTin`, `aoTin`, `arCuit`, `auAbn`, `auArn`, `awTin`, `azTin`, `baTin`, `bbTin`, `bdBin`, `bfIfu`, `bgUic`, `bhVat`, `bjIfu`, `boTin`, `brCnpj`, `brCpf`, `bsTin`, `byTin`, `caBn`, `caGstHst`, `caPstBc`, `caPstMb`, `caPstSk`, `caQst`, `cdNif`, `chUid`, `chVat`, `clTin`, `cmNiu`, `cnTin`, `coNit`, `crTin`, `cvNif`, `deStn`, `doRcn`, `ecRuc`, `egTin`, `esCif`, `etTin`, `euOssVat`, `euVat`, `foVat`, `gbVat`, `geVat`, `giTin`, `gnNif`, `hkBr`, `hrOib`, `huTin`, `idNpwp`, `ilVat`, `inGst`, `isVat`, `itCf`, `jpCn`, `jpRn`, `jpTrn`, `kePin`, `kgTin`, `khTin`, `krBrn`, `kzBin`, `laTin`, `liUid`, `liVat`, `lkVat`, `maVat`, `mdVat`, `mePib`, `mkVat`, `mrNif`, `mxRfc`, `myFrp`, `myItn`, `mySst`, `ngTin`, `noVat`, `noVoec`, `npPan`, `nzGst`, `omVat`, `peRuc`, `phTin`, `plNip`, `pyRuc`, `roTin`, `rsPib`, `ruInn`, `ruKpp`, `saVat`, `sgGst`, `sgUen`, `siTin`, `snNinea`, `srFin`, `svNit`, `thVat`, `tjTin`, `trTin`, `twVat`, `tzVat`, `uaVat`, `ugTin`, `usEin`, `uyRuc`, `uzTin`, `uzVat`, `veRif`, `vnTin`, `zaVat`, `zmTin`, or `zwTin`. Note that some legacy tax IDs have type `unknown`
     */
    declare public readonly type: pulumi.Output<string>;
    /**
     * Value of the tax ID.
     */
    declare public readonly value: pulumi.Output<string>;
    /**
     * Tax ID verification information.
     */
    declare public /*out*/ readonly verification: pulumi.Output<outputs.TaxIdVerification>;

    /**
     * Create a TaxId resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: TaxIdArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: TaxIdArgs | TaxIdState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as TaxIdState | undefined;
            resourceInputs["country"] = state?.country;
            resourceInputs["created"] = state?.created;
            resourceInputs["customer"] = state?.customer;
            resourceInputs["customerAccount"] = state?.customerAccount;
            resourceInputs["livemode"] = state?.livemode;
            resourceInputs["object"] = state?.object;
            resourceInputs["owner"] = state?.owner;
            resourceInputs["type"] = state?.type;
            resourceInputs["value"] = state?.value;
            resourceInputs["verification"] = state?.verification;
        } else {
            const args = argsOrState as TaxIdArgs | undefined;
            if (args?.customer === undefined && !opts.urn) {
                throw new Error("Missing required property 'customer'");
            }
            if (args?.type === undefined && !opts.urn) {
                throw new Error("Missing required property 'type'");
            }
            if (args?.value === undefined && !opts.urn) {
                throw new Error("Missing required property 'value'");
            }
            resourceInputs["customer"] = args?.customer;
            resourceInputs["type"] = args?.type;
            resourceInputs["value"] = args?.value;
            resourceInputs["country"] = undefined /*out*/;
            resourceInputs["created"] = undefined /*out*/;
            resourceInputs["customerAccount"] = undefined /*out*/;
            resourceInputs["livemode"] = undefined /*out*/;
            resourceInputs["object"] = undefined /*out*/;
            resourceInputs["owner"] = undefined /*out*/;
            resourceInputs["verification"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(TaxId.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering TaxId resources.
 */
export interface TaxIdState {
    /**
     * Two-letter ISO code representing the country of the tax ID.
     */
    country?: pulumi.Input<string | undefined>;
    /**
     * Time at which the object was created. Measured in seconds since the Unix epoch.
     */
    created?: pulumi.Input<number | undefined>;
    /**
     * ID of the customer.
     */
    customer?: pulumi.Input<string | undefined>;
    /**
     * ID of the Account representing the customer.
     */
    customerAccount?: pulumi.Input<string | undefined>;
    /**
     * If the object exists in live mode, the value is `true`. If the object exists in test mode, the value is `false`.
     */
    livemode?: pulumi.Input<boolean | undefined>;
    /**
     * String representing the object's type. Objects of the same type share the same value.
     */
    object?: pulumi.Input<string | undefined>;
    /**
     * The account or customer the tax ID belongs to.
     */
    owner?: pulumi.Input<inputs.TaxIdOwner | undefined>;
    /**
     * Type of the tax ID, one of `adNrt`, `aeTrn`, `alTin`, `amTin`, `aoTin`, `arCuit`, `auAbn`, `auArn`, `awTin`, `azTin`, `baTin`, `bbTin`, `bdBin`, `bfIfu`, `bgUic`, `bhVat`, `bjIfu`, `boTin`, `brCnpj`, `brCpf`, `bsTin`, `byTin`, `caBn`, `caGstHst`, `caPstBc`, `caPstMb`, `caPstSk`, `caQst`, `cdNif`, `chUid`, `chVat`, `clTin`, `cmNiu`, `cnTin`, `coNit`, `crTin`, `cvNif`, `deStn`, `doRcn`, `ecRuc`, `egTin`, `esCif`, `etTin`, `euOssVat`, `euVat`, `foVat`, `gbVat`, `geVat`, `giTin`, `gnNif`, `hkBr`, `hrOib`, `huTin`, `idNpwp`, `ilVat`, `inGst`, `isVat`, `itCf`, `jpCn`, `jpRn`, `jpTrn`, `kePin`, `kgTin`, `khTin`, `krBrn`, `kzBin`, `laTin`, `liUid`, `liVat`, `lkVat`, `maVat`, `mdVat`, `mePib`, `mkVat`, `mrNif`, `mxRfc`, `myFrp`, `myItn`, `mySst`, `ngTin`, `noVat`, `noVoec`, `npPan`, `nzGst`, `omVat`, `peRuc`, `phTin`, `plNip`, `pyRuc`, `roTin`, `rsPib`, `ruInn`, `ruKpp`, `saVat`, `sgGst`, `sgUen`, `siTin`, `snNinea`, `srFin`, `svNit`, `thVat`, `tjTin`, `trTin`, `twVat`, `tzVat`, `uaVat`, `ugTin`, `usEin`, `uyRuc`, `uzTin`, `uzVat`, `veRif`, `vnTin`, `zaVat`, `zmTin`, or `zwTin`. Note that some legacy tax IDs have type `unknown`
     */
    type?: pulumi.Input<string | undefined>;
    /**
     * Value of the tax ID.
     */
    value?: pulumi.Input<string | undefined>;
    /**
     * Tax ID verification information.
     */
    verification?: pulumi.Input<inputs.TaxIdVerification | undefined>;
}

/**
 * The set of arguments for constructing a TaxId resource.
 */
export interface TaxIdArgs {
    /**
     * ID of the customer.
     */
    customer: pulumi.Input<string>;
    /**
     * Type of the tax ID, one of `adNrt`, `aeTrn`, `alTin`, `amTin`, `aoTin`, `arCuit`, `auAbn`, `auArn`, `awTin`, `azTin`, `baTin`, `bbTin`, `bdBin`, `bfIfu`, `bgUic`, `bhVat`, `bjIfu`, `boTin`, `brCnpj`, `brCpf`, `bsTin`, `byTin`, `caBn`, `caGstHst`, `caPstBc`, `caPstMb`, `caPstSk`, `caQst`, `cdNif`, `chUid`, `chVat`, `clTin`, `cmNiu`, `cnTin`, `coNit`, `crTin`, `cvNif`, `deStn`, `doRcn`, `ecRuc`, `egTin`, `esCif`, `etTin`, `euOssVat`, `euVat`, `foVat`, `gbVat`, `geVat`, `giTin`, `gnNif`, `hkBr`, `hrOib`, `huTin`, `idNpwp`, `ilVat`, `inGst`, `isVat`, `itCf`, `jpCn`, `jpRn`, `jpTrn`, `kePin`, `kgTin`, `khTin`, `krBrn`, `kzBin`, `laTin`, `liUid`, `liVat`, `lkVat`, `maVat`, `mdVat`, `mePib`, `mkVat`, `mrNif`, `mxRfc`, `myFrp`, `myItn`, `mySst`, `ngTin`, `noVat`, `noVoec`, `npPan`, `nzGst`, `omVat`, `peRuc`, `phTin`, `plNip`, `pyRuc`, `roTin`, `rsPib`, `ruInn`, `ruKpp`, `saVat`, `sgGst`, `sgUen`, `siTin`, `snNinea`, `srFin`, `svNit`, `thVat`, `tjTin`, `trTin`, `twVat`, `tzVat`, `uaVat`, `ugTin`, `usEin`, `uyRuc`, `uzTin`, `uzVat`, `veRif`, `vnTin`, `zaVat`, `zmTin`, or `zwTin`. Note that some legacy tax IDs have type `unknown`
     */
    type: pulumi.Input<string>;
    /**
     * Value of the tax ID.
     */
    value: pulumi.Input<string>;
}
