// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * A Tax `Registration` lets us know that your business is registered to collect tax on payments within a region, enabling you to [automatically collect tax](https://docs.stripe.com/tax).
 *
 * Stripe doesn't register on your behalf with the relevant authorities when you create a Tax `Registration` object. For more information on how to register to collect tax, see [our guide](https://docs.stripe.com/tax/registering).
 *
 * Related guide: [Using the Registrations API](https://docs.stripe.com/tax/registrations-api)
 */
export class TaxRegistration extends pulumi.CustomResource {
    /**
     * Get an existing TaxRegistration resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: TaxRegistrationState, opts?: pulumi.CustomResourceOptions): TaxRegistration {
        return new TaxRegistration(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'stripe:index/taxRegistration:TaxRegistration';

    /**
     * Returns true if the given object is an instance of TaxRegistration.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is TaxRegistration {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === TaxRegistration.__pulumiType;
    }

    /**
     * Time at which the registration becomes active. Measured in seconds since the Unix epoch.
     */
    declare public readonly activeFrom: pulumi.Output<number>;
    /**
     * Two-letter country code ([ISO 3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2)).
     */
    declare public readonly country: pulumi.Output<string>;
    declare public readonly countryOptions: pulumi.Output<outputs.TaxRegistrationCountryOptions>;
    /**
     * Time at which the object was created. Measured in seconds since the Unix epoch.
     */
    declare public /*out*/ readonly created: pulumi.Output<number>;
    /**
     * If set, the registration stops being active at this time. If not set, the registration will be active indefinitely. Measured in seconds since the Unix epoch.
     */
    declare public readonly expiresAt: pulumi.Output<number>;
    /**
     * If the object exists in live mode, the value is `true`. If the object exists in test mode, the value is `false`.
     */
    declare public /*out*/ readonly livemode: pulumi.Output<boolean>;
    /**
     * String representing the object's type. Objects of the same type share the same value.
     */
    declare public /*out*/ readonly object: pulumi.Output<string>;
    /**
     * The status of the registration. This field is present for convenience and can be deduced from `activeFrom` and `expiresAt`.
     */
    declare public /*out*/ readonly status: pulumi.Output<string>;

    /**
     * Create a TaxRegistration resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: TaxRegistrationArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: TaxRegistrationArgs | TaxRegistrationState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as TaxRegistrationState | undefined;
            resourceInputs["activeFrom"] = state?.activeFrom;
            resourceInputs["country"] = state?.country;
            resourceInputs["countryOptions"] = state?.countryOptions;
            resourceInputs["created"] = state?.created;
            resourceInputs["expiresAt"] = state?.expiresAt;
            resourceInputs["livemode"] = state?.livemode;
            resourceInputs["object"] = state?.object;
            resourceInputs["status"] = state?.status;
        } else {
            const args = argsOrState as TaxRegistrationArgs | undefined;
            if (args?.activeFrom === undefined && !opts.urn) {
                throw new Error("Missing required property 'activeFrom'");
            }
            if (args?.country === undefined && !opts.urn) {
                throw new Error("Missing required property 'country'");
            }
            if (args?.countryOptions === undefined && !opts.urn) {
                throw new Error("Missing required property 'countryOptions'");
            }
            resourceInputs["activeFrom"] = args?.activeFrom;
            resourceInputs["country"] = args?.country;
            resourceInputs["countryOptions"] = args?.countryOptions;
            resourceInputs["expiresAt"] = args?.expiresAt;
            resourceInputs["created"] = undefined /*out*/;
            resourceInputs["livemode"] = undefined /*out*/;
            resourceInputs["object"] = undefined /*out*/;
            resourceInputs["status"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(TaxRegistration.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering TaxRegistration resources.
 */
export interface TaxRegistrationState {
    /**
     * Time at which the registration becomes active. Measured in seconds since the Unix epoch.
     */
    activeFrom?: pulumi.Input<number | undefined>;
    /**
     * Two-letter country code ([ISO 3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2)).
     */
    country?: pulumi.Input<string | undefined>;
    countryOptions?: pulumi.Input<inputs.TaxRegistrationCountryOptions | undefined>;
    /**
     * Time at which the object was created. Measured in seconds since the Unix epoch.
     */
    created?: pulumi.Input<number | undefined>;
    /**
     * If set, the registration stops being active at this time. If not set, the registration will be active indefinitely. Measured in seconds since the Unix epoch.
     */
    expiresAt?: pulumi.Input<number | undefined>;
    /**
     * If the object exists in live mode, the value is `true`. If the object exists in test mode, the value is `false`.
     */
    livemode?: pulumi.Input<boolean | undefined>;
    /**
     * String representing the object's type. Objects of the same type share the same value.
     */
    object?: pulumi.Input<string | undefined>;
    /**
     * The status of the registration. This field is present for convenience and can be deduced from `activeFrom` and `expiresAt`.
     */
    status?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a TaxRegistration resource.
 */
export interface TaxRegistrationArgs {
    /**
     * Time at which the registration becomes active. Measured in seconds since the Unix epoch.
     */
    activeFrom: pulumi.Input<number>;
    /**
     * Two-letter country code ([ISO 3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2)).
     */
    country: pulumi.Input<string>;
    countryOptions: pulumi.Input<inputs.TaxRegistrationCountryOptions>;
    /**
     * If set, the registration stops being active at this time. If not set, the registration will be active indefinitely. Measured in seconds since the Unix epoch.
     */
    expiresAt?: pulumi.Input<number | undefined>;
}
