// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * Tax rates can be applied to [invoices](https://docs.stripe.com/invoicing/taxes/tax-rates), [subscriptions](https://docs.stripe.com/billing/taxes/tax-rates) and [Checkout Sessions](https://docs.stripe.com/payments/checkout/use-manual-tax-rates) to collect tax.
 *
 * Related guide: [Tax rates](https://docs.stripe.com/billing/taxes/tax-rates)
 */
export class TaxRate extends pulumi.CustomResource {
    /**
     * Get an existing TaxRate resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: TaxRateState, opts?: pulumi.CustomResourceOptions): TaxRate {
        return new TaxRate(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'stripe:index/taxRate:TaxRate';

    /**
     * Returns true if the given object is an instance of TaxRate.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is TaxRate {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === TaxRate.__pulumiType;
    }

    /**
     * Defaults to `true`. When set to `false`, this tax rate cannot be used with new applications or Checkout Sessions, but will still work for subscriptions and invoices that already have it set.
     */
    declare public readonly active: pulumi.Output<boolean>;
    /**
     * Two-letter country code ([ISO 3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2)).
     */
    declare public readonly country: pulumi.Output<string>;
    /**
     * Time at which the object was created. Measured in seconds since the Unix epoch.
     */
    declare public /*out*/ readonly created: pulumi.Output<number>;
    /**
     * An arbitrary string attached to the tax rate for your internal use only. It will not be visible to your customers.
     */
    declare public readonly description: pulumi.Output<string>;
    /**
     * The display name of the tax rates as it will appear to your customer on their receipt email, PDF, and the hosted invoice page.
     */
    declare public readonly displayName: pulumi.Output<string>;
    /**
     * Actual/effective tax rate percentage out of 100. For tax calculations with automatic_tax[enabled]=true,
     * this percentage reflects the rate actually used to calculate tax based on the product's taxability
     * and whether the user is registered to collect taxes in the corresponding jurisdiction.
     */
    declare public /*out*/ readonly effectivePercentage: pulumi.Output<number>;
    /**
     * The amount of the tax rate when the `rateType` is `flatAmount`. Tax rates with `rateType` `percentage` can vary based on the transaction, resulting in this field being `null`. This field exposes the amount and currency of the flat tax rate.
     */
    declare public /*out*/ readonly flatAmount: pulumi.Output<outputs.TaxRateFlatAmount>;
    /**
     * This specifies if the tax rate is inclusive or exclusive.
     */
    declare public readonly inclusive: pulumi.Output<boolean>;
    /**
     * The jurisdiction for the tax rate. You can use this label field for tax reporting purposes. It also appears on your customer’s invoice.
     */
    declare public readonly jurisdiction: pulumi.Output<string>;
    /**
     * The level of the jurisdiction that imposes this tax rate. Will be `null` for manually defined tax rates.
     */
    declare public /*out*/ readonly jurisdictionLevel: pulumi.Output<string>;
    /**
     * If the object exists in live mode, the value is `true`. If the object exists in test mode, the value is `false`.
     */
    declare public /*out*/ readonly livemode: pulumi.Output<boolean>;
    /**
     * Set of [key-value pairs](https://docs.stripe.com/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format.
     */
    declare public readonly metadata: pulumi.Output<{[key: string]: string}>;
    /**
     * String representing the object's type. Objects of the same type share the same value.
     */
    declare public /*out*/ readonly object: pulumi.Output<string>;
    /**
     * Tax rate percentage out of 100. For tax calculations with automatic_tax[enabled]=true, this percentage includes the statutory tax rate of non-taxable jurisdictions.
     */
    declare public readonly percentage: pulumi.Output<number>;
    /**
     * Indicates the type of tax rate applied to the taxable amount. This value can be `null` when no tax applies to the location. This field is only present for TaxRates created by Stripe Tax.
     */
    declare public /*out*/ readonly rateType: pulumi.Output<string>;
    /**
     * [ISO 3166-2 subdivision code](https://en.wikipedia.org/wiki/ISO_3166-2), without country prefix. For example, "NY" for New York, United States.
     */
    declare public readonly state: pulumi.Output<string>;
    /**
     * The high-level tax type, such as `vat` or `salesTax`.
     */
    declare public readonly taxType: pulumi.Output<string>;

    /**
     * Create a TaxRate resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: TaxRateArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: TaxRateArgs | TaxRateState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as TaxRateState | undefined;
            resourceInputs["active"] = state?.active;
            resourceInputs["country"] = state?.country;
            resourceInputs["created"] = state?.created;
            resourceInputs["description"] = state?.description;
            resourceInputs["displayName"] = state?.displayName;
            resourceInputs["effectivePercentage"] = state?.effectivePercentage;
            resourceInputs["flatAmount"] = state?.flatAmount;
            resourceInputs["inclusive"] = state?.inclusive;
            resourceInputs["jurisdiction"] = state?.jurisdiction;
            resourceInputs["jurisdictionLevel"] = state?.jurisdictionLevel;
            resourceInputs["livemode"] = state?.livemode;
            resourceInputs["metadata"] = state?.metadata;
            resourceInputs["object"] = state?.object;
            resourceInputs["percentage"] = state?.percentage;
            resourceInputs["rateType"] = state?.rateType;
            resourceInputs["state"] = state?.state;
            resourceInputs["taxType"] = state?.taxType;
        } else {
            const args = argsOrState as TaxRateArgs | undefined;
            if (args?.displayName === undefined && !opts.urn) {
                throw new Error("Missing required property 'displayName'");
            }
            if (args?.inclusive === undefined && !opts.urn) {
                throw new Error("Missing required property 'inclusive'");
            }
            if (args?.percentage === undefined && !opts.urn) {
                throw new Error("Missing required property 'percentage'");
            }
            resourceInputs["active"] = args?.active;
            resourceInputs["country"] = args?.country;
            resourceInputs["description"] = args?.description;
            resourceInputs["displayName"] = args?.displayName;
            resourceInputs["inclusive"] = args?.inclusive;
            resourceInputs["jurisdiction"] = args?.jurisdiction;
            resourceInputs["metadata"] = args?.metadata;
            resourceInputs["percentage"] = args?.percentage;
            resourceInputs["state"] = args?.state;
            resourceInputs["taxType"] = args?.taxType;
            resourceInputs["created"] = undefined /*out*/;
            resourceInputs["effectivePercentage"] = undefined /*out*/;
            resourceInputs["flatAmount"] = undefined /*out*/;
            resourceInputs["jurisdictionLevel"] = undefined /*out*/;
            resourceInputs["livemode"] = undefined /*out*/;
            resourceInputs["object"] = undefined /*out*/;
            resourceInputs["rateType"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(TaxRate.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering TaxRate resources.
 */
export interface TaxRateState {
    /**
     * Defaults to `true`. When set to `false`, this tax rate cannot be used with new applications or Checkout Sessions, but will still work for subscriptions and invoices that already have it set.
     */
    active?: pulumi.Input<boolean | undefined>;
    /**
     * Two-letter country code ([ISO 3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2)).
     */
    country?: pulumi.Input<string | undefined>;
    /**
     * Time at which the object was created. Measured in seconds since the Unix epoch.
     */
    created?: pulumi.Input<number | undefined>;
    /**
     * An arbitrary string attached to the tax rate for your internal use only. It will not be visible to your customers.
     */
    description?: pulumi.Input<string | undefined>;
    /**
     * The display name of the tax rates as it will appear to your customer on their receipt email, PDF, and the hosted invoice page.
     */
    displayName?: pulumi.Input<string | undefined>;
    /**
     * Actual/effective tax rate percentage out of 100. For tax calculations with automatic_tax[enabled]=true,
     * this percentage reflects the rate actually used to calculate tax based on the product's taxability
     * and whether the user is registered to collect taxes in the corresponding jurisdiction.
     */
    effectivePercentage?: pulumi.Input<number | undefined>;
    /**
     * The amount of the tax rate when the `rateType` is `flatAmount`. Tax rates with `rateType` `percentage` can vary based on the transaction, resulting in this field being `null`. This field exposes the amount and currency of the flat tax rate.
     */
    flatAmount?: pulumi.Input<inputs.TaxRateFlatAmount | undefined>;
    /**
     * This specifies if the tax rate is inclusive or exclusive.
     */
    inclusive?: pulumi.Input<boolean | undefined>;
    /**
     * The jurisdiction for the tax rate. You can use this label field for tax reporting purposes. It also appears on your customer’s invoice.
     */
    jurisdiction?: pulumi.Input<string | undefined>;
    /**
     * The level of the jurisdiction that imposes this tax rate. Will be `null` for manually defined tax rates.
     */
    jurisdictionLevel?: pulumi.Input<string | undefined>;
    /**
     * If the object exists in live mode, the value is `true`. If the object exists in test mode, the value is `false`.
     */
    livemode?: pulumi.Input<boolean | undefined>;
    /**
     * Set of [key-value pairs](https://docs.stripe.com/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format.
     */
    metadata?: pulumi.Input<{[key: string]: pulumi.Input<string>} | undefined>;
    /**
     * String representing the object's type. Objects of the same type share the same value.
     */
    object?: pulumi.Input<string | undefined>;
    /**
     * Tax rate percentage out of 100. For tax calculations with automatic_tax[enabled]=true, this percentage includes the statutory tax rate of non-taxable jurisdictions.
     */
    percentage?: pulumi.Input<number | undefined>;
    /**
     * Indicates the type of tax rate applied to the taxable amount. This value can be `null` when no tax applies to the location. This field is only present for TaxRates created by Stripe Tax.
     */
    rateType?: pulumi.Input<string | undefined>;
    /**
     * [ISO 3166-2 subdivision code](https://en.wikipedia.org/wiki/ISO_3166-2), without country prefix. For example, "NY" for New York, United States.
     */
    state?: pulumi.Input<string | undefined>;
    /**
     * The high-level tax type, such as `vat` or `salesTax`.
     */
    taxType?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a TaxRate resource.
 */
export interface TaxRateArgs {
    /**
     * Defaults to `true`. When set to `false`, this tax rate cannot be used with new applications or Checkout Sessions, but will still work for subscriptions and invoices that already have it set.
     */
    active?: pulumi.Input<boolean | undefined>;
    /**
     * Two-letter country code ([ISO 3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2)).
     */
    country?: pulumi.Input<string | undefined>;
    /**
     * An arbitrary string attached to the tax rate for your internal use only. It will not be visible to your customers.
     */
    description?: pulumi.Input<string | undefined>;
    /**
     * The display name of the tax rates as it will appear to your customer on their receipt email, PDF, and the hosted invoice page.
     */
    displayName: pulumi.Input<string>;
    /**
     * This specifies if the tax rate is inclusive or exclusive.
     */
    inclusive: pulumi.Input<boolean>;
    /**
     * The jurisdiction for the tax rate. You can use this label field for tax reporting purposes. It also appears on your customer’s invoice.
     */
    jurisdiction?: pulumi.Input<string | undefined>;
    /**
     * Set of [key-value pairs](https://docs.stripe.com/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format.
     */
    metadata?: pulumi.Input<{[key: string]: pulumi.Input<string>} | undefined>;
    /**
     * Tax rate percentage out of 100. For tax calculations with automatic_tax[enabled]=true, this percentage includes the statutory tax rate of non-taxable jurisdictions.
     */
    percentage: pulumi.Input<number>;
    /**
     * [ISO 3166-2 subdivision code](https://en.wikipedia.org/wiki/ISO_3166-2), without country prefix. For example, "NY" for New York, United States.
     */
    state?: pulumi.Input<string | undefined>;
    /**
     * The high-level tax type, such as `vat` or `salesTax`.
     */
    taxType?: pulumi.Input<string | undefined>;
}
