// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * A Reader represents a physical device for accepting payment details.
 *
 * Related guide: [Connecting to a reader](https://docs.stripe.com/terminal/payments/connect-reader)
 */
export class TerminalReader extends pulumi.CustomResource {
    /**
     * Get an existing TerminalReader resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: TerminalReaderState, opts?: pulumi.CustomResourceOptions): TerminalReader {
        return new TerminalReader(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'stripe:index/terminalReader:TerminalReader';

    /**
     * Returns true if the given object is an instance of TerminalReader.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is TerminalReader {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === TerminalReader.__pulumiType;
    }

    /**
     * The most recent action performed by the reader.
     */
    declare public /*out*/ readonly action: pulumi.Output<outputs.TerminalReaderAction>;
    /**
     * The current software version of the reader.
     */
    declare public /*out*/ readonly deviceSwVersion: pulumi.Output<string>;
    /**
     * Device type of the reader.
     */
    declare public /*out*/ readonly deviceType: pulumi.Output<string>;
    /**
     * The local IP address of the reader.
     */
    declare public /*out*/ readonly ipAddress: pulumi.Output<string>;
    /**
     * Custom label given to the reader for easier identification.
     */
    declare public readonly label: pulumi.Output<string>;
    /**
     * If the object exists in live mode, the value is `true`. If the object exists in test mode, the value is `false`.
     */
    declare public /*out*/ readonly livemode: pulumi.Output<boolean>;
    /**
     * The location identifier of the reader.
     */
    declare public readonly location: pulumi.Output<string>;
    /**
     * Set of [key-value pairs](https://docs.stripe.com/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format.
     */
    declare public readonly metadata: pulumi.Output<{[key: string]: string}>;
    /**
     * String representing the object's type. Objects of the same type share the same value.
     */
    declare public /*out*/ readonly object: pulumi.Output<string>;
    /**
     * **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * A code generated by the reader used for registering to an account.
     */
    declare public readonly registrationCode: pulumi.Output<string>;
    /**
     * Serial number of the reader.
     */
    declare public /*out*/ readonly serialNumber: pulumi.Output<string>;
    /**
     * The networking status of the reader. We do not recommend using this field in flows that may block taking payments.
     */
    declare public /*out*/ readonly status: pulumi.Output<string>;

    /**
     * Create a TerminalReader resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: TerminalReaderArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: TerminalReaderArgs | TerminalReaderState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as TerminalReaderState | undefined;
            resourceInputs["action"] = state?.action;
            resourceInputs["deviceSwVersion"] = state?.deviceSwVersion;
            resourceInputs["deviceType"] = state?.deviceType;
            resourceInputs["ipAddress"] = state?.ipAddress;
            resourceInputs["label"] = state?.label;
            resourceInputs["livemode"] = state?.livemode;
            resourceInputs["location"] = state?.location;
            resourceInputs["metadata"] = state?.metadata;
            resourceInputs["object"] = state?.object;
            resourceInputs["registrationCode"] = state?.registrationCode;
            resourceInputs["serialNumber"] = state?.serialNumber;
            resourceInputs["status"] = state?.status;
        } else {
            const args = argsOrState as TerminalReaderArgs | undefined;
            if (args?.registrationCode === undefined && !opts.urn) {
                throw new Error("Missing required property 'registrationCode'");
            }
            resourceInputs["label"] = args?.label;
            resourceInputs["location"] = args?.location;
            resourceInputs["metadata"] = args?.metadata;
            resourceInputs["registrationCode"] = args?.registrationCode ? pulumi.secret(args.registrationCode) : undefined;
            resourceInputs["action"] = undefined /*out*/;
            resourceInputs["deviceSwVersion"] = undefined /*out*/;
            resourceInputs["deviceType"] = undefined /*out*/;
            resourceInputs["ipAddress"] = undefined /*out*/;
            resourceInputs["livemode"] = undefined /*out*/;
            resourceInputs["object"] = undefined /*out*/;
            resourceInputs["serialNumber"] = undefined /*out*/;
            resourceInputs["status"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["registrationCode"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(TerminalReader.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering TerminalReader resources.
 */
export interface TerminalReaderState {
    /**
     * The most recent action performed by the reader.
     */
    action?: pulumi.Input<inputs.TerminalReaderAction | undefined>;
    /**
     * The current software version of the reader.
     */
    deviceSwVersion?: pulumi.Input<string | undefined>;
    /**
     * Device type of the reader.
     */
    deviceType?: pulumi.Input<string | undefined>;
    /**
     * The local IP address of the reader.
     */
    ipAddress?: pulumi.Input<string | undefined>;
    /**
     * Custom label given to the reader for easier identification.
     */
    label?: pulumi.Input<string | undefined>;
    /**
     * If the object exists in live mode, the value is `true`. If the object exists in test mode, the value is `false`.
     */
    livemode?: pulumi.Input<boolean | undefined>;
    /**
     * The location identifier of the reader.
     */
    location?: pulumi.Input<string | undefined>;
    /**
     * Set of [key-value pairs](https://docs.stripe.com/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format.
     */
    metadata?: pulumi.Input<{[key: string]: pulumi.Input<string>} | undefined>;
    /**
     * String representing the object's type. Objects of the same type share the same value.
     */
    object?: pulumi.Input<string | undefined>;
    /**
     * **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * A code generated by the reader used for registering to an account.
     */
    registrationCode?: pulumi.Input<string | undefined>;
    /**
     * Serial number of the reader.
     */
    serialNumber?: pulumi.Input<string | undefined>;
    /**
     * The networking status of the reader. We do not recommend using this field in flows that may block taking payments.
     */
    status?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a TerminalReader resource.
 */
export interface TerminalReaderArgs {
    /**
     * Custom label given to the reader for easier identification.
     */
    label?: pulumi.Input<string | undefined>;
    /**
     * The location identifier of the reader.
     */
    location?: pulumi.Input<string | undefined>;
    /**
     * Set of [key-value pairs](https://docs.stripe.com/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format.
     */
    metadata?: pulumi.Input<{[key: string]: pulumi.Input<string>} | undefined>;
    /**
     * **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * A code generated by the reader used for registering to an account.
     */
    registrationCode: pulumi.Input<string>;
}
