// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * Stripe Treasury provides users with a container for money called a FinancialAccount that is separate from their Payments balance.
 * FinancialAccounts serve as the source and destination of Treasury’s money movement APIs.
 */
export class TreasuryFinancialAccount extends pulumi.CustomResource {
    /**
     * Get an existing TreasuryFinancialAccount resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: TreasuryFinancialAccountState, opts?: pulumi.CustomResourceOptions): TreasuryFinancialAccount {
        return new TreasuryFinancialAccount(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'stripe:index/treasuryFinancialAccount:TreasuryFinancialAccount';

    /**
     * Returns true if the given object is an instance of TreasuryFinancialAccount.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is TreasuryFinancialAccount {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === TreasuryFinancialAccount.__pulumiType;
    }

    /**
     * The array of paths to active Features in the Features hash.
     */
    declare public /*out*/ readonly activeFeatures: pulumi.Output<string[]>;
    /**
     * Balance information for the FinancialAccount
     */
    declare public /*out*/ readonly balance: pulumi.Output<outputs.TreasuryFinancialAccountBalance>;
    /**
     * Two-letter country code ([ISO 3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2)).
     */
    declare public /*out*/ readonly country: pulumi.Output<string>;
    /**
     * Time at which the object was created. Measured in seconds since the Unix epoch.
     */
    declare public /*out*/ readonly created: pulumi.Output<number>;
    /**
     * **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * Encodes whether a FinancialAccount has access to a particular Feature, with a `status` enum and associated `statusDetails`.
     * Stripe or the platform can control Features via the requested field.
     */
    declare public readonly features: pulumi.Output<outputs.TreasuryFinancialAccountFeatures | undefined>;
    /**
     * The set of credentials that resolve to a FinancialAccount.
     */
    declare public /*out*/ readonly financialAddresses: pulumi.Output<outputs.TreasuryFinancialAccountFinancialAddress[]>;
    declare public /*out*/ readonly isDefault: pulumi.Output<boolean>;
    /**
     * If the object exists in live mode, the value is `true`. If the object exists in test mode, the value is `false`.
     */
    declare public /*out*/ readonly livemode: pulumi.Output<boolean>;
    /**
     * Set of [key-value pairs](https://docs.stripe.com/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format.
     */
    declare public readonly metadata: pulumi.Output<{[key: string]: string}>;
    /**
     * The nickname for the FinancialAccount.
     */
    declare public readonly nickname: pulumi.Output<string>;
    /**
     * String representing the object's type. Objects of the same type share the same value.
     */
    declare public /*out*/ readonly object: pulumi.Output<string>;
    /**
     * The array of paths to pending Features in the Features hash.
     */
    declare public /*out*/ readonly pendingFeatures: pulumi.Output<string[]>;
    /**
     * The set of functionalities that the platform can restrict on the FinancialAccount.
     */
    declare public readonly platformRestrictions: pulumi.Output<outputs.TreasuryFinancialAccountPlatformRestrictions>;
    /**
     * The array of paths to restricted Features in the Features hash.
     */
    declare public /*out*/ readonly restrictedFeatures: pulumi.Output<string[]>;
    /**
     * Status of this FinancialAccount.
     */
    declare public /*out*/ readonly status: pulumi.Output<string>;
    declare public /*out*/ readonly statusDetails: pulumi.Output<outputs.TreasuryFinancialAccountStatusDetails>;
    /**
     * The currencies the FinancialAccount can hold a balance in. Three-letter [ISO currency code](https://www.iso.org/iso-4217-currency-codes.html), in lowercase.
     */
    declare public readonly supportedCurrencies: pulumi.Output<string[]>;

    /**
     * Create a TreasuryFinancialAccount resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: TreasuryFinancialAccountArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: TreasuryFinancialAccountArgs | TreasuryFinancialAccountState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as TreasuryFinancialAccountState | undefined;
            resourceInputs["activeFeatures"] = state?.activeFeatures;
            resourceInputs["balance"] = state?.balance;
            resourceInputs["country"] = state?.country;
            resourceInputs["created"] = state?.created;
            resourceInputs["features"] = state?.features;
            resourceInputs["financialAddresses"] = state?.financialAddresses;
            resourceInputs["isDefault"] = state?.isDefault;
            resourceInputs["livemode"] = state?.livemode;
            resourceInputs["metadata"] = state?.metadata;
            resourceInputs["nickname"] = state?.nickname;
            resourceInputs["object"] = state?.object;
            resourceInputs["pendingFeatures"] = state?.pendingFeatures;
            resourceInputs["platformRestrictions"] = state?.platformRestrictions;
            resourceInputs["restrictedFeatures"] = state?.restrictedFeatures;
            resourceInputs["status"] = state?.status;
            resourceInputs["statusDetails"] = state?.statusDetails;
            resourceInputs["supportedCurrencies"] = state?.supportedCurrencies;
        } else {
            const args = argsOrState as TreasuryFinancialAccountArgs | undefined;
            if (args?.supportedCurrencies === undefined && !opts.urn) {
                throw new Error("Missing required property 'supportedCurrencies'");
            }
            resourceInputs["features"] = args?.features ? pulumi.secret(args.features) : undefined;
            resourceInputs["metadata"] = args?.metadata;
            resourceInputs["nickname"] = args?.nickname;
            resourceInputs["platformRestrictions"] = args?.platformRestrictions;
            resourceInputs["supportedCurrencies"] = args?.supportedCurrencies;
            resourceInputs["activeFeatures"] = undefined /*out*/;
            resourceInputs["balance"] = undefined /*out*/;
            resourceInputs["country"] = undefined /*out*/;
            resourceInputs["created"] = undefined /*out*/;
            resourceInputs["financialAddresses"] = undefined /*out*/;
            resourceInputs["isDefault"] = undefined /*out*/;
            resourceInputs["livemode"] = undefined /*out*/;
            resourceInputs["object"] = undefined /*out*/;
            resourceInputs["pendingFeatures"] = undefined /*out*/;
            resourceInputs["restrictedFeatures"] = undefined /*out*/;
            resourceInputs["status"] = undefined /*out*/;
            resourceInputs["statusDetails"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["features"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(TreasuryFinancialAccount.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering TreasuryFinancialAccount resources.
 */
export interface TreasuryFinancialAccountState {
    /**
     * The array of paths to active Features in the Features hash.
     */
    activeFeatures?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * Balance information for the FinancialAccount
     */
    balance?: pulumi.Input<inputs.TreasuryFinancialAccountBalance | undefined>;
    /**
     * Two-letter country code ([ISO 3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2)).
     */
    country?: pulumi.Input<string | undefined>;
    /**
     * Time at which the object was created. Measured in seconds since the Unix epoch.
     */
    created?: pulumi.Input<number | undefined>;
    /**
     * **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * Encodes whether a FinancialAccount has access to a particular Feature, with a `status` enum and associated `statusDetails`.
     * Stripe or the platform can control Features via the requested field.
     */
    features?: pulumi.Input<inputs.TreasuryFinancialAccountFeatures | undefined>;
    /**
     * The set of credentials that resolve to a FinancialAccount.
     */
    financialAddresses?: pulumi.Input<pulumi.Input<inputs.TreasuryFinancialAccountFinancialAddress>[] | undefined>;
    isDefault?: pulumi.Input<boolean | undefined>;
    /**
     * If the object exists in live mode, the value is `true`. If the object exists in test mode, the value is `false`.
     */
    livemode?: pulumi.Input<boolean | undefined>;
    /**
     * Set of [key-value pairs](https://docs.stripe.com/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format.
     */
    metadata?: pulumi.Input<{[key: string]: pulumi.Input<string>} | undefined>;
    /**
     * The nickname for the FinancialAccount.
     */
    nickname?: pulumi.Input<string | undefined>;
    /**
     * String representing the object's type. Objects of the same type share the same value.
     */
    object?: pulumi.Input<string | undefined>;
    /**
     * The array of paths to pending Features in the Features hash.
     */
    pendingFeatures?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * The set of functionalities that the platform can restrict on the FinancialAccount.
     */
    platformRestrictions?: pulumi.Input<inputs.TreasuryFinancialAccountPlatformRestrictions | undefined>;
    /**
     * The array of paths to restricted Features in the Features hash.
     */
    restrictedFeatures?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * Status of this FinancialAccount.
     */
    status?: pulumi.Input<string | undefined>;
    statusDetails?: pulumi.Input<inputs.TreasuryFinancialAccountStatusDetails | undefined>;
    /**
     * The currencies the FinancialAccount can hold a balance in. Three-letter [ISO currency code](https://www.iso.org/iso-4217-currency-codes.html), in lowercase.
     */
    supportedCurrencies?: pulumi.Input<pulumi.Input<string>[] | undefined>;
}

/**
 * The set of arguments for constructing a TreasuryFinancialAccount resource.
 */
export interface TreasuryFinancialAccountArgs {
    /**
     * **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * Encodes whether a FinancialAccount has access to a particular Feature, with a `status` enum and associated `statusDetails`.
     * Stripe or the platform can control Features via the requested field.
     */
    features?: pulumi.Input<inputs.TreasuryFinancialAccountFeatures | undefined>;
    /**
     * Set of [key-value pairs](https://docs.stripe.com/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format.
     */
    metadata?: pulumi.Input<{[key: string]: pulumi.Input<string>} | undefined>;
    /**
     * The nickname for the FinancialAccount.
     */
    nickname?: pulumi.Input<string | undefined>;
    /**
     * The set of functionalities that the platform can restrict on the FinancialAccount.
     */
    platformRestrictions?: pulumi.Input<inputs.TreasuryFinancialAccountPlatformRestrictions | undefined>;
    /**
     * The currencies the FinancialAccount can hold a balance in. Three-letter [ISO currency code](https://www.iso.org/iso-4217-currency-codes.html), in lowercase.
     */
    supportedCurrencies: pulumi.Input<pulumi.Input<string>[]>;
}
