// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * A Licensed Item represents a billable item whose pricing is based on license fees. You can use license fees to specify the pricing and create subscriptions to these items.
 */
export class V2BillingLicensedItem extends pulumi.CustomResource {
    /**
     * Get an existing V2BillingLicensedItem resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: V2BillingLicensedItemState, opts?: pulumi.CustomResourceOptions): V2BillingLicensedItem {
        return new V2BillingLicensedItem(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'stripe:index/v2BillingLicensedItem:V2BillingLicensedItem';

    /**
     * Returns true if the given object is an instance of V2BillingLicensedItem.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is V2BillingLicensedItem {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === V2BillingLicensedItem.__pulumiType;
    }

    /**
     * Description that customers will see in the invoice line item. Maximum length of 250 characters.
     */
    declare public readonly displayName: pulumi.Output<string>;
    /**
     * An internal key you can use to search for a particular billable item. Must be unique among billable items. Maximum length of 200 characters.
     */
    declare public readonly lookupKey: pulumi.Output<string>;
    /**
     * Set of [key-value pairs](https://www.terraform.io/docs/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format.
     */
    declare public readonly metadata: pulumi.Output<{[key: string]: string}>;
    /**
     * The unit to use when displaying prices for this billable item in places like Checkout. For example, set this field to \"seat\" for Checkout to display \"(price) per seat\", or \"environment\" to display \"(price) per environment\". Maximum length of 100 characters.
     */
    declare public readonly unitLabel: pulumi.Output<string>;

    /**
     * Create a V2BillingLicensedItem resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: V2BillingLicensedItemArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: V2BillingLicensedItemArgs | V2BillingLicensedItemState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as V2BillingLicensedItemState | undefined;
            resourceInputs["displayName"] = state?.displayName;
            resourceInputs["lookupKey"] = state?.lookupKey;
            resourceInputs["metadata"] = state?.metadata;
            resourceInputs["unitLabel"] = state?.unitLabel;
        } else {
            const args = argsOrState as V2BillingLicensedItemArgs | undefined;
            if (args?.displayName === undefined && !opts.urn) {
                throw new Error("Missing required property 'displayName'");
            }
            resourceInputs["displayName"] = args?.displayName;
            resourceInputs["lookupKey"] = args?.lookupKey;
            resourceInputs["metadata"] = args?.metadata;
            resourceInputs["unitLabel"] = args?.unitLabel;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(V2BillingLicensedItem.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering V2BillingLicensedItem resources.
 */
export interface V2BillingLicensedItemState {
    /**
     * Description that customers will see in the invoice line item. Maximum length of 250 characters.
     */
    displayName?: pulumi.Input<string | undefined>;
    /**
     * An internal key you can use to search for a particular billable item. Must be unique among billable items. Maximum length of 200 characters.
     */
    lookupKey?: pulumi.Input<string | undefined>;
    /**
     * Set of [key-value pairs](https://www.terraform.io/docs/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format.
     */
    metadata?: pulumi.Input<{[key: string]: pulumi.Input<string>} | undefined>;
    /**
     * The unit to use when displaying prices for this billable item in places like Checkout. For example, set this field to \"seat\" for Checkout to display \"(price) per seat\", or \"environment\" to display \"(price) per environment\". Maximum length of 100 characters.
     */
    unitLabel?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a V2BillingLicensedItem resource.
 */
export interface V2BillingLicensedItemArgs {
    /**
     * Description that customers will see in the invoice line item. Maximum length of 250 characters.
     */
    displayName: pulumi.Input<string>;
    /**
     * An internal key you can use to search for a particular billable item. Must be unique among billable items. Maximum length of 200 characters.
     */
    lookupKey?: pulumi.Input<string | undefined>;
    /**
     * Set of [key-value pairs](https://www.terraform.io/docs/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format.
     */
    metadata?: pulumi.Input<{[key: string]: pulumi.Input<string>} | undefined>;
    /**
     * The unit to use when displaying prices for this billable item in places like Checkout. For example, set this field to \"seat\" for Checkout to display \"(price) per seat\", or \"environment\" to display \"(price) per environment\". Maximum length of 100 characters.
     */
    unitLabel?: pulumi.Input<string | undefined>;
}
