// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * A Metered Item represents a billable item whose pricing is based on usage, measured by a meter. You can use rate cards to specify the pricing and create subscriptions to these items.
 */
export class V2BillingMeteredItem extends pulumi.CustomResource {
    /**
     * Get an existing V2BillingMeteredItem resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: V2BillingMeteredItemState, opts?: pulumi.CustomResourceOptions): V2BillingMeteredItem {
        return new V2BillingMeteredItem(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'stripe:index/v2BillingMeteredItem:V2BillingMeteredItem';

    /**
     * Returns true if the given object is an instance of V2BillingMeteredItem.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is V2BillingMeteredItem {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === V2BillingMeteredItem.__pulumiType;
    }

    /**
     * Description that customers will see in the invoice line item. Maximum length of 250 characters.
     */
    declare public readonly displayName: pulumi.Output<string>;
    /**
     * Optional array of Meter dimensions to group event dimension keys for invoice line items.
     */
    declare public readonly invoicePresentationDimensions: pulumi.Output<string[] | undefined>;
    /**
     * An internal key you can use to search for a particular billable item. Must be unique among billable items. Maximum length of 200 characters.
     */
    declare public readonly lookupKey: pulumi.Output<string>;
    /**
     * Set of [key-value pairs](https://www.terraform.io/docs/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format.
     */
    declare public readonly metadata: pulumi.Output<{[key: string]: string}>;
    /**
     * ID of the Meter that measures usage for this Metered Item.
     */
    declare public readonly meter: pulumi.Output<string>;
    /**
     * Optional array of Meter segments to filter event dimension keys for billing.
     */
    declare public readonly meterSegmentConditions: pulumi.Output<outputs.V2BillingMeteredItemMeterSegmentCondition[] | undefined>;
    /**
     * The unit to use when displaying prices for this billable item in places like Checkout. For example, set this field to \"CPU-hour\" for Checkout to display \"(price) per CPU-hour\", or \"1 million events\" to display \"(price) per 1 million events\". Maximum length of 100 characters.
     */
    declare public readonly unitLabel: pulumi.Output<string>;

    /**
     * Create a V2BillingMeteredItem resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: V2BillingMeteredItemArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: V2BillingMeteredItemArgs | V2BillingMeteredItemState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as V2BillingMeteredItemState | undefined;
            resourceInputs["displayName"] = state?.displayName;
            resourceInputs["invoicePresentationDimensions"] = state?.invoicePresentationDimensions;
            resourceInputs["lookupKey"] = state?.lookupKey;
            resourceInputs["metadata"] = state?.metadata;
            resourceInputs["meter"] = state?.meter;
            resourceInputs["meterSegmentConditions"] = state?.meterSegmentConditions;
            resourceInputs["unitLabel"] = state?.unitLabel;
        } else {
            const args = argsOrState as V2BillingMeteredItemArgs | undefined;
            if (args?.displayName === undefined && !opts.urn) {
                throw new Error("Missing required property 'displayName'");
            }
            if (args?.meter === undefined && !opts.urn) {
                throw new Error("Missing required property 'meter'");
            }
            resourceInputs["displayName"] = args?.displayName;
            resourceInputs["invoicePresentationDimensions"] = args?.invoicePresentationDimensions;
            resourceInputs["lookupKey"] = args?.lookupKey;
            resourceInputs["metadata"] = args?.metadata;
            resourceInputs["meter"] = args?.meter;
            resourceInputs["meterSegmentConditions"] = args?.meterSegmentConditions;
            resourceInputs["unitLabel"] = args?.unitLabel;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(V2BillingMeteredItem.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering V2BillingMeteredItem resources.
 */
export interface V2BillingMeteredItemState {
    /**
     * Description that customers will see in the invoice line item. Maximum length of 250 characters.
     */
    displayName?: pulumi.Input<string | undefined>;
    /**
     * Optional array of Meter dimensions to group event dimension keys for invoice line items.
     */
    invoicePresentationDimensions?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * An internal key you can use to search for a particular billable item. Must be unique among billable items. Maximum length of 200 characters.
     */
    lookupKey?: pulumi.Input<string | undefined>;
    /**
     * Set of [key-value pairs](https://www.terraform.io/docs/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format.
     */
    metadata?: pulumi.Input<{[key: string]: pulumi.Input<string>} | undefined>;
    /**
     * ID of the Meter that measures usage for this Metered Item.
     */
    meter?: pulumi.Input<string | undefined>;
    /**
     * Optional array of Meter segments to filter event dimension keys for billing.
     */
    meterSegmentConditions?: pulumi.Input<pulumi.Input<inputs.V2BillingMeteredItemMeterSegmentCondition>[] | undefined>;
    /**
     * The unit to use when displaying prices for this billable item in places like Checkout. For example, set this field to \"CPU-hour\" for Checkout to display \"(price) per CPU-hour\", or \"1 million events\" to display \"(price) per 1 million events\". Maximum length of 100 characters.
     */
    unitLabel?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a V2BillingMeteredItem resource.
 */
export interface V2BillingMeteredItemArgs {
    /**
     * Description that customers will see in the invoice line item. Maximum length of 250 characters.
     */
    displayName: pulumi.Input<string>;
    /**
     * Optional array of Meter dimensions to group event dimension keys for invoice line items.
     */
    invoicePresentationDimensions?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * An internal key you can use to search for a particular billable item. Must be unique among billable items. Maximum length of 200 characters.
     */
    lookupKey?: pulumi.Input<string | undefined>;
    /**
     * Set of [key-value pairs](https://www.terraform.io/docs/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format.
     */
    metadata?: pulumi.Input<{[key: string]: pulumi.Input<string>} | undefined>;
    /**
     * ID of the Meter that measures usage for this Metered Item.
     */
    meter: pulumi.Input<string>;
    /**
     * Optional array of Meter segments to filter event dimension keys for billing.
     */
    meterSegmentConditions?: pulumi.Input<pulumi.Input<inputs.V2BillingMeteredItemMeterSegmentCondition>[] | undefined>;
    /**
     * The unit to use when displaying prices for this billable item in places like Checkout. For example, set this field to \"CPU-hour\" for Checkout to display \"(price) per CPU-hour\", or \"1 million events\" to display \"(price) per 1 million events\". Maximum length of 100 characters.
     */
    unitLabel?: pulumi.Input<string | undefined>;
}
