// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * Set up an event destination to receive events from Stripe across multiple destination types, including [webhook endpoints](https://docs.stripe.com/webhooks) and [Amazon EventBridge](https://docs.stripe.com/event-destinations/eventbridge). Event destinations support receiving [thin events](https://docs.stripe.com/api/v2/events) and [snapshot events](https://docs.stripe.com/api/events).
 */
export class V2CoreEventDestination extends pulumi.CustomResource {
    /**
     * Get an existing V2CoreEventDestination resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: V2CoreEventDestinationState, opts?: pulumi.CustomResourceOptions): V2CoreEventDestination {
        return new V2CoreEventDestination(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'stripe:index/v2CoreEventDestination:V2CoreEventDestination';

    /**
     * Returns true if the given object is an instance of V2CoreEventDestination.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is V2CoreEventDestination {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === V2CoreEventDestination.__pulumiType;
    }

    /**
     * Amazon EventBridge configuration.
     */
    declare public readonly amazonEventbridge: pulumi.Output<outputs.V2CoreEventDestinationAmazonEventbridge | undefined>;
    /**
     * An optional description of what the event destination is used for.
     */
    declare public readonly description: pulumi.Output<string>;
    /**
     * The list of events to enable for this endpoint.
     */
    declare public readonly enabledEvents: pulumi.Output<string[]>;
    /**
     * Payload type of events being subscribed to.
     */
    declare public readonly eventPayload: pulumi.Output<string>;
    /**
     * Where events should be routed from.
     */
    declare public readonly eventsFroms: pulumi.Output<string[]>;
    /**
     * Metadata.
     */
    declare public readonly metadata: pulumi.Output<{[key: string]: string}>;
    /**
     * Event destination name.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * If using the snapshot event payload, the API version events are rendered as.
     */
    declare public readonly snapshotApiVersion: pulumi.Output<string>;
    /**
     * Status. It can be set to either enabled or disabled.
     */
    declare public /*out*/ readonly status: pulumi.Output<string>;
    /**
     * Event destination type.
     */
    declare public readonly type: pulumi.Output<string>;
    /**
     * Webhook endpoint configuration.
     */
    declare public readonly webhookEndpoint: pulumi.Output<outputs.V2CoreEventDestinationWebhookEndpoint | undefined>;

    /**
     * Create a V2CoreEventDestination resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: V2CoreEventDestinationArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: V2CoreEventDestinationArgs | V2CoreEventDestinationState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as V2CoreEventDestinationState | undefined;
            resourceInputs["amazonEventbridge"] = state?.amazonEventbridge;
            resourceInputs["description"] = state?.description;
            resourceInputs["enabledEvents"] = state?.enabledEvents;
            resourceInputs["eventPayload"] = state?.eventPayload;
            resourceInputs["eventsFroms"] = state?.eventsFroms;
            resourceInputs["metadata"] = state?.metadata;
            resourceInputs["name"] = state?.name;
            resourceInputs["snapshotApiVersion"] = state?.snapshotApiVersion;
            resourceInputs["status"] = state?.status;
            resourceInputs["type"] = state?.type;
            resourceInputs["webhookEndpoint"] = state?.webhookEndpoint;
        } else {
            const args = argsOrState as V2CoreEventDestinationArgs | undefined;
            if (args?.enabledEvents === undefined && !opts.urn) {
                throw new Error("Missing required property 'enabledEvents'");
            }
            if (args?.eventPayload === undefined && !opts.urn) {
                throw new Error("Missing required property 'eventPayload'");
            }
            if (args?.type === undefined && !opts.urn) {
                throw new Error("Missing required property 'type'");
            }
            resourceInputs["amazonEventbridge"] = args?.amazonEventbridge;
            resourceInputs["description"] = args?.description;
            resourceInputs["enabledEvents"] = args?.enabledEvents;
            resourceInputs["eventPayload"] = args?.eventPayload;
            resourceInputs["eventsFroms"] = args?.eventsFroms;
            resourceInputs["metadata"] = args?.metadata;
            resourceInputs["name"] = args?.name;
            resourceInputs["snapshotApiVersion"] = args?.snapshotApiVersion;
            resourceInputs["type"] = args?.type;
            resourceInputs["webhookEndpoint"] = args?.webhookEndpoint;
            resourceInputs["status"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(V2CoreEventDestination.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering V2CoreEventDestination resources.
 */
export interface V2CoreEventDestinationState {
    /**
     * Amazon EventBridge configuration.
     */
    amazonEventbridge?: pulumi.Input<inputs.V2CoreEventDestinationAmazonEventbridge | undefined>;
    /**
     * An optional description of what the event destination is used for.
     */
    description?: pulumi.Input<string | undefined>;
    /**
     * The list of events to enable for this endpoint.
     */
    enabledEvents?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * Payload type of events being subscribed to.
     */
    eventPayload?: pulumi.Input<string | undefined>;
    /**
     * Where events should be routed from.
     */
    eventsFroms?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * Metadata.
     */
    metadata?: pulumi.Input<{[key: string]: pulumi.Input<string>} | undefined>;
    /**
     * Event destination name.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * If using the snapshot event payload, the API version events are rendered as.
     */
    snapshotApiVersion?: pulumi.Input<string | undefined>;
    /**
     * Status. It can be set to either enabled or disabled.
     */
    status?: pulumi.Input<string | undefined>;
    /**
     * Event destination type.
     */
    type?: pulumi.Input<string | undefined>;
    /**
     * Webhook endpoint configuration.
     */
    webhookEndpoint?: pulumi.Input<inputs.V2CoreEventDestinationWebhookEndpoint | undefined>;
}

/**
 * The set of arguments for constructing a V2CoreEventDestination resource.
 */
export interface V2CoreEventDestinationArgs {
    /**
     * Amazon EventBridge configuration.
     */
    amazonEventbridge?: pulumi.Input<inputs.V2CoreEventDestinationAmazonEventbridge | undefined>;
    /**
     * An optional description of what the event destination is used for.
     */
    description?: pulumi.Input<string | undefined>;
    /**
     * The list of events to enable for this endpoint.
     */
    enabledEvents: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Payload type of events being subscribed to.
     */
    eventPayload: pulumi.Input<string>;
    /**
     * Where events should be routed from.
     */
    eventsFroms?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * Metadata.
     */
    metadata?: pulumi.Input<{[key: string]: pulumi.Input<string>} | undefined>;
    /**
     * Event destination name.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * If using the snapshot event payload, the API version events are rendered as.
     */
    snapshotApiVersion?: pulumi.Input<string | undefined>;
    /**
     * Event destination type.
     */
    type: pulumi.Input<string>;
    /**
     * Webhook endpoint configuration.
     */
    webhookEndpoint?: pulumi.Input<inputs.V2CoreEventDestinationWebhookEndpoint | undefined>;
}
